import {
  Hash,
  Palette,
  Users,
  UtensilsCrossed,
  PawPrint,
  Handshake,
  CloudSun,
  Shirt,
  Sofa,
  PersonStanding,
  Clock,
  Car,
  Briefcase,
  Smile,
  ShoppingBag,
  Laptop,
  Leaf,
  HeartPulse,
  GraduationCap,
  Brain,
  Landmark,
  Sunrise,
  Puzzle,
  MapPin,
  School,
  Megaphone,
  Lightbulb,
  FlaskConical,
  BookMarked,
  Equal,
  Type,
  Repeat,
  Layers,
  UserCheck,
  History,
  RefreshCw,
  TrendingUp,
  ListOrdered,
  MapPinned,
  ShieldCheck,
  Rocket,
  CheckCheck,
  Rewind,
  GitBranch,
  GitFork,
  GitCompare,
  GitMerge,
  ArrowLeftRight,
  MessageSquareQuote,
  Link2,
  Search,
  CalendarClock,
  RotateCcw,
  FlipVertical,
  SplitSquareHorizontal,
  ShieldQuestion,
  Sparkles,
  Repeat2,
  BookOpen,
  PenLine,
  type LucideIcon,
} from "lucide-react";

// Per-topic icons so the topic list reads as "each subject drawn
// appropriately" rather than the same book glyph repeated down the page.
// Unmapped slugs (new content not yet added here) fall back to a
// sensible per-kind default instead of breaking.
const VOCABULARY_ICONS: Record<string, LucideIcon> = {
  numbers: Hash,
  colors: Palette,
  family: Users,
  "food-drink": UtensilsCrossed,
  animals: PawPrint,
  greetings: Handshake,
  weather: CloudSun,
  clothes: Shirt,
  "house-furniture": Sofa,
  "body-parts": PersonStanding,
  "time-days": Clock,
  transportation: Car,
  "jobs-professions": Briefcase,
  "emotions-feelings": Smile,
  shopping: ShoppingBag,
  technology: Laptop,
  "environment-climate": Leaf,
  "health-wellness": HeartPulse,
  "business-negotiation": Handshake,
  "academic-writing": GraduationCap,
  "abstract-concepts": Brain,
  "formal-register": Landmark,
  "daily-routines": Sunrise,
  hobbies: Puzzle,
  "places-in-town": MapPin,
  school: School,
  "rhetoric-persuasion": Megaphone,
  "psychology-cognition": Lightbulb,
  "scientific-inquiry": FlaskConical,
  "literary-analysis": BookMarked,
};

const GRAMMAR_ICONS: Record<string, LucideIcon> = {
  "verb-to-be": Equal,
  articles: Type,
  "present-simple": Repeat,
  plurals: Layers,
  "possessive-adjectives": UserCheck,
  "past-simple": History,
  "present-continuous": RefreshCw,
  "comparatives-superlatives": TrendingUp,
  "countable-uncountable": ListOrdered,
  "prepositions-time-place": MapPinned,
  "modals-can-must-should": ShieldCheck,
  "future-going-to": Rocket,
  "present-perfect": CheckCheck,
  "past-continuous": Rewind,
  "first-conditional": GitBranch,
  "second-conditional": GitFork,
  "passive-voice": ArrowLeftRight,
  "reported-speech": MessageSquareQuote,
  "relative-clauses": Link2,
  "modals-of-deduction": Search,
  "past-perfect": CalendarClock,
  "used-to-would": RotateCcw,
  "third-conditional": GitCompare,
  inversion: FlipVertical,
  "cleft-sentences": SplitSquareHorizontal,
  "advanced-modals-past": ShieldQuestion,
  "mixed-conditionals": GitMerge,
  subjunctive: Sparkles,
  "gerunds-infinitives-meaning": Repeat2,
};

export function getTopicIcon(kind: "vocabulary" | "grammar", slug: string): LucideIcon {
  if (kind === "vocabulary") return VOCABULARY_ICONS[slug] ?? BookOpen;
  return GRAMMAR_ICONS[slug] ?? PenLine;
}
