// Vocabulary set 2: new topics for A2 to C1, where the inventory showed
// 50 to 70 words per level. Rows match VOCAB_TOPICS in levelExpansion.mjs:
// [headword, ipa (American, like the rest of the table), part of speech,
//  Hebrew, example (uses the word), plain English definition].
// All examples are original.

export const VOCAB_TOPICS = [
  // ---------------- A2 ----------------
  {
    slug: "at-the-doctor",
    name_he: "אצל הרופא",
    name_en: "At the Doctor",
    level: "A2",
    sort: 40,
    words: [
      ["headache", "/ˈhedeɪk/", "noun", "כאב ראש", "I have a terrible headache, so I'm going to bed early.", "a pain in your head"],
      ["fever", "/ˈfiːvər/", "noun", "חום גבוה", "The baby has a fever and doesn't want to eat.", "a body temperature that is higher than normal"],
      ["cough", "/kɔːf/", "noun", "שיעול", "This syrup is good for a dry cough.", "the sound of pushing air out of your throat suddenly"],
      ["medicine", "/ˈmedɪsən/", "noun", "תרופה", "Take this medicine three times a day after meals.", "something you take to get better when you are ill"],
      ["appointment", "/əˈpɔɪntmənt/", "noun", "תור", "I have an appointment with the dentist at four.", "a time you arrange to see someone, like a doctor"],
      ["pill", "/pɪl/", "noun", "כדור", "Take one pill before you go to sleep.", "a small round piece of medicine that you swallow"],
      ["hurt", "/hɜːrt/", "verb", "לכאוב", "My back hurts when I sit for a long time.", "to feel pain in a part of your body"],
      ["sick", "/sɪk/", "adjective", "חולה", "She stayed home from work because she felt sick.", "not healthy; ill"],
      ["rest", "/rest/", "verb", "לנוח", "The doctor told me to rest for a few days.", "to relax or sleep so your body can get better"],
      ["temperature", "/ˈtemprətʃər/", "noun", "חום הגוף", "The nurse took my temperature and said it was normal.", "how hot your body is"],
    ],
  },
  {
    slug: "sports-fitness",
    name_he: "ספורט וכושר",
    name_en: "Sports & Fitness",
    level: "A2",
    sort: 41,
    words: [
      ["team", "/tiːm/", "noun", "קבוצה", "Our team won the match on Saturday.", "a group of people who play a sport together"],
      ["match", "/mætʃ/", "noun", "משחק", "The match starts at eight o'clock.", "a sports game between two players or teams"],
      ["score", "/skɔːr/", "verb", "להבקיע", "He scored two goals in the first half.", "to get a point or a goal in a game"],
      ["lose", "/luːz/", "verb", "להפסיד", "If we lose this game, we're out of the cup.", "to not win a game or competition"],
      ["player", "/ˈpleɪər/", "noun", "שחקן", "She is the best player in the club.", "a person who takes part in a sport or game"],
      ["coach", "/koʊtʃ/", "noun", "מאמן", "The coach told us to run faster.", "a person who trains a sports player or team"],
      ["gym", "/dʒɪm/", "noun", "חדר כושר", "I go to the gym three times a week.", "a room or building with equipment for exercise"],
      ["race", "/reɪs/", "noun", "מרוץ", "He finished the race in second place.", "a competition to see who is the fastest"],
      ["fit", "/fɪt/", "adjective", "בכושר", "Swimming is a great way to stay fit.", "healthy and strong because you exercise"],
      ["stadium", "/ˈsteɪdiəm/", "noun", "אצטדיון", "The stadium was full for the final.", "a large place with seats around a sports field"],
    ],
  },
  {
    slug: "celebrations",
    name_he: "חגים ואירועים",
    name_en: "Celebrations",
    level: "A2",
    sort: 42,
    words: [
      ["wedding", "/ˈwedɪŋ/", "noun", "חתונה", "Their wedding was on the beach in Caesarea.", "a ceremony where two people get married"],
      ["guest", "/ɡest/", "noun", "אורח", "We invited fifty guests to the party.", "a person you invite to your home or to an event"],
      ["invite", "/ɪnˈvaɪt/", "verb", "להזמין", "Did you invite your neighbors to the party?", "to ask someone to come to an event"],
      ["gift", "/ɡɪft/", "noun", "מתנה", "Thank you for the beautiful gift.", "something you give to someone; a present"],
      ["celebrate", "/ˈseləbreɪt/", "verb", "לחגוג", "How do you celebrate the new year?", "to do something special because of a happy event"],
      ["candle", "/ˈkændəl/", "noun", "נר", "There were ten candles on the cake.", "a stick of wax that you burn to give light"],
      ["decorate", "/ˈdekəreɪt/", "verb", "לקשט", "The children decorated the room with balloons.", "to make something look nicer by adding things to it"],
      ["holiday", "/ˈhɑːlədeɪ/", "noun", "חג", "Passover is my favorite holiday.", "a special day when people celebrate and often do not work"],
      ["congratulations", "/kənˌɡrætʃəˈleɪʃənz/", "exclamation", "מזל טוב", "Congratulations on your new job!", "what you say when someone has done something good"],
      ["anniversary", "/ˌænɪˈvɜːrsəri/", "noun", "יום נישואים", "My parents went out for dinner on their anniversary.", "the same date as an important event in an earlier year"],
    ],
  },

  // ---------------- B1 ----------------
  {
    slug: "housing-renting",
    name_he: "דיור ושכירות",
    name_en: "Housing & Renting",
    level: "B1",
    sort: 43,
    words: [
      ["rent", "/rent/", "verb", "לשכור", "We rent a small apartment near the university.", "to pay money to live in or use something that someone else owns"],
      ["landlord", "/ˈlændlɔːrd/", "noun", "בעל הדירה", "The landlord fixed the heater the same day.", "a person who rents a home to someone else"],
      ["tenant", "/ˈtenənt/", "noun", "שוכר", "The new tenants are moving in on Sunday.", "a person who pays rent to live somewhere"],
      ["lease", "/liːs/", "noun", "חוזה שכירות", "We signed a one-year lease.", "a legal agreement to rent a home for a period of time"],
      ["deposit", "/dɪˈpɑːzɪt/", "noun", "פיקדון", "You'll get your deposit back when you leave, if nothing is damaged.", "money you pay at the start that you get back later"],
      ["utilities", "/juːˈtɪlətiz/", "noun", "חשבונות חשמל, מים וגז", "Does the rent include utilities?", "services like electricity, water and gas"],
      ["furnished", "/ˈfɜːrnɪʃt/", "adjective", "מרוהט", "The apartment is fully furnished, so we only need our clothes.", "with furniture already in it"],
      ["move in", "/muːv ɪn/", "phrasal verb", "לעבור לגור", "When can we move in?", "to start living in a new home"],
      ["roommate", "/ˈruːmmeɪt/", "noun", "שותף לדירה", "My roommate cooks dinner on Fridays.", "a person you share a home with"],
      ["landlady", "/ˈlændleɪdi/", "noun", "בעלת הדירה", "Our landlady lives on the top floor.", "a woman who rents a home to someone else"],
    ],
  },
  {
    slug: "eating-out",
    name_he: "אוכל בחוץ",
    name_en: "Eating Out",
    level: "B1",
    sort: 44,
    words: [
      ["menu", "/ˈmenjuː/", "noun", "תפריט", "Could we see the menu, please?", "a list of the food you can order in a restaurant"],
      ["waiter", "/ˈweɪtər/", "noun", "מלצר", "The waiter brought us some bread while we waited.", "a person who serves food in a restaurant"],
      ["tip", "/tɪp/", "noun", "טיפ", "We left a ten percent tip.", "extra money you give to thank someone for a service"],
      ["napkin", "/ˈnæpkɪn/", "noun", "מפית", "Could we have some more napkins, please?", "a piece of paper or cloth for cleaning your mouth and hands"],
      ["dish", "/dɪʃ/", "noun", "מנה", "The fish is their most popular dish.", "food cooked in a particular way, as part of a meal"],
      ["spicy", "/ˈspaɪsi/", "adjective", "חריף", "Is the soup very spicy?", "with a strong, hot taste"],
      ["dessert", "/dɪˈzɜːrt/", "noun", "קינוח", "Let's share a dessert.", "sweet food you eat at the end of a meal"],
      ["vegetarian", "/ˌvedʒəˈteriən/", "adjective", "צמחוני", "Do you have any vegetarian options?", "without meat or fish"],
      ["appetizer", "/ˈæpɪtaɪzər/", "noun", "מנה ראשונה", "We ordered two appetizers and one main course.", "a small dish you eat before the main part of a meal"],
      ["takeout", "/ˈteɪkaʊt/", "noun", "אוכל לקחת", "We were too tired to cook, so we ordered takeout.", "food you buy at a restaurant and eat at home"],
    ],
  },
  {
    slug: "personality",
    name_he: "אופי ותכונות",
    name_en: "Personality",
    level: "B1",
    sort: 45,
    words: [
      ["honest", "/ˈɑːnɪst/", "adjective", "ישר", "Thank you for being honest with me.", "telling the truth and not cheating"],
      ["generous", "/ˈdʒenərəs/", "adjective", "נדיב", "She is very generous with her time.", "happy to give money, time or help to others"],
      ["lazy", "/ˈleɪzi/", "adjective", "עצלן", "I always feel lazy on Saturday mornings.", "not wanting to work or make an effort"],
      ["shy", "/ʃaɪ/", "adjective", "ביישן", "He was shy at first, but now he talks a lot.", "nervous about talking to people you don't know"],
      ["confident", "/ˈkɑːnfɪdənt/", "adjective", "בטוח בעצמו", "She sounded confident in the interview.", "sure about yourself and your abilities"],
      ["patient", "/ˈpeɪʃənt/", "adjective", "סבלני", "Good teachers are patient with their students.", "able to wait or deal with problems without getting angry"],
      ["selfish", "/ˈselfɪʃ/", "adjective", "אנוכי", "It was selfish of him to take the last piece.", "thinking only about yourself"],
      ["reliable", "/rɪˈlaɪəbəl/", "adjective", "אמין", "We need someone reliable to look after the shop.", "someone you can trust to do what they say"],
      ["stubborn", "/ˈstʌbərn/", "adjective", "עקשן", "My grandfather is too stubborn to ask for help.", "not willing to change your mind"],
      ["cheerful", "/ˈtʃɪrfəl/", "adjective", "עליז", "She is always cheerful, even on Mondays.", "happy and in a good mood"],
    ],
  },

  // ---------------- B2 ----------------
  {
    slug: "arts-culture",
    name_he: "אמנות ותרבות",
    name_en: "Arts & Culture",
    level: "B2",
    sort: 46,
    words: [
      ["exhibition", "/ˌeksɪˈbɪʃən/", "noun", "תערוכה", "The museum has a new photography exhibition.", "a show of art or objects that people come to see"],
      ["orchestra", "/ˈɔːrkɪstrə/", "noun", "תזמורת", "The orchestra played for almost two hours.", "a large group of musicians who play together"],
      ["performance", "/pərˈfɔːrməns/", "noun", "הופעה", "Her performance in the play was brilliant.", "the act of playing, singing or acting in front of people"],
      ["masterpiece", "/ˈmæstərpiːs/", "noun", "יצירת מופת", "Many people consider it his masterpiece.", "the best work of an artist or writer"],
      ["critic", "/ˈkrɪtɪk/", "noun", "מבקר", "The critics loved the new album.", "a person whose job is to judge films, books or art"],
      ["sculpture", "/ˈskʌlptʃər/", "noun", "פסל", "There is a huge metal sculpture outside the theater.", "a piece of art made from stone, metal or wood"],
      ["gallery", "/ˈɡæləri/", "noun", "גלריה", "We spent the afternoon in a small art gallery.", "a room or building where art is shown"],
      ["plot", "/plɑːt/", "noun", "עלילה", "The plot was hard to follow, but the acting was great.", "the story of a book, film or play"],
      ["rehearsal", "/rɪˈhɜːrsəl/", "noun", "חזרה", "The band has a rehearsal every Thursday.", "a practice before a real performance"],
      ["contemporary", "/kənˈtempəreri/", "adjective", "עכשווי", "I'm not a big fan of contemporary art.", "belonging to the present time; modern"],
    ],
  },
  {
    slug: "careers",
    name_he: "קריירה",
    name_en: "Careers",
    level: "B2",
    sort: 47,
    words: [
      ["pension", "/ˈpenʃən/", "noun", "פנסיה", "She has paid into a pension since her first job.", "money paid regularly to someone after they stop working"],
      ["quit", "/kwɪt/", "verb", "לעזוב עבודה", "He quit his job to travel around South America.", "to leave a job because you choose to"],
      ["applicant", "/ˈæplɪkənt/", "noun", "מועמד", "There were over a hundred applicants for the job.", "a person who asks for a job or a place somewhere"],
      ["qualification", "/ˌkwɑːlɪfɪˈkeɪʃən/", "noun", "הכשרה", "What qualifications do you need to be a nurse?", "a skill or exam that makes you suitable for a job"],
      ["internship", "/ˈɪntɜːrnʃɪp/", "noun", "התמחות", "I did a summer internship at a law firm.", "a short period of work to get experience"],
      ["freelance", "/ˈfriːlæns/", "adjective", "עצמאי", "She works as a freelance designer.", "working for different clients, not for one employer"],
      ["workload", "/ˈwɜːrkloʊd/", "noun", "עומס עבודה", "My workload doubled this month.", "the amount of work you have to do"],
      ["reference", "/ˈrefərəns/", "noun", "המלצה", "My old manager agreed to give me a reference.", "a letter or call from someone who says you are good at your job"],
      ["layoffs", "/ˈleɪɔːfs/", "noun", "פיטורים", "The company announced layoffs last week.", "the ending of workers' jobs because there is not enough work"],
      ["career", "/kəˈrɪr/", "noun", "קריירה", "He started his career as a teacher.", "the jobs you do over your working life"],
    ],
  },
  {
    slug: "society-issues",
    name_he: "חברה ונושאים חברתיים",
    name_en: "Society & Social Issues",
    level: "B2",
    sort: 48,
    words: [
      ["poverty", "/ˈpɑːvərti/", "noun", "עוני", "Millions of children still live in poverty.", "the state of being very poor"],
      ["inequality", "/ˌɪnɪˈkwɑːləti/", "noun", "אי שוויון", "The report looks at income inequality in big cities.", "an unfair difference between groups of people"],
      ["volunteer", "/ˌvɑːlənˈtɪr/", "verb", "להתנדב", "She volunteers at a food bank every week.", "to work for free to help others"],
      ["charity", "/ˈtʃærəti/", "noun", "ארגון צדקה", "All the money from the concert goes to charity.", "an organization that helps people in need"],
      ["community", "/kəˈmjuːnəti/", "noun", "קהילה", "The whole community helped rebuild the school.", "the people who live in one area or share something"],
      ["homeless", "/ˈhoʊmləs/", "adjective", "חסר בית", "The shelter gives homeless people a hot meal.", "without a place to live"],
      ["discrimination", "/dɪˌskrɪmɪˈneɪʃən/", "noun", "אפליה", "The law protects workers from discrimination.", "treating people unfairly because of who they are"],
      ["refugee", "/ˌrefjuˈdʒiː/", "noun", "פליט", "The war forced thousands of refugees to leave their homes.", "a person who has to leave their country because of danger"],
      ["welfare", "/ˈwelfer/", "noun", "רווחה", "The government spends more on welfare this year.", "help from the government for people who need it"],
      ["immigrant", "/ˈɪmɪɡrənt/", "noun", "מהגר", "My grandparents came to Israel as immigrants in 1950.", "a person who comes to live in a new country"],
    ],
  },

  // ---------------- C1 ----------------
  {
    slug: "medicine-healthcare",
    name_he: "רפואה ושירותי בריאות",
    name_en: "Medicine & Healthcare",
    level: "C1",
    sort: 49,
    words: [
      ["ward", "/wɔːrd/", "noun", "מחלקה בבית חולים", "Visitors can come to the children's ward until eight.", "a room or section in a hospital for a group of patients"],
      ["chronic", "/ˈkrɑːnɪk/", "adjective", "כרוני", "She suffers from chronic back pain.", "lasting for a long time or coming back again and again"],
      ["prescription", "/prɪˈskrɪpʃən/", "noun", "מרשם", "You can't buy this drug without a prescription.", "a doctor's written order for medicine"],
      ["side effect", "/ˈsaɪd ɪˌfekt/", "noun", "תופעת לוואי", "Tiredness is a possible side effect of the treatment.", "an extra, usually bad, result of a medicine"],
      ["relapse", "/ˈriːlæps/", "noun", "הישנות המחלה", "After a month of feeling well, she had a relapse.", "a return of an illness after a period of getting better"],
      ["surgeon", "/ˈsɜːrdʒən/", "noun", "מנתח", "The surgeon explained the risks before the operation.", "a doctor who performs operations"],
      ["vaccine", "/vækˈsiːn/", "noun", "חיסון", "The vaccine is free for children under five.", "a substance that protects the body from a disease"],
      ["contagious", "/kənˈteɪdʒəs/", "adjective", "מדבק", "Stay home while you're still contagious.", "able to spread from one person to another"],
      ["outpatient", "/ˈaʊtpeɪʃənt/", "adjective", "אמבולטורי", "It's an outpatient procedure, so you'll go home the same day.", "treated at a hospital without staying the night"],
      ["referral", "/rɪˈfɜːrəl/", "noun", "הפניה", "You need a referral from your family doctor to see a specialist.", "a doctor's note sending you to another doctor"],
    ],
  },
  {
    slug: "attitudes-opinions",
    name_he: "עמדות ודעות",
    name_en: "Attitudes & Opinions",
    level: "C1",
    sort: 50,
    words: [
      ["skeptical", "/ˈskeptɪkəl/", "adjective", "ספקן", "I'm skeptical about diets that promise quick results.", "having doubts that something is true or will work"],
      ["reluctant", "/rɪˈlʌktənt/", "adjective", "מהסס", "He was reluctant to admit his mistake.", "not willing to do something"],
      ["biased", "/ˈbaɪəst/", "adjective", "מוטה", "The article was clearly biased against the plan.", "unfairly supporting one side"],
      ["open-minded", "/ˌoʊpən ˈmaɪndɪd/", "adjective", "פתוח לרעיונות חדשים", "Living abroad has made me more open-minded.", "willing to consider new ideas"],
      ["indifferent", "/ɪnˈdɪfərənt/", "adjective", "אדיש", "Most voters seem indifferent to the issue.", "not interested or not caring about something"],
      ["outspoken", "/aʊtˈspoʊkən/", "adjective", "שאומר את דעתו בגלוי", "She is an outspoken critic of the new law.", "saying what you think openly, even if it upsets people"],
      ["cynical", "/ˈsɪnɪkəl/", "adjective", "ציני", "Years in politics made him cynical about promises.", "believing that people act only for their own good"],
      ["assertive", "/əˈsɜːrtɪv/", "adjective", "אסרטיבי", "You need to be more assertive in meetings.", "confident about saying what you want or think"],
      ["dismissive", "/dɪsˈmɪsɪv/", "adjective", "מזלזל", "Don't be so dismissive of other people's ideas.", "showing that you think something is not worth attention"],
      ["sympathetic", "/ˌsɪmpəˈθetɪk/", "adjective", "מגלה הבנה", "My manager was very sympathetic when my father was ill.", "showing that you understand and care about someone's problem"],
    ],
  },
];
