// Vocabulary set 3: the advanced levels, where the inventory had 60 to 80
// words. Same row shape as vocabSet2.mjs:
// [headword, ipa (American), part of speech, Hebrew, example, definition].
// All examples are original.

export const VOCAB_TOPICS = [
  // ---------------- B2 ----------------
  {
    slug: "digital-life",
    name_he: "חיים דיגיטליים",
    name_en: "Digital Life",
    level: "B2",
    sort: 51,
    words: [
      ["privacy", "/ˈpraɪvəsi/", "noun", "פרטיות", "Check the privacy settings before you post photos of your children.", "the right to keep your personal information to yourself"],
      ["notification", "/ˌnoʊtəfɪˈkeɪʃən/", "noun", "התראה", "I turned off notifications so I could focus on my work.", "a message on your phone telling you something has happened"],
      ["subscription", "/səbˈskrɪpʃən/", "noun", "מנוי", "She cancelled her streaming subscription to save money.", "a regular payment to use a service"],
      ["algorithm", "/ˈælɡərɪðəm/", "noun", "אלגוריתם", "The app's algorithm decides which videos you see first.", "a set of rules a computer follows to make decisions"],
      ["upload", "/ˈʌploʊd/", "verb", "להעלות (קובץ)", "It took ten minutes to upload the video.", "to send a file from your device to the internet"],
      ["browser", "/ˈbraʊzər/", "noun", "דפדפן", "Try opening the website in a different browser.", "a program you use to look at websites"],
      ["screen time", "/ˈskriːn taɪm/", "noun", "זמן מסך", "My screen time doubled during the exams.", "the time you spend looking at a phone or computer"],
      ["hack", "/hæk/", "verb", "לפרוץ (למחשב או לחשבון)", "Someone tried to hack my email account last night.", "to get into a computer system without permission"],
      ["offline", "/ˌɔːfˈlaɪn/", "adjective", "לא מחובר לרשת", "You can read the articles offline once they're downloaded.", "not connected to the internet"],
      ["cyberbullying", "/ˈsaɪbərˌbʊliɪŋ/", "noun", "בריונות ברשת", "The school runs a workshop on cyberbullying every year.", "using the internet to hurt or frighten someone"],
    ],
  },

  // ---------------- C1 ----------------
  {
    slug: "science-technology",
    name_he: "מדע וטכנולוגיה",
    name_en: "Science & Technology",
    level: "C1",
    sort: 52,
    words: [
      ["innovation", "/ˌɪnəˈveɪʃən/", "noun", "חדשנות", "The country invests heavily in innovation and research.", "a new idea, method or product"],
      ["breakthrough", "/ˈbreɪkθruː/", "noun", "פריצת דרך", "The new vaccine was hailed as a major breakthrough.", "an important discovery that solves a problem"],
      ["prototype", "/ˈproʊtətaɪp/", "noun", "אב טיפוס", "The engineers tested the prototype for six months.", "the first model of something, made to test it"],
      ["automation", "/ˌɔːtəˈmeɪʃən/", "noun", "אוטומציה", "Automation has replaced many factory jobs.", "the use of machines to do work that people did"],
      ["patent", "/ˈpætənt/", "noun", "פטנט", "She filed a patent for her new water filter.", "a legal right to be the only one to make or sell an invention"],
      ["obsolete", "/ˌɑːbsəˈliːt/", "adjective", "מיושן, שיצא משימוש", "Fax machines became obsolete almost overnight.", "no longer used because something better exists"],
      ["cutting-edge", "/ˌkʌtɪŋ ˈedʒ/", "adjective", "חדשני ביותר", "The lab uses cutting-edge equipment.", "the most modern and advanced"],
      ["feasible", "/ˈfiːzəbəl/", "adjective", "בר ביצוע", "Is it feasible to finish the project by June?", "possible to do in practice"],
      ["sophisticated", "/səˈfɪstɪkeɪtɪd/", "adjective", "מתוחכם", "The system uses sophisticated software to detect fraud.", "complex and advanced"],
      ["implement", "/ˈɪmplɪment/", "verb", "ליישם", "The company will implement the new system next year.", "to start using a plan or system"],
    ],
  },
  {
    slug: "workplace-dynamics",
    name_he: "יחסים בעבודה",
    name_en: "Workplace Dynamics",
    level: "C1",
    sort: 53,
    words: [
      ["delegate", "/ˈdeləɡeɪt/", "verb", "להאציל סמכויות", "Good managers know how to delegate tasks to their team.", "to give part of your work to someone else"],
      ["burnout", "/ˈbɜːrnaʊt/", "noun", "שחיקה", "Long hours without breaks can lead to burnout.", "extreme tiredness caused by working too hard for too long"],
      ["morale", "/məˈræl/", "noun", "מורל", "Team morale improved after the new manager arrived.", "how confident and positive people in a group feel"],
      ["initiative", "/ɪˈnɪʃətɪv/", "noun", "יוזמה", "She showed initiative by fixing the problem before anyone asked.", "the ability to act without being told what to do"],
      ["hierarchy", "/ˈhaɪərɑːrki/", "noun", "היררכיה", "Start-ups often have a flat hierarchy.", "a system where people are organized in levels of power"],
      ["collaborate", "/kəˈlæbəreɪt/", "verb", "לשתף פעולה", "The two departments collaborated on the new product.", "to work together with someone"],
      ["productivity", "/ˌproʊdʌkˈtɪvəti/", "noun", "פריון", "Productivity dropped during the summer months.", "how much work is done in a period of time"],
      ["mentor", "/ˈmentɔːr/", "noun", "חונך", "My first mentor taught me how to run a meeting.", "an experienced person who advises someone less experienced"],
      ["accountability", "/əˌkaʊntəˈbɪləti/", "noun", "אחריותיות, נשיאה באחריות", "The new policy increases accountability for decisions.", "being responsible for your actions and able to explain them"],
      ["constructive", "/kənˈstrʌktɪv/", "adjective", "בונה", "Thanks for the constructive feedback on my report.", "useful and meant to help improve something"],
    ],
  },
  {
    slug: "culture-heritage",
    name_he: "תרבות ומורשת",
    name_en: "Culture & Heritage",
    level: "C1",
    sort: 54,
    words: [
      ["heritage", "/ˈherɪtɪdʒ/", "noun", "מורשת", "The old city is part of the country's cultural heritage.", "traditions, buildings and history passed down from the past"],
      ["custom", "/ˈkʌstəm/", "noun", "מנהג", "It's a local custom to bring sweets when you visit someone.", "a traditional way of doing something"],
      ["etiquette", "/ˈetɪket/", "noun", "כללי נימוס", "Business etiquette varies a lot between countries.", "the rules of polite behavior"],
      ["cosmopolitan", "/ˌkɑːzməˈpɑːlɪtən/", "adjective", "קוסמופוליטי", "Tel Aviv has a cosmopolitan atmosphere.", "full of people and influences from many countries"],
      ["assimilate", "/əˈsɪməleɪt/", "verb", "להיטמע", "Many immigrants assimilate quickly into the new culture.", "to become part of a new group or culture"],
      ["indigenous", "/ɪnˈdɪdʒənəs/", "adjective", "ילידי", "The museum displays indigenous art from the region.", "belonging to the original people of a place"],
      ["diaspora", "/daɪˈæspərə/", "noun", "תפוצה", "The festival brings together members of the diaspora.", "people who live outside the country their family came from"],
      ["ritual", "/ˈrɪtʃuəl/", "noun", "טקס, ריטואל", "Making coffee is my morning ritual.", "an action always done in the same way, often for a ceremony"],
      ["multicultural", "/ˌmʌltiˈkʌltʃərəl/", "adjective", "רב-תרבותי", "We grew up in a multicultural neighborhood.", "including people of many different cultures"],
      ["preserve", "/prɪˈzɜːrv/", "verb", "לשמר", "Volunteers work to preserve the old synagogue.", "to keep something in its original state"],
    ],
  },

  // ---------------- C2 ----------------
  {
    slug: "philosophy-ethics",
    name_he: "פילוסופיה ואתיקה",
    name_en: "Philosophy & Ethics",
    level: "C2",
    sort: 55,
    words: [
      ["dilemma", "/dɪˈlemə/", "noun", "דילמה", "She faced a moral dilemma between loyalty and honesty.", "a situation where you must choose between two difficult options"],
      ["utilitarian", "/juːˌtɪlɪˈteriən/", "adjective", "תועלתני", "A utilitarian view judges actions by their consequences.", "aiming for the greatest good for the greatest number"],
      ["autonomy", "/ɔːˈtɑːnəmi/", "noun", "אוטונומיה", "Patients have the autonomy to refuse treatment.", "the freedom to make your own decisions"],
      ["integrity", "/ɪnˈteɡrəti/", "noun", "יושרה", "He was respected for his integrity, even by his rivals.", "the quality of being honest and having strong principles"],
      ["virtue", "/ˈvɜːrtʃuː/", "noun", "מידה טובה", "Patience is a virtue I'm still working on.", "a good quality in a person's character"],
      ["determinism", "/dɪˈtɜːrmɪnɪzəm/", "noun", "דטרמיניזם", "Determinism raises hard questions about free will.", "the belief that every event is caused by earlier events"],
      ["relativism", "/ˈrelətɪvɪzəm/", "noun", "רלטיביזם", "Moral relativism holds that right and wrong depend on culture.", "the idea that truth or morality is not the same for everyone"],
      ["conscience", "/ˈkɑːnʃəns/", "noun", "מצפון", "My conscience wouldn't let me keep the money.", "the inner sense of what is right and wrong"],
      ["altruism", "/ˈæltruɪzəm/", "noun", "אלטרואיזם", "Donating a kidney to a stranger is an act of pure altruism.", "caring about others' wellbeing more than your own"],
      ["premise", "/ˈpremɪs/", "noun", "הנחת יסוד", "The argument rests on a questionable premise.", "an idea that an argument is based on"],
    ],
  },
  {
    slug: "law-jurisprudence",
    name_he: "משפט ומשפטנות",
    name_en: "Law & Jurisprudence",
    level: "C2",
    sort: 56,
    words: [
      ["jurisdiction", "/ˌdʒʊrɪsˈdɪkʃən/", "noun", "סמכות שיפוט", "The case falls outside the court's jurisdiction.", "the official power to make legal decisions"],
      ["precedent", "/ˈpresɪdənt/", "noun", "תקדים", "The ruling set an important precedent for future cases.", "an earlier decision used as an example later"],
      ["statute", "/ˈstætʃuːt/", "noun", "חוק כתוב", "The statute was amended in 2019.", "a written law passed by a parliament"],
      ["litigation", "/ˌlɪtɪˈɡeɪʃən/", "noun", "התדיינות משפטית", "The dispute ended in years of costly litigation.", "the process of taking a case to court"],
      ["plaintiff", "/ˈpleɪntɪf/", "noun", "תובע", "The plaintiff claimed the product had caused the injury.", "the person who brings a case against someone in court"],
      ["defendant", "/dɪˈfendənt/", "noun", "נתבע, נאשם", "The defendant denied all the charges.", "the person accused or sued in court"],
      ["injunction", "/ɪnˈdʒʌŋkʃən/", "noun", "צו מניעה", "The court issued an injunction to stop the construction.", "a court order that forbids an action"],
      ["liability", "/ˌlaɪəˈbɪləti/", "noun", "חבות, אחריות משפטית", "The company denied any liability for the accident.", "legal responsibility for something"],
      ["acquittal", "/əˈkwɪtəl/", "noun", "זיכוי", "The trial ended in an acquittal.", "a court decision that someone is not guilty"],
      ["constitutional", "/ˌkɑːnstɪˈtuːʃənəl/", "adjective", "חוקתי", "The judges ruled that the law was not constitutional.", "allowed by or relating to a country's constitution"],
    ],
  },
  {
    slug: "advanced-economics",
    name_he: "כלכלה ופיננסים",
    name_en: "Economics & Finance",
    level: "C2",
    sort: 57,
    words: [
      ["austerity", "/ɔːˈsterəti/", "noun", "צנע", "The government introduced austerity measures to cut the deficit.", "strict cuts in public spending"],
      ["liquidity", "/lɪˈkwɪdəti/", "noun", "נזילות", "The bank faced a liquidity crisis.", "having enough cash or assets that can quickly become cash"],
      ["collateral", "/kəˈlætərəl/", "noun", "בטוחה", "They used the house as collateral for the loan.", "property promised to a lender in case a loan isn't repaid"],
      ["dividend", "/ˈdɪvɪdend/", "noun", "דיבידנד", "Shareholders received a higher dividend this year.", "a share of a company's profit paid to its owners"],
      ["solvency", "/ˈsɑːlvənsi/", "noun", "כושר פירעון", "Investors questioned the firm's solvency.", "the ability to pay all your debts"],
      ["speculation", "/ˌspekjəˈleɪʃən/", "noun", "ספקולציה", "Speculation pushed housing prices to record highs.", "buying something in the hope of selling it for more"],
      ["deficit", "/ˈdefɪsɪt/", "noun", "גירעון", "The budget deficit grew for the third year in a row.", "the amount by which spending is greater than income"],
      ["tariff", "/ˈtærɪf/", "noun", "מכס", "New tariffs made imported cars more expensive.", "a tax on goods coming into a country"],
      ["depreciation", "/dɪˌpriːʃiˈeɪʃən/", "noun", "פחת, ירידת ערך", "The car's depreciation was faster than expected.", "a fall in the value of something over time"],
      ["equity", "/ˈekwəti/", "noun", "הון עצמי", "The founders gave up some equity to raise money.", "the value of a company that belongs to its owners"],
    ],
  },
];
