-- Expands vocabulary from "6 topics, all A1" to 16 topics across
-- A1-B1: 10 new everyday-life topics (weather, clothes, house &
-- furniture, body parts, time & days, transportation, jobs, emotions,
-- shopping, technology), each with 10 words, one MCQ exercise per word,
-- and one match exercise, matching the exact density/format of the
-- original A1 vocabulary batch (seed 001+002). Generated programmatically
-- (not hand-authored) so every MCQ's options/correctIndex are guaranteed
-- correct by construction — verified again below with the same
-- structural validator used for the grammar seeds.
-- Run this AFTER seed 001 and 002 have been applied.
-- Safe to re-run: topics are upserted by slug; vocabulary_items and
-- exercises for these topics are cleared and reinserted.

insert into public.topics (slug, name_he, name_en, cefr_level, sort_order) values
  ('weather', 'מזג אוויר', 'Weather', 'A1', 7),
  ('clothes', 'בגדים', 'Clothes', 'A1', 8),
  ('house-furniture', 'בית ורהיטים', 'House & Furniture', 'A2', 9),
  ('body-parts', 'חלקי הגוף', 'Body Parts', 'A1', 10),
  ('time-days', 'זמן וימות השבוע', 'Time & Days', 'A1', 11),
  ('transportation', 'תחבורה', 'Transportation', 'A2', 12),
  ('jobs-professions', 'מקצועות', 'Jobs & Professions', 'A2', 13),
  ('emotions-feelings', 'רגשות', 'Emotions & Feelings', 'A2', 14),
  ('shopping', 'קניות', 'Shopping', 'A2', 15),
  ('technology', 'טכנולוגיה', 'Technology', 'B1', 16)
on conflict (slug) do update set
  name_he = excluded.name_he,
  name_en = excluded.name_en,
  cefr_level = excluded.cefr_level,
  sort_order = excluded.sort_order;

delete from public.vocabulary_items
where topic_id in (select id from public.topics where slug in ('weather', 'clothes', 'house-furniture', 'body-parts', 'time-days', 'transportation', 'jobs-professions', 'emotions-feelings', 'shopping', 'technology'));

insert into public.vocabulary_items (topic_id, headword, ipa, part_of_speech, translation_he, example_en, cefr_level, sort_order)
select t.id, v.headword, v.ipa, v.part_of_speech, v.translation_he, v.example_en, t.cefr_level, v.sort_order
from public.topics t
join (values
  ('weather', 'sun', '/sʌn/', 'noun', 'שמש', 'The sun is shining today.', 1),
  ('weather', 'rain', '/reɪn/', 'noun', 'גשם', 'I love the sound of rain.', 2),
  ('weather', 'cloud', '/klaʊd/', 'noun', 'ענן', 'There is a big cloud in the sky.', 3),
  ('weather', 'wind', '/wɪnd/', 'noun', 'רוח', 'The wind is very strong today.', 4),
  ('weather', 'snow', '/snəʊ/', 'noun', 'שלג', 'It snows every winter here.', 5),
  ('weather', 'hot', '/hɒt/', 'adjective', 'חם', 'It''s very hot in summer.', 6),
  ('weather', 'cold', '/kəʊld/', 'adjective', 'קר', 'It''s cold outside, wear a coat.', 7),
  ('weather', 'storm', '/stɔːrm/', 'noun', 'סערה', 'A storm is coming tonight.', 8),
  ('weather', 'weather', '/ˈweðər/', 'noun', 'מזג אוויר', 'What''s the weather like today?', 9),
  ('weather', 'umbrella', '/ʌmˈbrelə/', 'noun', 'מטריה', 'Take an umbrella, it might rain.', 10),
  ('clothes', 'shirt', '/ʃɜːrt/', 'noun', 'חולצה', 'He is wearing a blue shirt.', 1),
  ('clothes', 'pants', '/pænts/', 'noun', 'מכנסיים', 'These pants are too long.', 2),
  ('clothes', 'dress', '/dres/', 'noun', 'שמלה', 'She bought a new dress.', 3),
  ('clothes', 'shoes', '/ʃuːz/', 'noun', 'נעליים', 'My shoes are very comfortable.', 4),
  ('clothes', 'jacket', '/ˈdʒækɪt/', 'noun', 'מעיל קל', 'Put on your jacket, it''s cold.', 5),
  ('clothes', 'hat', '/hæt/', 'noun', 'כובע', 'He wore a hat in the sun.', 6),
  ('clothes', 'socks', '/sɒks/', 'noun', 'גרביים', 'I need clean socks.', 7),
  ('clothes', 'skirt', '/skɜːrt/', 'noun', 'חצאית', 'She is wearing a red skirt.', 8),
  ('clothes', 'coat', '/kəʊt/', 'noun', 'מעיל', 'Wear a warm coat in winter.', 9),
  ('clothes', 'scarf', '/skɑːrf/', 'noun', 'צעיף', 'She wrapped a scarf around her neck.', 10),
  ('house-furniture', 'table', '/ˈteɪbəl/', 'noun', 'שולחן', 'We eat dinner at the table.', 1),
  ('house-furniture', 'chair', '/tʃeər/', 'noun', 'כיסא', 'Please sit on this chair.', 2),
  ('house-furniture', 'bed', '/bed/', 'noun', 'מיטה', 'The bed is very comfortable.', 3),
  ('house-furniture', 'sofa', '/ˈsəʊfə/', 'noun', 'ספה', 'We watch TV on the sofa.', 4),
  ('house-furniture', 'kitchen', '/ˈkɪtʃɪn/', 'noun', 'מטבח', 'Mom is cooking in the kitchen.', 5),
  ('house-furniture', 'bathroom', '/ˈbɑːθruːm/', 'noun', 'חדר אמבטיה', 'The bathroom is upstairs.', 6),
  ('house-furniture', 'window', '/ˈwɪndəʊ/', 'noun', 'חלון', 'Open the window, please.', 7),
  ('house-furniture', 'door', '/dɔːr/', 'noun', 'דלת', 'Please close the door.', 8),
  ('house-furniture', 'shelf', '/ʃelf/', 'noun', 'מדף', 'The books are on the shelf.', 9),
  ('house-furniture', 'lamp', '/læmp/', 'noun', 'מנורה', 'Turn on the lamp, it''s dark.', 10),
  ('body-parts', 'head', '/hed/', 'noun', 'ראש', 'My head hurts.', 1),
  ('body-parts', 'hand', '/hænd/', 'noun', 'יד', 'Wash your hands before eating.', 2),
  ('body-parts', 'leg', '/leɡ/', 'noun', 'רגל', 'He hurt his leg playing football.', 3),
  ('body-parts', 'eye', '/aɪ/', 'noun', 'עין', 'She has blue eyes.', 4),
  ('body-parts', 'ear', '/ɪər/', 'noun', 'אוזן', 'Speak louder, I can''t hear with this ear.', 5),
  ('body-parts', 'nose', '/nəʊz/', 'noun', 'אף', 'My nose is cold.', 6),
  ('body-parts', 'mouth', '/maʊθ/', 'noun', 'פה', 'Open your mouth, please.', 7),
  ('body-parts', 'hair', '/heər/', 'noun', 'שיער', 'She has long brown hair.', 8),
  ('body-parts', 'finger', '/ˈfɪŋɡər/', 'noun', 'אצבע', 'I cut my finger.', 9),
  ('body-parts', 'foot', '/fʊt/', 'noun', 'כף רגל', 'My foot hurts after the walk.', 10),
  ('time-days', 'Monday', '/ˈmʌndeɪ/', 'noun', 'יום שני', 'I have class on Monday.', 1),
  ('time-days', 'Friday', '/ˈfraɪdeɪ/', 'noun', 'יום שישי', 'We rest on Friday.', 2),
  ('time-days', 'today', '/təˈdeɪ/', 'adverb', 'היום', 'What are we doing today?', 3),
  ('time-days', 'tomorrow', '/təˈmɒrəʊ/', 'adverb', 'מחר', 'See you tomorrow.', 4),
  ('time-days', 'yesterday', '/ˈjestərdeɪ/', 'adverb', 'אתמול', 'I saw her yesterday.', 5),
  ('time-days', 'morning', '/ˈmɔːrnɪŋ/', 'noun', 'בוקר', 'Good morning!', 6),
  ('time-days', 'night', '/naɪt/', 'noun', 'לילה', 'Good night, sleep well.', 7),
  ('time-days', 'week', '/wiːk/', 'noun', 'שבוע', 'I''ll see you next week.', 8),
  ('time-days', 'hour', '/ˈaʊər/', 'noun', 'שעה', 'The meeting is one hour long.', 9),
  ('time-days', 'minute', '/ˈmɪnɪt/', 'noun', 'דקה', 'Wait a minute, please.', 10),
  ('transportation', 'car', '/kɑːr/', 'noun', 'מכונית', 'He drives a red car.', 1),
  ('transportation', 'bus', '/bʌs/', 'noun', 'אוטובוס', 'I take the bus to work.', 2),
  ('transportation', 'train', '/treɪn/', 'noun', 'רכבת', 'The train leaves at nine.', 3),
  ('transportation', 'airplane', '/ˈeərpleɪn/', 'noun', 'מטוס', 'We flew by airplane.', 4),
  ('transportation', 'bicycle', '/ˈbaɪsɪkəl/', 'noun', 'אופניים', 'She rides her bicycle to school.', 5),
  ('transportation', 'taxi', '/ˈtæksi/', 'noun', 'מונית', 'Let''s take a taxi home.', 6),
  ('transportation', 'ship', '/ʃɪp/', 'noun', 'ספינה', 'The ship sailed across the ocean.', 7),
  ('transportation', 'traffic', '/ˈtræfɪk/', 'noun', 'תנועה', 'There was a lot of traffic today.', 8),
  ('transportation', 'station', '/ˈsteɪʃən/', 'noun', 'תחנה', 'Meet me at the train station.', 9),
  ('transportation', 'ticket', '/ˈtɪkɪt/', 'noun', 'כרטיס', 'I bought a ticket for the show.', 10),
  ('jobs-professions', 'teacher', '/ˈtiːtʃər/', 'noun', 'מורה', 'My teacher is very kind.', 1),
  ('jobs-professions', 'doctor', '/ˈdɒktər/', 'noun', 'רופא/ה', 'The doctor examined the patient.', 2),
  ('jobs-professions', 'engineer', '/ˌendʒɪˈnɪər/', 'noun', 'מהנדס/ת', 'She works as an engineer.', 3),
  ('jobs-professions', 'nurse', '/nɜːrs/', 'noun', 'אח/ות', 'The nurse took my temperature.', 4),
  ('jobs-professions', 'police officer', '/pəˈliːs ˈɒfɪsər/', 'noun', 'שוטר/ת', 'The police officer helped us.', 5),
  ('jobs-professions', 'chef', '/ʃef/', 'noun', 'שף', 'The chef made a delicious meal.', 6),
  ('jobs-professions', 'lawyer', '/ˈlɔːjər/', 'noun', 'עורך/ת דין', 'He hired a good lawyer.', 7),
  ('jobs-professions', 'farmer', '/ˈfɑːrmər/', 'noun', 'חקלאי/ת', 'The farmer grows vegetables.', 8),
  ('jobs-professions', 'driver', '/ˈdraɪvər/', 'noun', 'נהג/ת', 'The bus driver was very friendly.', 9),
  ('jobs-professions', 'artist', '/ˈɑːrtɪst/', 'noun', 'אמן/ית', 'She is a talented artist.', 10),
  ('emotions-feelings', 'happy', '/ˈhæpi/', 'adjective', 'שמח', 'I am happy today.', 1),
  ('emotions-feelings', 'sad', '/sæd/', 'adjective', 'עצוב', 'She felt sad after the movie.', 2),
  ('emotions-feelings', 'angry', '/ˈæŋɡri/', 'adjective', 'כועס', 'He was angry about the delay.', 3),
  ('emotions-feelings', 'tired', '/ˈtaɪərd/', 'adjective', 'עייף', 'I''m tired after work.', 4),
  ('emotions-feelings', 'excited', '/ɪkˈsaɪtɪd/', 'adjective', 'נרגש', 'We are excited about the trip.', 5),
  ('emotions-feelings', 'scared', '/skeərd/', 'adjective', 'מפוחד', 'The child was scared of the dark.', 6),
  ('emotions-feelings', 'surprised', '/sərˈpraɪzd/', 'adjective', 'מופתע', 'I was surprised by the news.', 7),
  ('emotions-feelings', 'bored', '/bɔːrd/', 'adjective', 'משועמם', 'The kids were bored at home.', 8),
  ('emotions-feelings', 'nervous', '/ˈnɜːrvəs/', 'adjective', 'עצבני', 'She felt nervous before the exam.', 9),
  ('emotions-feelings', 'proud', '/praʊd/', 'adjective', 'גאה', 'We are proud of you.', 10),
  ('shopping', 'money', '/ˈmʌni/', 'noun', 'כסף', 'I don''t have much money.', 1),
  ('shopping', 'price', '/praɪs/', 'noun', 'מחיר', 'What is the price of this shirt?', 2),
  ('shopping', 'cheap', '/tʃiːp/', 'adjective', 'זול', 'This store is very cheap.', 3),
  ('shopping', 'expensive', '/ɪkˈspensɪv/', 'adjective', 'יקר', 'That car is too expensive.', 4),
  ('shopping', 'shop', '/ʃɒp/', 'noun', 'חנות', 'I bought this at a small shop.', 5),
  ('shopping', 'buy', '/baɪ/', 'verb', 'לקנות', 'I want to buy a new phone.', 6),
  ('shopping', 'sell', '/sel/', 'verb', 'למכור', 'They sell fresh vegetables here.', 7),
  ('shopping', 'discount', '/ˈdɪskaʊnt/', 'noun', 'הנחה', 'There''s a 20% discount today.', 8),
  ('shopping', 'receipt', '/rɪˈsiːt/', 'noun', 'קבלה', 'Keep your receipt, please.', 9),
  ('shopping', 'cash', '/kæʃ/', 'noun', 'מזומן', 'Do you accept cash?', 10),
  ('technology', 'computer', '/kəmˈpjuːtər/', 'noun', 'מחשב', 'I work on my computer every day.', 1),
  ('technology', 'phone', '/fəʊn/', 'noun', 'טלפון', 'My phone battery is low.', 2),
  ('technology', 'internet', '/ˈɪntərnet/', 'noun', 'אינטרנט', 'The internet is very slow today.', 3),
  ('technology', 'password', '/ˈpæswɜːrd/', 'noun', 'סיסמה', 'Don''t forget your password.', 4),
  ('technology', 'screen', '/skriːn/', 'noun', 'מסך', 'The screen is cracked.', 5),
  ('technology', 'app', '/æp/', 'noun', 'אפליקציה', 'I downloaded a new app.', 6),
  ('technology', 'email', '/ˈiːmeɪl/', 'noun', 'דוא"ל', 'Send me an email later.', 7),
  ('technology', 'battery', '/ˈbætəri/', 'noun', 'סוללה', 'The battery is fully charged.', 8),
  ('technology', 'download', '/ˌdaʊnˈləʊd/', 'verb', 'להוריד קובץ', 'I need to download the file.', 9),
  ('technology', 'wifi', '/ˈwaɪfaɪ/', 'noun', 'ווייפיי', 'Do you have wifi here?', 10)
) as v(topic_slug, headword, ipa, part_of_speech, translation_he, example_en, sort_order)
  on t.slug = v.topic_slug;

delete from public.exercises
where topic_id in (select id from public.topics where slug in ('weather', 'clothes', 'house-furniture', 'body-parts', 'time-days', 'transportation', 'jobs-professions', 'emotions-feelings', 'shopping', 'technology'));

insert into public.exercises (type, skill_area, topic_id, vocabulary_item_id, cefr_level, content, sort_order)
select 'mcq'::exercise_type, 'vocabulary'::skill_area, t.id, v.id, t.cefr_level, gen.content::jsonb, gen.sort_order
from (values
  ('weather', 'sun', '{"prompt":"מה המילה באנגלית עבור \"שמש\"?","options":["sun","snow","cold","storm"],"correctIndex":0}'::jsonb, 1),
  ('weather', 'rain', '{"prompt":"מה המילה באנגלית עבור \"גשם\"?","options":["cold","rain","cloud","wind"],"correctIndex":1}'::jsonb, 2),
  ('weather', 'cloud', '{"prompt":"מה המילה באנגלית עבור \"ענן\"?","options":["umbrella","weather","cloud","hot"],"correctIndex":2}'::jsonb, 3),
  ('weather', 'wind', '{"prompt":"מה המילה באנגלית עבור \"רוח\"?","options":["umbrella","storm","weather","wind"],"correctIndex":3}'::jsonb, 4),
  ('weather', 'snow', '{"prompt":"מה המילה באנגלית עבור \"שלג\"?","options":["snow","wind","sun","storm"],"correctIndex":0}'::jsonb, 5),
  ('weather', 'hot', '{"prompt":"מה המילה באנגלית עבור \"חם\"?","options":["wind","hot","sun","rain"],"correctIndex":1}'::jsonb, 6),
  ('weather', 'cold', '{"prompt":"מה המילה באנגלית עבור \"קר\"?","options":["weather","cloud","cold","storm"],"correctIndex":2}'::jsonb, 7),
  ('weather', 'storm', '{"prompt":"מה המילה באנגלית עבור \"סערה\"?","options":["rain","umbrella","cold","storm"],"correctIndex":3}'::jsonb, 8),
  ('weather', 'weather', '{"prompt":"מה המילה באנגלית עבור \"מזג אוויר\"?","options":["weather","hot","wind","umbrella"],"correctIndex":0}'::jsonb, 9),
  ('weather', 'umbrella', '{"prompt":"מה המילה באנגלית עבור \"מטריה\"?","options":["cloud","umbrella","hot","wind"],"correctIndex":1}'::jsonb, 10),
  ('clothes', 'shirt', '{"prompt":"מה המילה באנגלית עבור \"חולצה\"?","options":["shirt","jacket","socks","skirt"],"correctIndex":0}'::jsonb, 1),
  ('clothes', 'pants', '{"prompt":"מה המילה באנגלית עבור \"מכנסיים\"?","options":["socks","pants","dress","shoes"],"correctIndex":1}'::jsonb, 2),
  ('clothes', 'dress', '{"prompt":"מה המילה באנגלית עבור \"שמלה\"?","options":["scarf","coat","dress","hat"],"correctIndex":2}'::jsonb, 3),
  ('clothes', 'shoes', '{"prompt":"מה המילה באנגלית עבור \"נעליים\"?","options":["scarf","skirt","coat","shoes"],"correctIndex":3}'::jsonb, 4),
  ('clothes', 'jacket', '{"prompt":"מה המילה באנגלית עבור \"מעיל קל\"?","options":["jacket","shoes","shirt","skirt"],"correctIndex":0}'::jsonb, 5),
  ('clothes', 'hat', '{"prompt":"מה המילה באנגלית עבור \"כובע\"?","options":["shoes","hat","shirt","pants"],"correctIndex":1}'::jsonb, 6),
  ('clothes', 'socks', '{"prompt":"מה המילה באנגלית עבור \"גרביים\"?","options":["coat","dress","socks","skirt"],"correctIndex":2}'::jsonb, 7),
  ('clothes', 'skirt', '{"prompt":"מה המילה באנגלית עבור \"חצאית\"?","options":["pants","scarf","socks","skirt"],"correctIndex":3}'::jsonb, 8),
  ('clothes', 'coat', '{"prompt":"מה המילה באנגלית עבור \"מעיל\"?","options":["coat","hat","shoes","scarf"],"correctIndex":0}'::jsonb, 9),
  ('clothes', 'scarf', '{"prompt":"מה המילה באנגלית עבור \"צעיף\"?","options":["dress","scarf","hat","shoes"],"correctIndex":1}'::jsonb, 10),
  ('house-furniture', 'table', '{"prompt":"מה המילה באנגלית עבור \"שולחן\"?","options":["table","sofa","lamp","door"],"correctIndex":0}'::jsonb, 1),
  ('house-furniture', 'chair', '{"prompt":"מה המילה באנגלית עבור \"כיסא\"?","options":["window","chair","bathroom","door"],"correctIndex":1}'::jsonb, 2),
  ('house-furniture', 'bed', '{"prompt":"מה המילה באנגלית עבור \"מיטה\"?","options":["table","door","bed","sofa"],"correctIndex":2}'::jsonb, 3),
  ('house-furniture', 'sofa', '{"prompt":"מה המילה באנגלית עבור \"ספה\"?","options":["table","lamp","kitchen","sofa"],"correctIndex":3}'::jsonb, 4),
  ('house-furniture', 'kitchen', '{"prompt":"מה המילה באנגלית עבור \"מטבח\"?","options":["kitchen","bathroom","chair","table"],"correctIndex":0}'::jsonb, 5),
  ('house-furniture', 'bathroom', '{"prompt":"מה המילה באנגלית עבור \"חדר אמבטיה\"?","options":["sofa","bathroom","lamp","window"],"correctIndex":1}'::jsonb, 6),
  ('house-furniture', 'window', '{"prompt":"מה המילה באנגלית עבור \"חלון\"?","options":["table","lamp","window","chair"],"correctIndex":2}'::jsonb, 7),
  ('house-furniture', 'door', '{"prompt":"מה המילה באנגלית עבור \"דלת\"?","options":["kitchen","bed","bathroom","door"],"correctIndex":3}'::jsonb, 8),
  ('house-furniture', 'shelf', '{"prompt":"מה המילה באנגלית עבור \"מדף\"?","options":["shelf","chair","kitchen","sofa"],"correctIndex":0}'::jsonb, 9),
  ('house-furniture', 'lamp', '{"prompt":"מה המילה באנגלית עבור \"מנורה\"?","options":["shelf","lamp","table","chair"],"correctIndex":1}'::jsonb, 10),
  ('body-parts', 'head', '{"prompt":"מה המילה באנגלית עבור \"ראש\"?","options":["head","hair","finger","nose"],"correctIndex":0}'::jsonb, 1),
  ('body-parts', 'hand', '{"prompt":"מה המילה באנגלית עבור \"יד\"?","options":["ear","hand","mouth","leg"],"correctIndex":1}'::jsonb, 2),
  ('body-parts', 'leg', '{"prompt":"מה המילה באנגלית עבור \"רגל\"?","options":["ear","foot","leg","head"],"correctIndex":2}'::jsonb, 3),
  ('body-parts', 'eye', '{"prompt":"מה המילה באנגלית עבור \"עין\"?","options":["ear","hair","mouth","eye"],"correctIndex":3}'::jsonb, 4),
  ('body-parts', 'ear', '{"prompt":"מה המילה באנגלית עבור \"אוזן\"?","options":["ear","head","leg","nose"],"correctIndex":0}'::jsonb, 5),
  ('body-parts', 'nose', '{"prompt":"מה המילה באנגלית עבור \"אף\"?","options":["ear","nose","hand","foot"],"correctIndex":1}'::jsonb, 6),
  ('body-parts', 'mouth', '{"prompt":"מה המילה באנגלית עבור \"פה\"?","options":["ear","eye","mouth","foot"],"correctIndex":2}'::jsonb, 7),
  ('body-parts', 'hair', '{"prompt":"מה המילה באנגלית עבור \"שיער\"?","options":["finger","foot","hand","hair"],"correctIndex":3}'::jsonb, 8),
  ('body-parts', 'finger', '{"prompt":"מה המילה באנגלית עבור \"אצבע\"?","options":["finger","leg","ear","eye"],"correctIndex":0}'::jsonb, 9),
  ('body-parts', 'foot', '{"prompt":"מה המילה באנגלית עבור \"כף רגל\"?","options":["head","foot","finger","eye"],"correctIndex":1}'::jsonb, 10),
  ('time-days', 'Monday', '{"prompt":"מה המילה באנגלית עבור \"יום שני\"?","options":["Monday","yesterday","minute","Friday"],"correctIndex":0}'::jsonb, 1),
  ('time-days', 'Friday', '{"prompt":"מה המילה באנגלית עבור \"יום שישי\"?","options":["yesterday","Friday","night","tomorrow"],"correctIndex":1}'::jsonb, 2),
  ('time-days', 'today', '{"prompt":"מה המילה באנגלית עבור \"היום\"?","options":["Monday","yesterday","today","minute"],"correctIndex":2}'::jsonb, 3),
  ('time-days', 'tomorrow', '{"prompt":"מה המילה באנגלית עבור \"מחר\"?","options":["hour","morning","Monday","tomorrow"],"correctIndex":3}'::jsonb, 4),
  ('time-days', 'yesterday', '{"prompt":"מה המילה באנגלית עבור \"אתמול\"?","options":["yesterday","Monday","tomorrow","today"],"correctIndex":0}'::jsonb, 5),
  ('time-days', 'morning', '{"prompt":"מה המילה באנגלית עבור \"בוקר\"?","options":["Monday","morning","yesterday","night"],"correctIndex":1}'::jsonb, 6),
  ('time-days', 'night', '{"prompt":"מה המילה באנגלית עבור \"לילה\"?","options":["morning","hour","night","tomorrow"],"correctIndex":2}'::jsonb, 7),
  ('time-days', 'week', '{"prompt":"מה המילה באנגלית עבור \"שבוע\"?","options":["night","morning","Monday","week"],"correctIndex":3}'::jsonb, 8),
  ('time-days', 'hour', '{"prompt":"מה המילה באנגלית עבור \"שעה\"?","options":["hour","tomorrow","morning","today"],"correctIndex":0}'::jsonb, 9),
  ('time-days', 'minute', '{"prompt":"מה המילה באנגלית עבור \"דקה\"?","options":["hour","minute","tomorrow","night"],"correctIndex":1}'::jsonb, 10),
  ('transportation', 'car', '{"prompt":"מה המילה באנגלית עבור \"מכונית\"?","options":["car","ship","train","airplane"],"correctIndex":0}'::jsonb, 1),
  ('transportation', 'bus', '{"prompt":"מה המילה באנגלית עבור \"אוטובוס\"?","options":["ticket","bus","station","taxi"],"correctIndex":1}'::jsonb, 2),
  ('transportation', 'train', '{"prompt":"מה המילה באנגלית עבור \"רכבת\"?","options":["ticket","traffic","train","station"],"correctIndex":2}'::jsonb, 3),
  ('transportation', 'airplane', '{"prompt":"מה המילה באנגלית עבור \"מטוס\"?","options":["bicycle","car","traffic","airplane"],"correctIndex":3}'::jsonb, 4),
  ('transportation', 'bicycle', '{"prompt":"מה המילה באנגלית עבור \"אופניים\"?","options":["bicycle","airplane","car","bus"],"correctIndex":0}'::jsonb, 5),
  ('transportation', 'taxi', '{"prompt":"מה המילה באנגלית עבור \"מונית\"?","options":["station","taxi","train","traffic"],"correctIndex":1}'::jsonb, 6),
  ('transportation', 'ship', '{"prompt":"מה המילה באנגלית עבור \"ספינה\"?","options":["bus","ticket","ship","traffic"],"correctIndex":2}'::jsonb, 7),
  ('transportation', 'traffic', '{"prompt":"מה המילה באנגלית עבור \"תנועה\"?","options":["taxi","airplane","ticket","traffic"],"correctIndex":3}'::jsonb, 8),
  ('transportation', 'station', '{"prompt":"מה המילה באנגלית עבור \"תחנה\"?","options":["station","train","taxi","airplane"],"correctIndex":0}'::jsonb, 9),
  ('transportation', 'ticket', '{"prompt":"מה המילה באנגלית עבור \"כרטיס\"?","options":["ship","ticket","station","traffic"],"correctIndex":1}'::jsonb, 10),
  ('jobs-professions', 'teacher', '{"prompt":"מה המילה באנגלית עבור \"מורה\"?","options":["teacher","police officer","lawyer","nurse"],"correctIndex":0}'::jsonb, 1),
  ('jobs-professions', 'doctor', '{"prompt":"מה המילה באנגלית עבור \"רופא/ה\"?","options":["teacher","doctor","police officer","artist"],"correctIndex":1}'::jsonb, 2),
  ('jobs-professions', 'engineer', '{"prompt":"מה המילה באנגלית עבור \"מהנדס/ת\"?","options":["driver","chef","engineer","teacher"],"correctIndex":2}'::jsonb, 3),
  ('jobs-professions', 'nurse', '{"prompt":"מה המילה באנגלית עבור \"אח/ות\"?","options":["teacher","police officer","engineer","nurse"],"correctIndex":3}'::jsonb, 4),
  ('jobs-professions', 'police officer', '{"prompt":"מה המילה באנגלית עבור \"שוטר/ת\"?","options":["police officer","teacher","chef","lawyer"],"correctIndex":0}'::jsonb, 5),
  ('jobs-professions', 'chef', '{"prompt":"מה המילה באנגלית עבור \"שף\"?","options":["lawyer","chef","driver","nurse"],"correctIndex":1}'::jsonb, 6),
  ('jobs-professions', 'lawyer', '{"prompt":"מה המילה באנגלית עבור \"עורך/ת דין\"?","options":["farmer","chef","lawyer","teacher"],"correctIndex":2}'::jsonb, 7),
  ('jobs-professions', 'farmer', '{"prompt":"מה המילה באנגלית עבור \"חקלאי/ת\"?","options":["nurse","chef","engineer","farmer"],"correctIndex":3}'::jsonb, 8),
  ('jobs-professions', 'driver', '{"prompt":"מה המילה באנגלית עבור \"נהג/ת\"?","options":["driver","artist","nurse","lawyer"],"correctIndex":0}'::jsonb, 9),
  ('jobs-professions', 'artist', '{"prompt":"מה המילה באנגלית עבור \"אמן/ית\"?","options":["farmer","artist","doctor","driver"],"correctIndex":1}'::jsonb, 10),
  ('emotions-feelings', 'happy', '{"prompt":"מה המילה באנגלית עבור \"שמח\"?","options":["happy","excited","surprised","angry"],"correctIndex":0}'::jsonb, 1),
  ('emotions-feelings', 'sad', '{"prompt":"מה המילה באנגלית עבור \"עצוב\"?","options":["excited","sad","proud","happy"],"correctIndex":1}'::jsonb, 2),
  ('emotions-feelings', 'angry', '{"prompt":"מה המילה באנגלית עבור \"כועס\"?","options":["excited","bored","angry","surprised"],"correctIndex":2}'::jsonb, 3),
  ('emotions-feelings', 'tired', '{"prompt":"מה המילה באנגלית עבור \"עייף\"?","options":["happy","angry","scared","tired"],"correctIndex":3}'::jsonb, 4),
  ('emotions-feelings', 'excited', '{"prompt":"מה המילה באנגלית עבור \"נרגש\"?","options":["excited","scared","sad","proud"],"correctIndex":0}'::jsonb, 5),
  ('emotions-feelings', 'scared', '{"prompt":"מה המילה באנגלית עבור \"מפוחד\"?","options":["excited","scared","tired","proud"],"correctIndex":1}'::jsonb, 6),
  ('emotions-feelings', 'surprised', '{"prompt":"מה המילה באנגלית עבור \"מופתע\"?","options":["nervous","proud","surprised","sad"],"correctIndex":2}'::jsonb, 7),
  ('emotions-feelings', 'bored', '{"prompt":"מה המילה באנגלית עבור \"משועמם\"?","options":["angry","excited","tired","bored"],"correctIndex":3}'::jsonb, 8),
  ('emotions-feelings', 'nervous', '{"prompt":"מה המילה באנגלית עבור \"עצבני\"?","options":["nervous","happy","proud","tired"],"correctIndex":0}'::jsonb, 9),
  ('emotions-feelings', 'proud', '{"prompt":"מה המילה באנגלית עבור \"גאה\"?","options":["nervous","proud","surprised","bored"],"correctIndex":1}'::jsonb, 10),
  ('shopping', 'money', '{"prompt":"מה המילה באנגלית עבור \"כסף\"?","options":["money","price","receipt","cash"],"correctIndex":0}'::jsonb, 1),
  ('shopping', 'price', '{"prompt":"מה המילה באנגלית עבור \"מחיר\"?","options":["expensive","price","cash","discount"],"correctIndex":1}'::jsonb, 2),
  ('shopping', 'cheap', '{"prompt":"מה המילה באנגלית עבור \"זול\"?","options":["sell","buy","cheap","discount"],"correctIndex":2}'::jsonb, 3),
  ('shopping', 'expensive', '{"prompt":"מה המילה באנגלית עבור \"יקר\"?","options":["money","discount","cheap","expensive"],"correctIndex":3}'::jsonb, 4),
  ('shopping', 'shop', '{"prompt":"מה המילה באנגלית עבור \"חנות\"?","options":["shop","money","cash","expensive"],"correctIndex":0}'::jsonb, 5),
  ('shopping', 'buy', '{"prompt":"מה המילה באנגלית עבור \"לקנות\"?","options":["shop","buy","price","money"],"correctIndex":1}'::jsonb, 6),
  ('shopping', 'sell', '{"prompt":"מה המילה באנגלית עבור \"למכור\"?","options":["expensive","cash","sell","buy"],"correctIndex":2}'::jsonb, 7),
  ('shopping', 'discount', '{"prompt":"מה המילה באנגלית עבור \"הנחה\"?","options":["money","cash","price","discount"],"correctIndex":3}'::jsonb, 8),
  ('shopping', 'receipt', '{"prompt":"מה המילה באנגלית עבור \"קבלה\"?","options":["receipt","shop","cheap","buy"],"correctIndex":0}'::jsonb, 9),
  ('shopping', 'cash', '{"prompt":"מה המילה באנגלית עבור \"מזומן\"?","options":["price","cash","shop","expensive"],"correctIndex":1}'::jsonb, 10),
  ('technology', 'computer', '{"prompt":"מה המילה באנגלית עבור \"מחשב\"?","options":["computer","battery","download","app"],"correctIndex":0}'::jsonb, 1),
  ('technology', 'phone', '{"prompt":"מה המילה באנגלית עבור \"טלפון\"?","options":["screen","phone","email","internet"],"correctIndex":1}'::jsonb, 2),
  ('technology', 'internet', '{"prompt":"מה המילה באנגלית עבור \"אינטרנט\"?","options":["screen","wifi","internet","computer"],"correctIndex":2}'::jsonb, 3),
  ('technology', 'password', '{"prompt":"מה המילה באנגלית עבור \"סיסמה\"?","options":["screen","battery","email","password"],"correctIndex":3}'::jsonb, 4),
  ('technology', 'screen', '{"prompt":"מה המילה באנגלית עבור \"מסך\"?","options":["screen","computer","internet","app"],"correctIndex":0}'::jsonb, 5),
  ('technology', 'app', '{"prompt":"מה המילה באנגלית עבור \"אפליקציה\"?","options":["screen","app","phone","wifi"],"correctIndex":1}'::jsonb, 6),
  ('technology', 'email', '{"prompt":"מה המילה באנגלית עבור \"דוא\"ל\"?","options":["screen","password","email","wifi"],"correctIndex":2}'::jsonb, 7),
  ('technology', 'battery', '{"prompt":"מה המילה באנגלית עבור \"סוללה\"?","options":["download","wifi","phone","battery"],"correctIndex":3}'::jsonb, 8),
  ('technology', 'download', '{"prompt":"מה המילה באנגלית עבור \"להוריד קובץ\"?","options":["download","internet","screen","password"],"correctIndex":0}'::jsonb, 9),
  ('technology', 'wifi', '{"prompt":"מה המילה באנגלית עבור \"ווייפיי\"?","options":["computer","wifi","download","password"],"correctIndex":1}'::jsonb, 10)
) as gen(topic_slug, headword, content, sort_order)
join public.topics t on t.slug = gen.topic_slug
join public.vocabulary_items v on v.topic_id = t.id and v.headword = gen.headword;

insert into public.exercises (type, skill_area, topic_id, cefr_level, content, sort_order)
select 'match'::exercise_type, 'vocabulary'::skill_area, t.id, t.cefr_level, gen.content, 100
from (values
  ('weather', '{"pairs":[{"left":"rain","right":"גשם"},{"left":"wind","right":"רוח"},{"left":"sun","right":"שמש"},{"left":"umbrella","right":"מטריה"}]}'::jsonb),
  ('clothes', '{"pairs":[{"left":"pants","right":"מכנסיים"},{"left":"shoes","right":"נעליים"},{"left":"shirt","right":"חולצה"},{"left":"scarf","right":"צעיף"}]}'::jsonb),
  ('house-furniture', '{"pairs":[{"left":"table","right":"שולחן"},{"left":"chair","right":"כיסא"},{"left":"sofa","right":"ספה"},{"left":"shelf","right":"מדף"}]}'::jsonb),
  ('body-parts', '{"pairs":[{"left":"nose","right":"אף"},{"left":"finger","right":"אצבע"},{"left":"leg","right":"רגל"},{"left":"head","right":"ראש"}]}'::jsonb),
  ('time-days', '{"pairs":[{"left":"Monday","right":"יום שני"},{"left":"morning","right":"בוקר"},{"left":"week","right":"שבוע"},{"left":"Friday","right":"יום שישי"}]}'::jsonb),
  ('transportation', '{"pairs":[{"left":"bus","right":"אוטובוס"},{"left":"taxi","right":"מונית"},{"left":"airplane","right":"מטוס"},{"left":"ticket","right":"כרטיס"}]}'::jsonb),
  ('jobs-professions', '{"pairs":[{"left":"driver","right":"נהג/ת"},{"left":"engineer","right":"מהנדס/ת"},{"left":"farmer","right":"חקלאי/ת"},{"left":"police officer","right":"שוטר/ת"}]}'::jsonb),
  ('emotions-feelings', '{"pairs":[{"left":"bored","right":"משועמם"},{"left":"nervous","right":"עצבני"},{"left":"tired","right":"עייף"},{"left":"surprised","right":"מופתע"}]}'::jsonb),
  ('shopping', '{"pairs":[{"left":"sell","right":"למכור"},{"left":"discount","right":"הנחה"},{"left":"shop","right":"חנות"},{"left":"receipt","right":"קבלה"}]}'::jsonb),
  ('technology', '{"pairs":[{"left":"app","right":"אפליקציה"},{"left":"download","right":"להוריד קובץ"},{"left":"internet","right":"אינטרנט"},{"left":"computer","right":"מחשב"}]}'::jsonb)
) as gen(topic_slug, content)
join public.topics t on t.slug = gen.topic_slug;
