-- English definitions for the 10 everyday-life topics from seed 010
-- (weather, clothes, house-furniture, body-parts, time-days,
-- transportation, jobs-professions, emotions-feelings, shopping,
-- technology) — 100 words. Continues the "identify word by definition"
-- game's coverage started in seed 018.
-- Run this AFTER migration 015_vocabulary_definitions.sql.
-- Safe to re-run: plain UPDATE, idempotent.

update public.vocabulary_items vi
set definition_en = v.definition_en
from (values
  ('weather', 'sun', 'the star that gives Earth light and heat during the day'),
  ('weather', 'rain', 'water that falls from clouds in the sky'),
  ('weather', 'cloud', 'a white or gray shape in the sky made of tiny drops of water'),
  ('weather', 'wind', 'air that moves, sometimes strongly'),
  ('weather', 'snow', 'soft white ice that falls from the sky in cold weather'),
  ('weather', 'hot', 'having a high temperature'),
  ('weather', 'cold', 'having a low temperature'),
  ('weather', 'storm', 'very bad weather with strong wind and often rain'),
  ('weather', 'weather', 'the outdoor conditions at a certain time, such as sun, rain, or wind'),
  ('weather', 'umbrella', 'an object you hold over your head to stay dry in the rain'),
  ('clothes', 'shirt', 'a piece of clothing worn on the upper body'),
  ('clothes', 'pants', 'a piece of clothing that covers the legs, worn from the waist down'),
  ('clothes', 'dress', 'a piece of clothing for women or girls that covers the body and legs'),
  ('clothes', 'shoes', 'items worn on the feet for walking'),
  ('clothes', 'jacket', 'a short coat, often worn over other clothes'),
  ('clothes', 'hat', 'an item worn on the head'),
  ('clothes', 'socks', 'soft items worn on the feet, under shoes'),
  ('clothes', 'skirt', 'a piece of clothing for women or girls that hangs from the waist'),
  ('clothes', 'coat', 'a piece of clothing worn over other clothes to stay warm outside'),
  ('clothes', 'scarf', 'a piece of cloth worn around the neck for warmth or style'),
  ('house-furniture', 'table', 'a piece of furniture with a flat top, used for eating or working'),
  ('house-furniture', 'chair', 'a piece of furniture for one person to sit on'),
  ('house-furniture', 'bed', 'a piece of furniture used for sleeping'),
  ('house-furniture', 'sofa', 'a long, soft piece of furniture for sitting, usually in a living room'),
  ('house-furniture', 'kitchen', 'the room in a house where food is cooked'),
  ('house-furniture', 'bathroom', 'the room in a house with a toilet and shower or bath'),
  ('house-furniture', 'window', 'an opening in a wall, usually with glass, that lets in light'),
  ('house-furniture', 'door', 'the part of a room or building that opens so people can go in or out'),
  ('house-furniture', 'shelf', 'a flat surface on a wall or in furniture used to hold objects'),
  ('house-furniture', 'lamp', 'a device that gives light, usually placed on a table or the floor'),
  ('body-parts', 'head', 'the top part of the body, where the brain and face are'),
  ('body-parts', 'hand', 'the part of the body at the end of the arm, used to hold things'),
  ('body-parts', 'leg', 'one of the two long parts of the body used for walking'),
  ('body-parts', 'eye', 'the part of the body used for seeing'),
  ('body-parts', 'ear', 'the part of the body used for hearing'),
  ('body-parts', 'nose', 'the part of the face used for breathing and smelling'),
  ('body-parts', 'mouth', 'the part of the face used for eating and speaking'),
  ('body-parts', 'hair', 'the thin strands that grow on the head and body'),
  ('body-parts', 'finger', 'one of the five thin parts at the end of the hand'),
  ('body-parts', 'foot', 'the part of the body at the end of the leg, used for standing and walking'),
  ('time-days', 'Monday', 'the first day of the work week, after Sunday'),
  ('time-days', 'Friday', 'the last work day of the week, before the weekend'),
  ('time-days', 'today', 'this present day'),
  ('time-days', 'tomorrow', 'the day after today'),
  ('time-days', 'yesterday', 'the day before today'),
  ('time-days', 'morning', 'the early part of the day, before noon'),
  ('time-days', 'night', 'the part of the day when it is dark outside'),
  ('time-days', 'week', 'a period of seven days'),
  ('time-days', 'hour', 'a period of sixty minutes'),
  ('time-days', 'minute', 'a period of sixty seconds'),
  ('transportation', 'car', 'a vehicle with four wheels used to travel on roads'),
  ('transportation', 'bus', 'a large vehicle that carries many passengers'),
  ('transportation', 'train', 'a vehicle that travels on rails, often used for long trips'),
  ('transportation', 'airplane', 'a vehicle that flies through the air, used for travel'),
  ('transportation', 'bicycle', 'a vehicle with two wheels that you ride by pedaling'),
  ('transportation', 'taxi', 'a car that you pay to drive you somewhere'),
  ('transportation', 'ship', 'a large boat used to travel across water'),
  ('transportation', 'traffic', 'the cars and other vehicles moving on a road'),
  ('transportation', 'station', 'a place where trains or buses stop for passengers'),
  ('transportation', 'ticket', 'a piece of paper or pass that allows you to travel or enter somewhere'),
  ('jobs-professions', 'teacher', 'a person whose job is to help students learn'),
  ('jobs-professions', 'doctor', 'a person whose job is to treat sick or injured people'),
  ('jobs-professions', 'engineer', 'a person who designs or builds machines, structures, or systems'),
  ('jobs-professions', 'nurse', 'a person whose job is to care for sick people, often in a hospital'),
  ('jobs-professions', 'police officer', 'a person whose job is to protect people and enforce the law'),
  ('jobs-professions', 'chef', 'a skilled cook, often in charge of a kitchen'),
  ('jobs-professions', 'lawyer', 'a person whose job is to give legal advice or represent people in court'),
  ('jobs-professions', 'farmer', 'a person who grows crops or raises animals for a living'),
  ('jobs-professions', 'driver', 'a person who operates a vehicle'),
  ('jobs-professions', 'artist', 'a person who creates paintings, drawings, or other art'),
  ('emotions-feelings', 'happy', 'feeling pleased or glad'),
  ('emotions-feelings', 'sad', 'feeling unhappy'),
  ('emotions-feelings', 'angry', 'feeling strong displeasure toward someone or something'),
  ('emotions-feelings', 'tired', 'needing rest or sleep'),
  ('emotions-feelings', 'excited', 'feeling very happy and eager about something'),
  ('emotions-feelings', 'scared', 'feeling afraid'),
  ('emotions-feelings', 'surprised', 'feeling shocked by something unexpected'),
  ('emotions-feelings', 'bored', 'feeling uninterested because there is nothing exciting to do'),
  ('emotions-feelings', 'nervous', 'feeling worried or uneasy about something'),
  ('emotions-feelings', 'proud', 'feeling pleased about something you or someone else achieved'),
  ('shopping', 'money', 'coins and paper notes used to pay for things'),
  ('shopping', 'price', 'the amount of money something costs'),
  ('shopping', 'cheap', 'not costing much money'),
  ('shopping', 'expensive', 'costing a lot of money'),
  ('shopping', 'shop', 'a place where you can buy things'),
  ('shopping', 'buy', 'to get something by paying money for it'),
  ('shopping', 'sell', 'to give something to someone in exchange for money'),
  ('shopping', 'discount', 'an amount taken off the usual price of something'),
  ('shopping', 'receipt', 'a piece of paper that proves you paid for something'),
  ('shopping', 'cash', 'money in the form of coins and paper notes, not a card'),
  ('technology', 'computer', 'an electronic device used to store and process information'),
  ('technology', 'phone', 'a device used to talk to people who are far away'),
  ('technology', 'internet', 'a global system that connects computers and lets people share information'),
  ('technology', 'password', 'a secret word or phrase used to prove who you are online'),
  ('technology', 'screen', 'the flat surface on a device where images and text appear'),
  ('technology', 'app', 'a small computer program, usually used on a phone'),
  ('technology', 'email', 'a message sent electronically over the internet'),
  ('technology', 'battery', 'a device that stores electrical power for a machine to use'),
  ('technology', 'download', 'to copy a file from the internet onto your device'),
  ('technology', 'wifi', 'a wireless connection that lets devices use the internet')
) as v(topic_slug, headword, definition_en)
join public.topics t on t.slug = v.topic_slug
where vi.topic_id = t.id and vi.headword = v.headword;
