-- English definitions for the B2-C2 topics from seed 014 (60 words:
-- environment-climate, health-wellness, business-negotiation,
-- academic-writing, abstract-concepts, formal-register) and the A1/C2
-- topics from seed 016 (80 words: daily-routines, hobbies,
-- places-in-town, school, rhetoric-persuasion, psychology-cognition,
-- scientific-inquiry, literary-analysis) — 140 words. Completes
-- definitions coverage across every vocabulary topic seeded so far.
-- Run this AFTER migration 015_vocabulary_definitions.sql.
-- Safe to re-run: plain UPDATE, idempotent.

update public.vocabulary_items vi
set definition_en = v.definition_en
from (values
  ('environment-climate', 'climate', 'the usual weather conditions of a place over a long period of time'),
  ('environment-climate', 'pollution', 'harmful substances that damage the air, water, or land'),
  ('environment-climate', 'recycle', 'to process used materials so they can be used again'),
  ('environment-climate', 'renewable', 'able to be replaced naturally, such as an energy source that does not run out'),
  ('environment-climate', 'sustainability', 'the ability to continue something without harming the environment or running out of resources'),
  ('environment-climate', 'greenhouse', 'related to gases that trap heat in the Earth''s atmosphere'),
  ('environment-climate', 'drought', 'a long period with little or no rain'),
  ('environment-climate', 'wildlife', 'animals and plants living in their natural environment'),
  ('environment-climate', 'emission', 'a gas or substance released into the air, often by vehicles or factories'),
  ('environment-climate', 'conservation', 'the protection of nature, wildlife, or resources'),
  ('health-wellness', 'symptom', 'a sign in the body that shows a person may be ill'),
  ('health-wellness', 'diagnosis', 'a doctor''s decision about what illness a person has'),
  ('health-wellness', 'treatment', 'medical care given to help a person get better'),
  ('health-wellness', 'immune', 'able to resist a disease or infection'),
  ('health-wellness', 'nutrition', 'the food a person eats and how it affects their health'),
  ('health-wellness', 'exercise', 'physical activity done to stay healthy and fit'),
  ('health-wellness', 'stress', 'a feeling of worry or pressure caused by difficult situations'),
  ('health-wellness', 'recovery', 'the process of getting better after being sick or injured'),
  ('health-wellness', 'therapy', 'treatment for a physical or emotional problem, often through talking or exercises'),
  ('health-wellness', 'wellbeing', 'a person''s overall state of being healthy, happy, and comfortable'),
  ('business-negotiation', 'negotiate', 'to discuss something with someone to reach an agreement'),
  ('business-negotiation', 'stakeholder', 'a person or group with an interest in a business or project'),
  ('business-negotiation', 'revenue', 'the money a business earns from selling goods or services'),
  ('business-negotiation', 'merger', 'the joining of two companies into one'),
  ('business-negotiation', 'strategy', 'a plan to achieve a goal'),
  ('business-negotiation', 'deadline', 'the latest time or date by which something must be finished'),
  ('business-negotiation', 'budget', 'a plan for how much money will be spent or earned'),
  ('business-negotiation', 'proposal', 'a plan or suggestion offered for consideration'),
  ('business-negotiation', 'compromise', 'an agreement reached when each side gives up something it wanted'),
  ('business-negotiation', 'leverage', 'power or influence used to achieve a desired result'),
  ('academic-writing', 'hypothesis', 'an idea that has not yet been proven, used as a starting point for research'),
  ('academic-writing', 'analyze', 'to study something carefully to understand it'),
  ('academic-writing', 'evidence', 'facts or information that show whether something is true'),
  ('academic-writing', 'methodology', 'the set of methods used in a piece of research'),
  ('academic-writing', 'conclude', 'to decide something after considering all the facts'),
  ('academic-writing', 'cite', 'to mention a source of information in your own writing'),
  ('academic-writing', 'critique', 'a detailed evaluation of someone''s work'),
  ('academic-writing', 'thesis', 'a long piece of writing based on research, often for a degree'),
  ('academic-writing', 'peer-review', 'a process where experts check someone''s work before it is published'),
  ('academic-writing', 'correlation', 'a relationship between two things where one changes when the other does'),
  ('abstract-concepts', 'ambiguous', 'having more than one possible meaning, unclear'),
  ('abstract-concepts', 'paradox', 'a situation that seems to contradict itself but may still be true'),
  ('abstract-concepts', 'nuance', 'a small, subtle difference in meaning or feeling'),
  ('abstract-concepts', 'subjective', 'based on personal opinion rather than fact'),
  ('abstract-concepts', 'inherent', 'existing as a natural or basic part of something'),
  ('abstract-concepts', 'implicit', 'understood without being directly stated'),
  ('abstract-concepts', 'conceptual', 'relating to ideas rather than physical things'),
  ('abstract-concepts', 'ambivalent', 'having mixed or uncertain feelings about something'),
  ('abstract-concepts', 'discern', 'to notice or recognize something, often something not obvious'),
  ('abstract-concepts', 'ubiquitous', 'found or existing everywhere'),
  ('formal-register', 'albeit', 'although, even though'),
  ('formal-register', 'notwithstanding', 'despite something, without being prevented by it'),
  ('formal-register', 'henceforth', 'from this point forward'),
  ('formal-register', 'aforementioned', 'mentioned earlier in the same piece of writing'),
  ('formal-register', 'pertinent', 'relevant or related to the subject being discussed'),
  ('formal-register', 'discretion', 'the freedom to decide what should be done in a situation'),
  ('formal-register', 'candid', 'honest and direct, without hiding anything'),
  ('formal-register', 'tacit', 'understood without being said directly'),
  ('formal-register', 'mitigate', 'to make something less severe or harmful'),
  ('formal-register', 'reconcile', 'to make two different ideas or situations agree with each other'),
  ('daily-routines', 'wake up', 'to stop sleeping'),
  ('daily-routines', 'get up', 'to rise from bed or a seated position'),
  ('daily-routines', 'brush teeth', 'to clean your teeth with a toothbrush'),
  ('daily-routines', 'take a shower', 'to wash your body by standing under running water'),
  ('daily-routines', 'get dressed', 'to put on your clothes'),
  ('daily-routines', 'have breakfast', 'to eat the first meal of the day'),
  ('daily-routines', 'go to work', 'to travel to the place where you have a job'),
  ('daily-routines', 'come home', 'to return to the place where you live'),
  ('daily-routines', 'go to bed', 'to lie down to sleep'),
  ('daily-routines', 'sleep', 'to rest with your eyes closed and your mind unaware'),
  ('hobbies', 'reading', 'looking at and understanding written words'),
  ('hobbies', 'swimming', 'moving through water using your arms and legs'),
  ('hobbies', 'drawing', 'making pictures with a pen or pencil'),
  ('hobbies', 'cooking', 'preparing food by heating it'),
  ('hobbies', 'dancing', 'moving your body to music'),
  ('hobbies', 'singing', 'making music with your voice'),
  ('hobbies', 'painting', 'making pictures using paint'),
  ('hobbies', 'running', 'moving quickly on foot, faster than walking'),
  ('hobbies', 'fishing', 'trying to catch fish, usually with a rod or net'),
  ('hobbies', 'gardening', 'growing and taking care of plants outdoors'),
  ('places-in-town', 'bank', 'a place where people keep and manage their money'),
  ('places-in-town', 'hospital', 'a place where sick or injured people receive medical care'),
  ('places-in-town', 'park', 'an open area with grass and trees where people relax outdoors'),
  ('places-in-town', 'library', 'a place where people can borrow or read books'),
  ('places-in-town', 'restaurant', 'a place where people pay to eat meals'),
  ('places-in-town', 'supermarket', 'a large shop that sells food and other everyday items'),
  ('places-in-town', 'school', 'a place where children go to learn'),
  ('places-in-town', 'hotel', 'a place where people pay to stay for a short time when traveling'),
  ('places-in-town', 'museum', 'a building where interesting or historical objects are displayed'),
  ('places-in-town', 'pharmacy', 'a shop where you can buy medicine'),
  ('school', 'teacher', 'a person whose job is to help students learn'),
  ('school', 'student', 'a person who is studying at a school or other place of learning'),
  ('school', 'classroom', 'a room where lessons are taught'),
  ('school', 'homework', 'school work that students do at home'),
  ('school', 'pencil', 'a thin tool used for writing or drawing, usually with a wooden case'),
  ('school', 'book', 'a set of printed pages joined together, containing writing or pictures'),
  ('school', 'notebook', 'a book of blank pages used for writing notes'),
  ('school', 'desk', 'a piece of furniture with a flat top used for writing or studying'),
  ('school', 'blackboard', 'a dark board that teachers write on with chalk'),
  ('school', 'exam', 'a formal test of a person''s knowledge or skill'),
  ('rhetoric-persuasion', 'rhetoric', 'the skill of using language effectively to persuade or influence'),
  ('rhetoric-persuasion', 'persuade', 'to convince someone to do or believe something'),
  ('rhetoric-persuasion', 'hyperbole', 'exaggerated language not meant to be taken literally'),
  ('rhetoric-persuasion', 'irony', 'a situation or statement where the result is the opposite of what was expected'),
  ('rhetoric-persuasion', 'euphemism', 'a mild or indirect word used instead of a harsher or blunter one'),
  ('rhetoric-persuasion', 'connotation', 'a feeling or idea suggested by a word beyond its literal meaning'),
  ('rhetoric-persuasion', 'discourse', 'communication, especially formal discussion, in speech or writing'),
  ('rhetoric-persuasion', 'eloquent', 'able to speak or write fluently and persuasively'),
  ('rhetoric-persuasion', 'satire', 'the use of humor or exaggeration to criticize something'),
  ('rhetoric-persuasion', 'allegory', 'a story in which the characters and events represent a deeper meaning'),
  ('psychology-cognition', 'cognition', 'the mental process of gaining knowledge and understanding'),
  ('psychology-cognition', 'perception', 'the way someone notices or understands something through the senses'),
  ('psychology-cognition', 'introspection', 'the examination of one''s own thoughts and feelings'),
  ('psychology-cognition', 'bias', 'an unfair preference for or against something'),
  ('psychology-cognition', 'empathy', 'the ability to understand and share the feelings of another person'),
  ('psychology-cognition', 'resilience', 'the ability to recover quickly from difficulties'),
  ('psychology-cognition', 'subconscious', 'the part of the mind that affects behavior without a person being aware of it'),
  ('psychology-cognition', 'temperament', 'a person''s natural way of thinking, feeling, and behaving'),
  ('psychology-cognition', 'intuition', 'the ability to understand something instinctively, without needing to think it through'),
  ('psychology-cognition', 'disposition', 'a person''s usual mood or way of behaving'),
  ('scientific-inquiry', 'empirical', 'based on observation or experiment rather than theory alone'),
  ('scientific-inquiry', 'phenomenon', 'a fact or event that can be observed, especially one that is unusual'),
  ('scientific-inquiry', 'paradigm', 'a typical example or pattern of how something works'),
  ('scientific-inquiry', 'causation', 'the act of causing something to happen'),
  ('scientific-inquiry', 'variable', 'a factor in an experiment that can change or be changed'),
  ('scientific-inquiry', 'anomaly', 'something that is different from what is expected or normal'),
  ('scientific-inquiry', 'replicate', 'to repeat an experiment to see if the same result happens again'),
  ('scientific-inquiry', 'theoretical', 'based on ideas rather than practical experience or proof'),
  ('scientific-inquiry', 'quantify', 'to measure or express something as a number'),
  ('scientific-inquiry', 'systematic', 'done in an organized, careful, and methodical way'),
  ('literary-analysis', 'narrative', 'a spoken or written account of events; a story'),
  ('literary-analysis', 'protagonist', 'the main character in a story'),
  ('literary-analysis', 'motif', 'an idea or image that repeats throughout a piece of writing'),
  ('literary-analysis', 'symbolism', 'the use of objects or images to represent ideas'),
  ('literary-analysis', 'foreshadowing', 'a hint about something that will happen later in a story'),
  ('literary-analysis', 'juxtaposition', 'placing two different things close together to highlight their contrast'),
  ('literary-analysis', 'prose', 'ordinary written language, not poetry'),
  ('literary-analysis', 'verse', 'writing arranged with a rhythm, as in poetry'),
  ('literary-analysis', 'metaphor', 'a way of describing something by calling it another thing to show a similarity'),
  ('literary-analysis', 'tone', 'the general feeling or attitude expressed in a piece of writing')
) as v(topic_slug, headword, definition_en)
join public.topics t on t.slug = v.topic_slug
where vi.topic_id = t.id and vi.headword = v.headword;
