-- Level expansion (generated by scripts/generate-level-expansion.mjs from
-- scripts/content/levelExpansion.mjs — edit the content there, not here).
-- Fills the levels the content inventory showed were thin:
--   vocabulary: 13 new topics (130 words, with IPA, example and English definition),
--   grammar: 5 new topics with a lesson and practice,
--   writing: 16 new prompts (first ever at C1/C2),
--   speaking: 9 new scenarios (first ever at C1/C2).
-- All content is original. Safe to re-run: rows are upserted by slug, or
-- cleared and reinserted for these topics; writing prompts insert only if
-- the same prompt text isn't there yet.

insert into public.topics (slug, name_he, name_en, cefr_level, sort_order) values
  ('kitchen-cooking', 'מטבח ובישול', 'Kitchen & Cooking', 'A2', 23),
  ('nature-outdoors', 'טבע ונופים', 'Nature & the Outdoors', 'A2', 24),
  ('work-office', 'עבודה ומשרד', 'Work & the Office', 'B1', 25),
  ('money-banking', 'כסף ובנקים', 'Money & Banking', 'B1', 26),
  ('media-news', 'תקשורת וחדשות', 'Media & News', 'B1', 27),
  ('relationships', 'יחסים בין אנשים', 'Relationships', 'B1', 28),
  ('travel-planning', 'תכנון נסיעה', 'Planning a Trip', 'B1', 29),
  ('crime-law', 'פשע ומשפט', 'Crime & the Law', 'B2', 30),
  ('education-learning', 'השכלה ולימודים', 'Education & Learning', 'B2', 31),
  ('urban-life', 'חיים בעיר', 'City Life', 'B2', 32),
  ('politics-government', 'פוליטיקה ושלטון', 'Politics & Government', 'C1', 33),
  ('media-communication', 'מדיה ותקשורת המונים', 'Media & Public Communication', 'C1', 34),
  ('economy-finance', 'כלכלה ומשק', 'The Economy', 'C1', 35)
on conflict (slug) do update set
  name_he = excluded.name_he,
  name_en = excluded.name_en,
  cefr_level = excluded.cefr_level,
  sort_order = excluded.sort_order;

delete from public.exercises where topic_id in (select id from public.topics where slug in ('kitchen-cooking', 'nature-outdoors', 'work-office', 'money-banking', 'media-news', 'relationships', 'travel-planning', 'crime-law', 'education-learning', 'urban-life', 'politics-government', 'media-communication', 'economy-finance'));
delete from public.vocabulary_items where topic_id in (select id from public.topics where slug in ('kitchen-cooking', 'nature-outdoors', 'work-office', 'money-banking', 'media-news', 'relationships', 'travel-planning', 'crime-law', 'education-learning', 'urban-life', 'politics-government', 'media-communication', 'economy-finance'));

insert into public.vocabulary_items (topic_id, headword, ipa, part_of_speech, translation_he, example_en, definition_en, cefr_level, sort_order)
select t.id, v.headword, v.ipa, v.part_of_speech, v.translation_he, v.example_en, v.definition_en, t.cefr_level, v.sort_order
from public.topics t
join (values
  ('kitchen-cooking', 'boil', '/bɔɪl/', 'verb', 'להרתיח', 'Boil the water before you add the pasta.', 'to heat a liquid until it bubbles', 1),
  ('kitchen-cooking', 'fry', '/fraɪ/', 'verb', 'לטגן', 'My dad likes to fry eggs in the morning.', 'to cook food in hot oil', 2),
  ('kitchen-cooking', 'bake', '/beɪk/', 'verb', 'לאפות', 'We bake a cake for every birthday.', 'to cook food like bread or cake in an oven', 3),
  ('kitchen-cooking', 'slice', '/slaɪs/', 'verb', 'לפרוס', 'Can you slice the bread, please?', 'to cut something into thin pieces', 4),
  ('kitchen-cooking', 'stir', '/stɜːr/', 'verb', 'לערבב', 'Stir the soup so it doesn''t burn.', 'to move a spoon around in a liquid to mix it', 5),
  ('kitchen-cooking', 'pan', '/pæn/', 'noun', 'מחבת', 'Put a little oil in the pan.', 'a flat metal pot used for frying', 6),
  ('kitchen-cooking', 'oven', '/ˈʌvən/', 'noun', 'תנור', 'The chicken is in the oven.', 'a box-shaped machine that cooks food with heat', 7),
  ('kitchen-cooking', 'recipe', '/ˈresəpi/', 'noun', 'מתכון', 'This recipe is from my grandmother.', 'instructions for cooking a dish', 8),
  ('kitchen-cooking', 'ingredient', '/ɪnˈɡriːdiənt/', 'noun', 'מרכיב', 'Flour is the main ingredient in bread.', 'one of the foods you use to make a dish', 9),
  ('kitchen-cooking', 'taste', '/teɪst/', 'verb', 'לטעום', 'Taste the sauce and add salt if you need it.', 'to try a little food to see what it is like', 10),
  ('nature-outdoors', 'forest', '/ˈfɔːrɪst/', 'noun', 'יער', 'We walked through the forest for two hours.', 'a large area full of trees', 1),
  ('nature-outdoors', 'river', '/ˈrɪvər/', 'noun', 'נהר', 'The river runs through the middle of the city.', 'a long line of water that flows to the sea', 2),
  ('nature-outdoors', 'mountain', '/ˈmaʊntən/', 'noun', 'הר', 'They climbed the mountain on Saturday.', 'a very high hill', 3),
  ('nature-outdoors', 'lake', '/leɪk/', 'noun', 'אגם', 'In summer we swim in the lake.', 'a large area of water with land all around it', 4),
  ('nature-outdoors', 'beach', '/biːtʃ/', 'noun', 'חוף ים', 'The beach is ten minutes from our hotel.', 'the sandy area next to the sea', 5),
  ('nature-outdoors', 'island', '/ˈaɪlənd/', 'noun', 'אי', 'Cyprus is an island in the Mediterranean.', 'land with water on every side', 6),
  ('nature-outdoors', 'flower', '/ˈflaʊər/', 'noun', 'פרח', 'She gave her mother a flower.', 'the colorful part of a plant', 7),
  ('nature-outdoors', 'grass', '/ɡræs/', 'noun', 'דשא', 'The children are playing on the grass.', 'the thin green plant that covers parks and fields', 8),
  ('nature-outdoors', 'hill', '/hɪl/', 'noun', 'גבעה', 'Our house is at the top of a hill.', 'a high area of land, smaller than a mountain', 9),
  ('nature-outdoors', 'desert', '/ˈdezərt/', 'noun', 'מדבר', 'It almost never rains in the desert.', 'a very dry area with sand and few plants', 10),
  ('work-office', 'colleague', '/ˈkɒliːɡ/', 'noun', 'עמית לעבודה', 'I had lunch with a colleague from the sales team.', 'a person you work with', 1),
  ('work-office', 'manager', '/ˈmænɪdʒər/', 'noun', 'מנהל', 'Ask your manager if you can leave early.', 'the person in charge of a team or department', 2),
  ('work-office', 'meeting', '/ˈmiːtɪŋ/', 'noun', 'פגישה', 'The meeting starts at nine.', 'an event where people come together to discuss something', 3),
  ('work-office', 'salary', '/ˈsæləri/', 'noun', 'משכורת', 'Her salary went up this year.', 'the money you get every month for your job', 4),
  ('work-office', 'schedule', '/ˈskedʒuːl/', 'noun', 'לוח זמנים', 'My schedule is full this week.', 'a plan of what you will do and when', 5),
  ('work-office', 'contract', '/ˈkɒntrækt/', 'noun', 'חוזה', 'Read the contract carefully before you sign it.', 'a written legal agreement', 6),
  ('work-office', 'employee', '/ɪmˈplɔɪiː/', 'noun', 'עובד', 'The company has two hundred employees.', 'a person who works for a company', 7),
  ('work-office', 'promotion', '/prəˈmoʊʃən/', 'noun', 'קידום', 'He got a promotion after three years.', 'a move to a higher job in the same company', 8),
  ('work-office', 'resign', '/rɪˈzaɪn/', 'verb', 'להתפטר', 'She resigned because she found a better job.', 'to leave your job by choice', 9),
  ('work-office', 'task', '/tæsk/', 'noun', 'משימה', 'My first task today is to answer emails.', 'a piece of work that you have to do', 10),
  ('money-banking', 'account', '/əˈkaʊnt/', 'noun', 'חשבון בנק', 'I opened a bank account when I started working.', 'an arrangement to keep your money in a bank', 1),
  ('money-banking', 'loan', '/loʊn/', 'noun', 'הלוואה', 'They took a loan to buy a car.', 'money that you borrow and must pay back', 2),
  ('money-banking', 'savings', '/ˈseɪvɪŋz/', 'noun', 'חסכונות', 'She used her savings to travel.', 'money that you keep and do not spend', 3),
  ('money-banking', 'debt', '/det/', 'noun', 'חוב', 'He paid off all his debt last year.', 'money that you owe someone', 4),
  ('money-banking', 'invest', '/ɪnˈvest/', 'verb', 'להשקיע', 'They want to invest in a small business.', 'to put money into something to make more money', 5),
  ('money-banking', 'withdraw', '/wɪðˈdrɔː/', 'verb', 'למשוך (כסף)', 'I need to withdraw some money from the ATM.', 'to take money out of a bank account', 6),
  ('money-banking', 'afford', '/əˈfɔːrd/', 'verb', 'להרשות לעצמו (כלכלית)', 'We can''t afford a new apartment right now.', 'to have enough money to pay for something', 7),
  ('money-banking', 'borrow', '/ˈbɒroʊ/', 'verb', 'ללוות', 'Can I borrow ten shekels until tomorrow?', 'to take something that you will give back later', 8),
  ('money-banking', 'expense', '/ɪkˈspens/', 'noun', 'הוצאה', 'Rent is our biggest monthly expense.', 'money that you spend on something', 9),
  ('money-banking', 'refund', '/ˈriːfʌnd/', 'noun', 'החזר כספי', 'The shop gave me a full refund.', 'money that is paid back to you, for example when you return something', 10),
  ('media-news', 'headline', '/ˈhedlaɪn/', 'noun', 'כותרת', 'The headline was about the election.', 'the title of a news story, in large letters', 1),
  ('media-news', 'journalist', '/ˈdʒɜːrnəlɪst/', 'noun', 'עיתונאי', 'The journalist interviewed the mayor.', 'a person who writes or reports the news', 2),
  ('media-news', 'article', '/ˈɑːrtɪkəl/', 'noun', 'כתבה, מאמר', 'I read an interesting article about sleep.', 'a piece of writing in a newspaper or on a website', 3),
  ('media-news', 'broadcast', '/ˈbrɔːdkæst/', 'verb', 'לשדר', 'The game will be broadcast live tonight.', 'to send out a program on TV or radio', 4),
  ('media-news', 'audience', '/ˈɔːdiəns/', 'noun', 'קהל', 'The show has a young audience.', 'the people who watch, read or listen to something', 5),
  ('media-news', 'reporter', '/rɪˈpɔːrtər/', 'noun', 'כתב', 'A reporter was waiting outside the court.', 'a journalist who collects and tells the news', 6),
  ('media-news', 'rumor', '/ˈruːmər/', 'noun', 'שמועה', 'Don''t believe every rumor you hear online.', 'a story that may not be true, passed from person to person', 7),
  ('media-news', 'source', '/sɔːrs/', 'noun', 'מקור', 'Always check the source of the information.', 'the place or person information comes from', 8),
  ('media-news', 'advertisement', '/ˌædvərˈtaɪzmənt/', 'noun', 'פרסומת', 'There was an advertisement before the video.', 'a short message that tries to make you buy something', 9),
  ('media-news', 'editor', '/ˈedɪtər/', 'noun', 'עורך', 'The editor changed the title of my story.', 'a person who checks and corrects writing before it is published', 10),
  ('relationships', 'trust', '/trʌst/', 'verb', 'לסמוך על', 'I trust my best friend completely.', 'to believe that someone is honest and will not hurt you', 1),
  ('relationships', 'argue', '/ˈɑːrɡjuː/', 'verb', 'להתווכח', 'My brothers argue about everything.', 'to disagree with someone in an angry way', 2),
  ('relationships', 'apologize', '/əˈpɒlədʒaɪz/', 'verb', 'להתנצל', 'He apologized for being late.', 'to say that you are sorry', 3),
  ('relationships', 'jealous', '/ˈdʒeləs/', 'adjective', 'מקנא', 'She was jealous of her sister''s new phone.', 'unhappy because someone has something you want', 4),
  ('relationships', 'loyal', '/ˈlɔɪəl/', 'adjective', 'נאמן', 'A loyal friend stays with you in hard times.', 'always supporting someone', 5),
  ('relationships', 'support', '/səˈpɔːrt/', 'verb', 'לתמוך', 'My parents support my decision.', 'to help and encourage someone', 6),
  ('relationships', 'partner', '/ˈpɑːrtnər/', 'noun', 'בן או בת זוג', 'She lives with her partner in Haifa.', 'the person you are in a relationship with', 7),
  ('relationships', 'engaged', '/ɪnˈɡeɪdʒd/', 'adjective', 'מאורס', 'They got engaged last summer.', 'having agreed to marry someone', 8),
  ('relationships', 'get along', '/ɡet əˈlɔːŋ/', 'verb', 'להסתדר עם', 'I get along well with my neighbors.', 'to have a friendly relationship with someone', 9),
  ('relationships', 'respect', '/rɪˈspekt/', 'noun', 'כבוד', 'Good teams are built on respect.', 'a feeling that someone is important and should be treated well', 10),
  ('travel-planning', 'itinerary', '/aɪˈtɪnəreri/', 'noun', 'מסלול טיול', 'Our itinerary includes three cities in five days.', 'a detailed plan of a journey', 1),
  ('travel-planning', 'passport', '/ˈpæspɔːrt/', 'noun', 'דרכון', 'Don''t forget your passport at the airport.', 'an official document you need to travel abroad', 2),
  ('travel-planning', 'luggage', '/ˈlʌɡɪdʒ/', 'noun', 'מזוודות', 'My luggage didn''t arrive with the flight.', 'the bags you take when you travel', 3),
  ('travel-planning', 'reservation', '/ˌrezərˈveɪʃən/', 'noun', 'הזמנה מראש', 'We have a reservation for two nights.', 'an arrangement to keep a room or table for you', 4),
  ('travel-planning', 'destination', '/ˌdestɪˈneɪʃən/', 'noun', 'יעד', 'Rome is a popular destination in spring.', 'the place you are traveling to', 5),
  ('travel-planning', 'departure', '/dɪˈpɑːrtʃər/', 'noun', 'יציאה, המראה', 'Check the departure time on your ticket.', 'the act of leaving a place', 6),
  ('travel-planning', 'delay', '/dɪˈleɪ/', 'noun', 'עיכוב', 'There was a two-hour delay because of the storm.', 'a situation when something happens later than planned', 7),
  ('travel-planning', 'sightseeing', '/ˈsaɪtsiːɪŋ/', 'noun', 'סיור באתרים', 'We spent the morning sightseeing in the old city.', 'visiting famous places as a tourist', 8),
  ('travel-planning', 'accommodation', '/əˌkɒməˈdeɪʃən/', 'noun', 'מקום לינה', 'The price includes flights and accommodation.', 'a place to stay, like a hotel or apartment', 9),
  ('travel-planning', 'insurance', '/ɪnˈʃʊrəns/', 'noun', 'ביטוח', 'Buy travel insurance before you go.', 'an agreement that pays you if something bad happens', 10),
  ('crime-law', 'suspect', '/ˈsʌspekt/', 'noun', 'חשוד', 'The police arrested a suspect last night.', 'a person who may have committed a crime', 1),
  ('crime-law', 'witness', '/ˈwɪtnəs/', 'noun', 'עד', 'A witness saw the car leave the scene.', 'a person who saw something happen and can describe it', 2),
  ('crime-law', 'trial', '/ˈtraɪəl/', 'noun', 'משפט (בבית משפט)', 'The trial will last several weeks.', 'the process in a court that decides if someone is guilty', 3),
  ('crime-law', 'jury', '/ˈdʒʊri/', 'noun', 'חבר מושבעים', 'The jury needed two days to reach a verdict.', 'a group of citizens who decide a case in court', 4),
  ('crime-law', 'sentence', '/ˈsentəns/', 'noun', 'גזר דין', 'He received a sentence of three years.', 'the punishment a judge gives', 5),
  ('crime-law', 'arrest', '/əˈrest/', 'verb', 'לעצור', 'The officers arrested two men at the border.', 'to take someone to the police because of a crime', 6),
  ('crime-law', 'guilty', '/ˈɡɪlti/', 'adjective', 'אשם', 'The court found her not guilty.', 'responsible for doing something illegal or wrong', 7),
  ('crime-law', 'victim', '/ˈvɪktɪm/', 'noun', 'קורבן', 'The victim was taken to hospital.', 'a person who is hurt or harmed by a crime', 8),
  ('crime-law', 'fraud', '/frɔːd/', 'noun', 'הונאה', 'The company was accused of fraud.', 'the crime of tricking people to get money', 9),
  ('crime-law', 'verdict', '/ˈvɜːrdɪkt/', 'noun', 'פסק דין', 'Everyone waited quietly for the verdict.', 'the official decision at the end of a trial', 10),
  ('education-learning', 'curriculum', '/kəˈrɪkjələm/', 'noun', 'תוכנית לימודים', 'Coding is now part of the school curriculum.', 'all the subjects taught in a school or course', 1),
  ('education-learning', 'lecture', '/ˈlektʃər/', 'noun', 'הרצאה', 'The lecture on climate was recorded.', 'a formal talk to a group of students', 2),
  ('education-learning', 'assignment', '/əˈsaɪnmənt/', 'noun', 'מטלה', 'The assignment is due on Monday.', 'a piece of work given to a student', 3),
  ('education-learning', 'scholarship', '/ˈskɒlərʃɪp/', 'noun', 'מלגה', 'She won a scholarship to study abroad.', 'money given to a student to pay for their studies', 4),
  ('education-learning', 'tuition', '/tuːˈɪʃən/', 'noun', 'שכר לימוד', 'Tuition at private universities is expensive.', 'the money paid for teaching at a school or university', 5),
  ('education-learning', 'semester', '/sɪˈmestər/', 'noun', 'סמסטר', 'I''m taking four courses this semester.', 'one of the two main periods of the academic year', 6),
  ('education-learning', 'degree', '/dɪˈɡriː/', 'noun', 'תואר אקדמי', 'He has a degree in engineering.', 'the qualification you get after finishing university', 7),
  ('education-learning', 'graduate', '/ˈɡrædʒueɪt/', 'verb', 'לסיים לימודים', 'She graduated from Tel Aviv University in 2024.', 'to finish your studies and receive a degree', 8),
  ('education-learning', 'literacy', '/ˈlɪtərəsi/', 'noun', 'אוריינות', 'Reading at home improves children''s literacy.', 'the ability to read and write', 9),
  ('education-learning', 'vocational', '/voʊˈkeɪʃənəl/', 'adjective', 'מקצועי (הכשרה)', 'He chose a vocational course in electronics.', 'teaching the skills needed for a particular job', 10),
  ('urban-life', 'congestion', '/kənˈdʒestʃən/', 'noun', 'עומס תנועה', 'Congestion is worst between eight and nine.', 'too much traffic in one place', 1),
  ('urban-life', 'pedestrian', '/pəˈdestriən/', 'noun', 'הולך רגל', 'This street is only for pedestrians.', 'a person who is walking, not driving', 2),
  ('urban-life', 'suburb', '/ˈsʌbɜːrb/', 'noun', 'פרבר', 'They moved to a quiet suburb outside the city.', 'an area where people live at the edge of a city', 3),
  ('urban-life', 'commute', '/kəˈmjuːt/', 'verb', 'לנסוע לעבודה וממנה', 'I commute to work by train.', 'to travel regularly between home and work', 4),
  ('urban-life', 'residential', '/ˌrezɪˈdenʃəl/', 'adjective', 'מגורים (אזור)', 'It''s a residential area with few shops.', 'used for people''s homes rather than businesses', 5),
  ('urban-life', 'infrastructure', '/ˈɪnfrəstrʌktʃər/', 'noun', 'תשתית', 'The city is investing in new infrastructure.', 'basic systems like roads, water and electricity', 6),
  ('urban-life', 'skyscraper', '/ˈskaɪskreɪpər/', 'noun', 'גורד שחקים', 'The new skyscraper has sixty floors.', 'a very tall building in a city', 7),
  ('urban-life', 'neighborhood', '/ˈneɪbərhʊd/', 'noun', 'שכונה', 'I grew up in a friendly neighborhood.', 'an area of a town where people live', 8),
  ('urban-life', 'crowded', '/ˈkraʊdɪd/', 'adjective', 'צפוף', 'The bus was so crowded that I had to stand.', 'full of too many people', 9),
  ('urban-life', 'affordable', '/əˈfɔːrdəbəl/', 'adjective', 'במחיר סביר', 'Young families need affordable housing.', 'cheap enough for most people to pay for', 10),
  ('politics-government', 'parliament', '/ˈpɑːrləmənt/', 'noun', 'פרלמנט', 'The bill was debated in parliament for weeks.', 'the group of elected people who make a country''s laws', 1),
  ('politics-government', 'legislation', '/ˌledʒɪsˈleɪʃən/', 'noun', 'חקיקה', 'New legislation will protect online privacy.', 'a law or a set of laws', 2),
  ('politics-government', 'candidate', '/ˈkændɪdət/', 'noun', 'מועמד', 'Each candidate gave a short speech.', 'a person who wants to be elected or chosen', 3),
  ('politics-government', 'coalition', '/ˌkoʊəˈlɪʃən/', 'noun', 'קואליציה', 'Three parties formed a coalition government.', 'a group of parties that agree to govern together', 4),
  ('politics-government', 'referendum', '/ˌrefəˈrendəm/', 'noun', 'משאל עם', 'The decision was put to a referendum.', 'a vote by all citizens on one specific question', 5),
  ('politics-government', 'accountable', '/əˈkaʊntəbəl/', 'adjective', 'נושא באחריות', 'Leaders must be held accountable for their decisions.', 'expected to explain and take responsibility for actions', 6),
  ('politics-government', 'constituency', '/kənˈstɪtʃuənsi/', 'noun', 'אזור בחירה', 'She represents a rural constituency.', 'an area whose voters elect a representative', 7),
  ('politics-government', 'veto', '/ˈviːtoʊ/', 'verb', 'להטיל וטו', 'The president vetoed the new tax law.', 'to officially reject a decision or law', 8),
  ('politics-government', 'bureaucracy', '/bjʊˈrɒkrəsi/', 'noun', 'ביורוקרטיה', 'Too much bureaucracy slows down small businesses.', 'complicated official rules and procedures', 9),
  ('politics-government', 'sovereignty', '/ˈsɒvrənti/', 'noun', 'ריבונות', 'The treaty respects each nation''s sovereignty.', 'the power of a country to govern itself', 10),
  ('media-communication', 'propaganda', '/ˌprɒpəˈɡændə/', 'noun', 'תעמולה', 'The poster was a piece of wartime propaganda.', 'information used to push people toward one opinion', 1),
  ('media-communication', 'censorship', '/ˈsensərʃɪp/', 'noun', 'צנזורה', 'The film was banned because of censorship.', 'stopping people from seeing or publishing certain content', 2),
  ('media-communication', 'credibility', '/ˌkredəˈbɪləti/', 'noun', 'אמינות', 'The scandal damaged the newspaper''s credibility.', 'the quality of being trusted and believed', 3),
  ('media-communication', 'misinformation', '/ˌmɪsɪnfərˈmeɪʃən/', 'noun', 'מידע שגוי', 'Misinformation spreads quickly on social media.', 'false information, whether or not it is meant to trick people', 4),
  ('media-communication', 'coverage', '/ˈkʌvərɪdʒ/', 'noun', 'סיקור', 'The election got wide coverage abroad.', 'the way news reports on an event', 5),
  ('media-communication', 'editorial', '/ˌedɪˈtɔːriəl/', 'noun', 'מאמר מערכת', 'The editorial criticized the new policy.', 'an article giving a newspaper''s own opinion', 6),
  ('media-communication', 'spokesperson', '/ˈspoʊkspɜːrsən/', 'noun', 'דובר', 'A spokesperson for the company declined to comment.', 'a person chosen to speak for an organization', 7),
  ('media-communication', 'sensationalism', '/senˈseɪʃənəlɪzəm/', 'noun', 'סנסציוניות', 'Readers are tired of sensationalism in the news.', 'presenting stories in a shocking way to attract attention', 8),
  ('media-communication', 'transparency', '/trænsˈpærənsi/', 'noun', 'שקיפות', 'The public expects transparency from officials.', 'openness about decisions, so others can check them', 9),
  ('media-communication', 'outlet', '/ˈaʊtlet/', 'noun', 'כלי תקשורת', 'Several news outlets reported the story.', 'a company that publishes or broadcasts news', 10),
  ('economy-finance', 'inflation', '/ɪnˈfleɪʃən/', 'noun', 'אינפלציה', 'Inflation made food much more expensive this year.', 'a general rise in prices over time', 1),
  ('economy-finance', 'recession', '/rɪˈseʃən/', 'noun', 'מיתון', 'Many people lost their jobs during the recession.', 'a period when a country''s economy gets smaller', 2),
  ('economy-finance', 'currency', '/ˈkɜːrənsi/', 'noun', 'מטבע', 'The shekel is Israel''s currency.', 'the money used in a particular country', 3),
  ('economy-finance', 'shareholder', '/ˈʃerhoʊldər/', 'noun', 'בעל מניות', 'Shareholders voted against the merger.', 'a person who owns part of a company', 4),
  ('economy-finance', 'unemployment', '/ˌʌnɪmˈplɔɪmənt/', 'noun', 'אבטלה', 'Unemployment fell to its lowest level in years.', 'the number of people who want work but have none', 5),
  ('economy-finance', 'subsidy', '/ˈsʌbsɪdi/', 'noun', 'סובסידיה', 'Farmers receive a government subsidy for water.', 'money a government pays to keep prices low or help an industry', 6),
  ('economy-finance', 'fiscal', '/ˈfɪskəl/', 'adjective', 'פיסקלי, תקציבי', 'The government announced new fiscal measures.', 'relating to government taxes and spending', 7),
  ('economy-finance', 'monopoly', '/məˈnɒpəli/', 'noun', 'מונופול', 'One company has a monopoly on the market.', 'complete control of a market by one company', 8),
  ('economy-finance', 'surplus', '/ˈsɜːrpləs/', 'noun', 'עודף', 'The country had a trade surplus last year.', 'an amount that is more than what is needed', 9),
  ('economy-finance', 'volatile', '/ˈvɒlətaɪl/', 'adjective', 'תנודתי', 'Oil prices have been volatile this month.', 'likely to change suddenly and without warning', 10)
) as v(topic_slug, headword, ipa, part_of_speech, translation_he, example_en, definition_en, sort_order)
  on t.slug = v.topic_slug;

insert into public.exercises (type, skill_area, topic_id, vocabulary_item_id, cefr_level, content, sort_order)
select 'mcq'::exercise_type, 'vocabulary'::skill_area, t.id, v.id, t.cefr_level, gen.content::jsonb, gen.sort_order
from (values
  ('kitchen-cooking', 'boil', '{"prompt":"מה המילה באנגלית עבור \"להרתיח\"?","options":["boil","fry","slice","pan"],"correctIndex":0}', 1),
  ('kitchen-cooking', 'fry', '{"prompt":"מה המילה באנגלית עבור \"לטגן\"?","options":["stir","fry","oven","ingredient"],"correctIndex":1}', 2),
  ('kitchen-cooking', 'bake', '{"prompt":"מה המילה באנגלית עבור \"לאפות\"?","options":["recipe","taste","bake","fry"],"correctIndex":2}', 3),
  ('kitchen-cooking', 'slice', '{"prompt":"מה המילה באנגלית עבור \"לפרוס\"?","options":["boil","bake","pan","slice"],"correctIndex":3}', 4),
  ('kitchen-cooking', 'stir', '{"prompt":"מה המילה באנגלית עבור \"לערבב\"?","options":["stir","slice","oven","ingredient"],"correctIndex":0}', 5),
  ('kitchen-cooking', 'pan', '{"prompt":"מה המילה באנגלית עבור \"מחבת\"?","options":["recipe","pan","taste","fry"],"correctIndex":1}', 6),
  ('kitchen-cooking', 'oven', '{"prompt":"מה המילה באנגלית עבור \"תנור\"?","options":["boil","bake","oven","stir"],"correctIndex":2}', 7),
  ('kitchen-cooking', 'recipe', '{"prompt":"מה המילה באנגלית עבור \"מתכון\"?","options":["slice","pan","ingredient","recipe"],"correctIndex":3}', 8),
  ('kitchen-cooking', 'ingredient', '{"prompt":"מה המילה באנגלית עבור \"מרכיב\"?","options":["ingredient","oven","taste","fry"],"correctIndex":0}', 9),
  ('kitchen-cooking', 'taste', '{"prompt":"מה המילה באנגלית עבור \"לטעום\"?","options":["boil","taste","bake","stir"],"correctIndex":1}', 10),
  ('nature-outdoors', 'forest', '{"prompt":"מה המילה באנגלית עבור \"יער\"?","options":["forest","river","lake","island"],"correctIndex":0}', 1),
  ('nature-outdoors', 'river', '{"prompt":"מה המילה באנגלית עבור \"נהר\"?","options":["beach","river","flower","hill"],"correctIndex":1}', 2),
  ('nature-outdoors', 'mountain', '{"prompt":"מה המילה באנגלית עבור \"הר\"?","options":["grass","desert","mountain","river"],"correctIndex":2}', 3),
  ('nature-outdoors', 'lake', '{"prompt":"מה המילה באנגלית עבור \"אגם\"?","options":["forest","mountain","island","lake"],"correctIndex":3}', 4),
  ('nature-outdoors', 'beach', '{"prompt":"מה המילה באנגלית עבור \"חוף ים\"?","options":["beach","lake","flower","hill"],"correctIndex":0}', 5),
  ('nature-outdoors', 'island', '{"prompt":"מה המילה באנגלית עבור \"אי\"?","options":["grass","island","desert","river"],"correctIndex":1}', 6),
  ('nature-outdoors', 'flower', '{"prompt":"מה המילה באנגלית עבור \"פרח\"?","options":["forest","mountain","flower","beach"],"correctIndex":2}', 7),
  ('nature-outdoors', 'grass', '{"prompt":"מה המילה באנגלית עבור \"דשא\"?","options":["lake","island","hill","grass"],"correctIndex":3}', 8),
  ('nature-outdoors', 'hill', '{"prompt":"מה המילה באנגלית עבור \"גבעה\"?","options":["hill","flower","desert","river"],"correctIndex":0}', 9),
  ('nature-outdoors', 'desert', '{"prompt":"מה המילה באנגלית עבור \"מדבר\"?","options":["forest","desert","mountain","beach"],"correctIndex":1}', 10),
  ('work-office', 'colleague', '{"prompt":"מה המילה באנגלית עבור \"עמית לעבודה\"?","options":["colleague","manager","salary","contract"],"correctIndex":0}', 1),
  ('work-office', 'manager', '{"prompt":"מה המילה באנגלית עבור \"מנהל\"?","options":["schedule","manager","employee","resign"],"correctIndex":1}', 2),
  ('work-office', 'meeting', '{"prompt":"מה המילה באנגלית עבור \"פגישה\"?","options":["promotion","task","meeting","manager"],"correctIndex":2}', 3),
  ('work-office', 'salary', '{"prompt":"מה המילה באנגלית עבור \"משכורת\"?","options":["colleague","meeting","contract","salary"],"correctIndex":3}', 4),
  ('work-office', 'schedule', '{"prompt":"מה המילה באנגלית עבור \"לוח זמנים\"?","options":["schedule","salary","employee","resign"],"correctIndex":0}', 5),
  ('work-office', 'contract', '{"prompt":"מה המילה באנגלית עבור \"חוזה\"?","options":["promotion","contract","task","manager"],"correctIndex":1}', 6),
  ('work-office', 'employee', '{"prompt":"מה המילה באנגלית עבור \"עובד\"?","options":["colleague","meeting","employee","schedule"],"correctIndex":2}', 7),
  ('work-office', 'promotion', '{"prompt":"מה המילה באנגלית עבור \"קידום\"?","options":["salary","contract","resign","promotion"],"correctIndex":3}', 8),
  ('work-office', 'resign', '{"prompt":"מה המילה באנגלית עבור \"להתפטר\"?","options":["resign","employee","task","manager"],"correctIndex":0}', 9),
  ('work-office', 'task', '{"prompt":"מה המילה באנגלית עבור \"משימה\"?","options":["colleague","task","meeting","schedule"],"correctIndex":1}', 10),
  ('money-banking', 'account', '{"prompt":"מה המילה באנגלית עבור \"חשבון בנק\"?","options":["account","loan","debt","withdraw"],"correctIndex":0}', 1),
  ('money-banking', 'loan', '{"prompt":"מה המילה באנגלית עבור \"הלוואה\"?","options":["invest","loan","afford","expense"],"correctIndex":1}', 2),
  ('money-banking', 'savings', '{"prompt":"מה המילה באנגלית עבור \"חסכונות\"?","options":["borrow","refund","savings","loan"],"correctIndex":2}', 3),
  ('money-banking', 'debt', '{"prompt":"מה המילה באנגלית עבור \"חוב\"?","options":["account","savings","withdraw","debt"],"correctIndex":3}', 4),
  ('money-banking', 'invest', '{"prompt":"מה המילה באנגלית עבור \"להשקיע\"?","options":["invest","debt","afford","expense"],"correctIndex":0}', 5),
  ('money-banking', 'withdraw', '{"prompt":"מה המילה באנגלית עבור \"למשוך (כסף)\"?","options":["borrow","withdraw","refund","loan"],"correctIndex":1}', 6),
  ('money-banking', 'afford', '{"prompt":"מה המילה באנגלית עבור \"להרשות לעצמו (כלכלית)\"?","options":["account","savings","afford","invest"],"correctIndex":2}', 7),
  ('money-banking', 'borrow', '{"prompt":"מה המילה באנגלית עבור \"ללוות\"?","options":["debt","withdraw","expense","borrow"],"correctIndex":3}', 8),
  ('money-banking', 'expense', '{"prompt":"מה המילה באנגלית עבור \"הוצאה\"?","options":["expense","afford","refund","loan"],"correctIndex":0}', 9),
  ('money-banking', 'refund', '{"prompt":"מה המילה באנגלית עבור \"החזר כספי\"?","options":["account","refund","savings","invest"],"correctIndex":1}', 10),
  ('media-news', 'headline', '{"prompt":"מה המילה באנגלית עבור \"כותרת\"?","options":["headline","journalist","broadcast","reporter"],"correctIndex":0}', 1),
  ('media-news', 'journalist', '{"prompt":"מה המילה באנגלית עבור \"עיתונאי\"?","options":["audience","journalist","rumor","advertisement"],"correctIndex":1}', 2),
  ('media-news', 'article', '{"prompt":"מה המילה באנגלית עבור \"כתבה, מאמר\"?","options":["source","editor","article","journalist"],"correctIndex":2}', 3),
  ('media-news', 'broadcast', '{"prompt":"מה המילה באנגלית עבור \"לשדר\"?","options":["headline","article","reporter","broadcast"],"correctIndex":3}', 4),
  ('media-news', 'audience', '{"prompt":"מה המילה באנגלית עבור \"קהל\"?","options":["audience","broadcast","rumor","advertisement"],"correctIndex":0}', 5),
  ('media-news', 'reporter', '{"prompt":"מה המילה באנגלית עבור \"כתב\"?","options":["source","reporter","editor","journalist"],"correctIndex":1}', 6),
  ('media-news', 'rumor', '{"prompt":"מה המילה באנגלית עבור \"שמועה\"?","options":["headline","article","rumor","audience"],"correctIndex":2}', 7),
  ('media-news', 'source', '{"prompt":"מה המילה באנגלית עבור \"מקור\"?","options":["broadcast","reporter","advertisement","source"],"correctIndex":3}', 8),
  ('media-news', 'advertisement', '{"prompt":"מה המילה באנגלית עבור \"פרסומת\"?","options":["advertisement","rumor","editor","journalist"],"correctIndex":0}', 9),
  ('media-news', 'editor', '{"prompt":"מה המילה באנגלית עבור \"עורך\"?","options":["headline","editor","article","audience"],"correctIndex":1}', 10),
  ('relationships', 'trust', '{"prompt":"מה המילה באנגלית עבור \"לסמוך על\"?","options":["trust","argue","jealous","support"],"correctIndex":0}', 1),
  ('relationships', 'argue', '{"prompt":"מה המילה באנגלית עבור \"להתווכח\"?","options":["loyal","argue","partner","get along"],"correctIndex":1}', 2),
  ('relationships', 'apologize', '{"prompt":"מה המילה באנגלית עבור \"להתנצל\"?","options":["engaged","respect","apologize","argue"],"correctIndex":2}', 3),
  ('relationships', 'jealous', '{"prompt":"מה המילה באנגלית עבור \"מקנא\"?","options":["trust","apologize","support","jealous"],"correctIndex":3}', 4),
  ('relationships', 'loyal', '{"prompt":"מה המילה באנגלית עבור \"נאמן\"?","options":["loyal","jealous","partner","get along"],"correctIndex":0}', 5),
  ('relationships', 'support', '{"prompt":"מה המילה באנגלית עבור \"לתמוך\"?","options":["engaged","support","respect","argue"],"correctIndex":1}', 6),
  ('relationships', 'partner', '{"prompt":"מה המילה באנגלית עבור \"בן או בת זוג\"?","options":["trust","apologize","partner","loyal"],"correctIndex":2}', 7),
  ('relationships', 'engaged', '{"prompt":"מה המילה באנגלית עבור \"מאורס\"?","options":["jealous","support","get along","engaged"],"correctIndex":3}', 8),
  ('relationships', 'get along', '{"prompt":"מה המילה באנגלית עבור \"להסתדר עם\"?","options":["get along","partner","respect","argue"],"correctIndex":0}', 9),
  ('relationships', 'respect', '{"prompt":"מה המילה באנגלית עבור \"כבוד\"?","options":["trust","respect","apologize","loyal"],"correctIndex":1}', 10),
  ('travel-planning', 'itinerary', '{"prompt":"מה המילה באנגלית עבור \"מסלול טיול\"?","options":["itinerary","passport","reservation","departure"],"correctIndex":0}', 1),
  ('travel-planning', 'passport', '{"prompt":"מה המילה באנגלית עבור \"דרכון\"?","options":["destination","passport","delay","accommodation"],"correctIndex":1}', 2),
  ('travel-planning', 'luggage', '{"prompt":"מה המילה באנגלית עבור \"מזוודות\"?","options":["sightseeing","insurance","luggage","passport"],"correctIndex":2}', 3),
  ('travel-planning', 'reservation', '{"prompt":"מה המילה באנגלית עבור \"הזמנה מראש\"?","options":["itinerary","luggage","departure","reservation"],"correctIndex":3}', 4),
  ('travel-planning', 'destination', '{"prompt":"מה המילה באנגלית עבור \"יעד\"?","options":["destination","reservation","delay","accommodation"],"correctIndex":0}', 5),
  ('travel-planning', 'departure', '{"prompt":"מה המילה באנגלית עבור \"יציאה, המראה\"?","options":["sightseeing","departure","insurance","passport"],"correctIndex":1}', 6),
  ('travel-planning', 'delay', '{"prompt":"מה המילה באנגלית עבור \"עיכוב\"?","options":["itinerary","luggage","delay","destination"],"correctIndex":2}', 7),
  ('travel-planning', 'sightseeing', '{"prompt":"מה המילה באנגלית עבור \"סיור באתרים\"?","options":["reservation","departure","accommodation","sightseeing"],"correctIndex":3}', 8),
  ('travel-planning', 'accommodation', '{"prompt":"מה המילה באנגלית עבור \"מקום לינה\"?","options":["accommodation","delay","insurance","passport"],"correctIndex":0}', 9),
  ('travel-planning', 'insurance', '{"prompt":"מה המילה באנגלית עבור \"ביטוח\"?","options":["itinerary","insurance","luggage","destination"],"correctIndex":1}', 10),
  ('crime-law', 'suspect', '{"prompt":"מה המילה באנגלית עבור \"חשוד\"?","options":["suspect","witness","jury","arrest"],"correctIndex":0}', 1),
  ('crime-law', 'witness', '{"prompt":"מה המילה באנגלית עבור \"עד\"?","options":["sentence","witness","guilty","fraud"],"correctIndex":1}', 2),
  ('crime-law', 'trial', '{"prompt":"מה המילה באנגלית עבור \"משפט (בבית משפט)\"?","options":["victim","verdict","trial","witness"],"correctIndex":2}', 3),
  ('crime-law', 'jury', '{"prompt":"מה המילה באנגלית עבור \"חבר מושבעים\"?","options":["suspect","trial","arrest","jury"],"correctIndex":3}', 4),
  ('crime-law', 'sentence', '{"prompt":"מה המילה באנגלית עבור \"גזר דין\"?","options":["sentence","jury","guilty","fraud"],"correctIndex":0}', 5),
  ('crime-law', 'arrest', '{"prompt":"מה המילה באנגלית עבור \"לעצור\"?","options":["victim","arrest","verdict","witness"],"correctIndex":1}', 6),
  ('crime-law', 'guilty', '{"prompt":"מה המילה באנגלית עבור \"אשם\"?","options":["suspect","trial","guilty","sentence"],"correctIndex":2}', 7),
  ('crime-law', 'victim', '{"prompt":"מה המילה באנגלית עבור \"קורבן\"?","options":["jury","arrest","fraud","victim"],"correctIndex":3}', 8),
  ('crime-law', 'fraud', '{"prompt":"מה המילה באנגלית עבור \"הונאה\"?","options":["fraud","guilty","verdict","witness"],"correctIndex":0}', 9),
  ('crime-law', 'verdict', '{"prompt":"מה המילה באנגלית עבור \"פסק דין\"?","options":["suspect","verdict","trial","sentence"],"correctIndex":1}', 10),
  ('education-learning', 'curriculum', '{"prompt":"מה המילה באנגלית עבור \"תוכנית לימודים\"?","options":["curriculum","lecture","scholarship","semester"],"correctIndex":0}', 1),
  ('education-learning', 'lecture', '{"prompt":"מה המילה באנגלית עבור \"הרצאה\"?","options":["tuition","lecture","degree","literacy"],"correctIndex":1}', 2),
  ('education-learning', 'assignment', '{"prompt":"מה המילה באנגלית עבור \"מטלה\"?","options":["graduate","vocational","assignment","lecture"],"correctIndex":2}', 3),
  ('education-learning', 'scholarship', '{"prompt":"מה המילה באנגלית עבור \"מלגה\"?","options":["curriculum","assignment","semester","scholarship"],"correctIndex":3}', 4),
  ('education-learning', 'tuition', '{"prompt":"מה המילה באנגלית עבור \"שכר לימוד\"?","options":["tuition","scholarship","degree","literacy"],"correctIndex":0}', 5),
  ('education-learning', 'semester', '{"prompt":"מה המילה באנגלית עבור \"סמסטר\"?","options":["graduate","semester","vocational","lecture"],"correctIndex":1}', 6),
  ('education-learning', 'degree', '{"prompt":"מה המילה באנגלית עבור \"תואר אקדמי\"?","options":["curriculum","assignment","degree","tuition"],"correctIndex":2}', 7),
  ('education-learning', 'graduate', '{"prompt":"מה המילה באנגלית עבור \"לסיים לימודים\"?","options":["scholarship","semester","literacy","graduate"],"correctIndex":3}', 8),
  ('education-learning', 'literacy', '{"prompt":"מה המילה באנגלית עבור \"אוריינות\"?","options":["literacy","degree","vocational","lecture"],"correctIndex":0}', 9),
  ('education-learning', 'vocational', '{"prompt":"מה המילה באנגלית עבור \"מקצועי (הכשרה)\"?","options":["curriculum","vocational","assignment","tuition"],"correctIndex":1}', 10),
  ('urban-life', 'congestion', '{"prompt":"מה המילה באנגלית עבור \"עומס תנועה\"?","options":["congestion","pedestrian","commute","infrastructure"],"correctIndex":0}', 1),
  ('urban-life', 'pedestrian', '{"prompt":"מה המילה באנגלית עבור \"הולך רגל\"?","options":["residential","pedestrian","skyscraper","crowded"],"correctIndex":1}', 2),
  ('urban-life', 'suburb', '{"prompt":"מה המילה באנגלית עבור \"פרבר\"?","options":["neighborhood","affordable","suburb","pedestrian"],"correctIndex":2}', 3),
  ('urban-life', 'commute', '{"prompt":"מה המילה באנגלית עבור \"לנסוע לעבודה וממנה\"?","options":["congestion","suburb","infrastructure","commute"],"correctIndex":3}', 4),
  ('urban-life', 'residential', '{"prompt":"מה המילה באנגלית עבור \"מגורים (אזור)\"?","options":["residential","commute","skyscraper","crowded"],"correctIndex":0}', 5),
  ('urban-life', 'infrastructure', '{"prompt":"מה המילה באנגלית עבור \"תשתית\"?","options":["neighborhood","infrastructure","affordable","pedestrian"],"correctIndex":1}', 6),
  ('urban-life', 'skyscraper', '{"prompt":"מה המילה באנגלית עבור \"גורד שחקים\"?","options":["congestion","suburb","skyscraper","residential"],"correctIndex":2}', 7),
  ('urban-life', 'neighborhood', '{"prompt":"מה המילה באנגלית עבור \"שכונה\"?","options":["commute","infrastructure","crowded","neighborhood"],"correctIndex":3}', 8),
  ('urban-life', 'crowded', '{"prompt":"מה המילה באנגלית עבור \"צפוף\"?","options":["crowded","skyscraper","affordable","pedestrian"],"correctIndex":0}', 9),
  ('urban-life', 'affordable', '{"prompt":"מה המילה באנגלית עבור \"במחיר סביר\"?","options":["congestion","affordable","suburb","residential"],"correctIndex":1}', 10),
  ('politics-government', 'parliament', '{"prompt":"מה המילה באנגלית עבור \"פרלמנט\"?","options":["parliament","legislation","coalition","accountable"],"correctIndex":0}', 1),
  ('politics-government', 'legislation', '{"prompt":"מה המילה באנגלית עבור \"חקיקה\"?","options":["referendum","legislation","constituency","bureaucracy"],"correctIndex":1}', 2),
  ('politics-government', 'candidate', '{"prompt":"מה המילה באנגלית עבור \"מועמד\"?","options":["veto","sovereignty","candidate","legislation"],"correctIndex":2}', 3),
  ('politics-government', 'coalition', '{"prompt":"מה המילה באנגלית עבור \"קואליציה\"?","options":["parliament","candidate","accountable","coalition"],"correctIndex":3}', 4),
  ('politics-government', 'referendum', '{"prompt":"מה המילה באנגלית עבור \"משאל עם\"?","options":["referendum","coalition","constituency","bureaucracy"],"correctIndex":0}', 5),
  ('politics-government', 'accountable', '{"prompt":"מה המילה באנגלית עבור \"נושא באחריות\"?","options":["veto","accountable","sovereignty","legislation"],"correctIndex":1}', 6),
  ('politics-government', 'constituency', '{"prompt":"מה המילה באנגלית עבור \"אזור בחירה\"?","options":["parliament","candidate","constituency","referendum"],"correctIndex":2}', 7),
  ('politics-government', 'veto', '{"prompt":"מה המילה באנגלית עבור \"להטיל וטו\"?","options":["coalition","accountable","bureaucracy","veto"],"correctIndex":3}', 8),
  ('politics-government', 'bureaucracy', '{"prompt":"מה המילה באנגלית עבור \"ביורוקרטיה\"?","options":["bureaucracy","constituency","sovereignty","legislation"],"correctIndex":0}', 9),
  ('politics-government', 'sovereignty', '{"prompt":"מה המילה באנגלית עבור \"ריבונות\"?","options":["parliament","sovereignty","candidate","referendum"],"correctIndex":1}', 10),
  ('media-communication', 'propaganda', '{"prompt":"מה המילה באנגלית עבור \"תעמולה\"?","options":["propaganda","censorship","misinformation","editorial"],"correctIndex":0}', 1),
  ('media-communication', 'censorship', '{"prompt":"מה המילה באנגלית עבור \"צנזורה\"?","options":["coverage","censorship","spokesperson","transparency"],"correctIndex":1}', 2),
  ('media-communication', 'credibility', '{"prompt":"מה המילה באנגלית עבור \"אמינות\"?","options":["sensationalism","outlet","credibility","censorship"],"correctIndex":2}', 3),
  ('media-communication', 'misinformation', '{"prompt":"מה המילה באנגלית עבור \"מידע שגוי\"?","options":["propaganda","credibility","editorial","misinformation"],"correctIndex":3}', 4),
  ('media-communication', 'coverage', '{"prompt":"מה המילה באנגלית עבור \"סיקור\"?","options":["coverage","misinformation","spokesperson","transparency"],"correctIndex":0}', 5),
  ('media-communication', 'editorial', '{"prompt":"מה המילה באנגלית עבור \"מאמר מערכת\"?","options":["sensationalism","editorial","outlet","censorship"],"correctIndex":1}', 6),
  ('media-communication', 'spokesperson', '{"prompt":"מה המילה באנגלית עבור \"דובר\"?","options":["propaganda","credibility","spokesperson","coverage"],"correctIndex":2}', 7),
  ('media-communication', 'sensationalism', '{"prompt":"מה המילה באנגלית עבור \"סנסציוניות\"?","options":["misinformation","editorial","transparency","sensationalism"],"correctIndex":3}', 8),
  ('media-communication', 'transparency', '{"prompt":"מה המילה באנגלית עבור \"שקיפות\"?","options":["transparency","spokesperson","outlet","censorship"],"correctIndex":0}', 9),
  ('media-communication', 'outlet', '{"prompt":"מה המילה באנגלית עבור \"כלי תקשורת\"?","options":["propaganda","outlet","credibility","coverage"],"correctIndex":1}', 10),
  ('economy-finance', 'inflation', '{"prompt":"מה המילה באנגלית עבור \"אינפלציה\"?","options":["inflation","recession","shareholder","subsidy"],"correctIndex":0}', 1),
  ('economy-finance', 'recession', '{"prompt":"מה המילה באנגלית עבור \"מיתון\"?","options":["unemployment","recession","fiscal","surplus"],"correctIndex":1}', 2),
  ('economy-finance', 'currency', '{"prompt":"מה המילה באנגלית עבור \"מטבע\"?","options":["monopoly","volatile","currency","recession"],"correctIndex":2}', 3),
  ('economy-finance', 'shareholder', '{"prompt":"מה המילה באנגלית עבור \"בעל מניות\"?","options":["inflation","currency","subsidy","shareholder"],"correctIndex":3}', 4),
  ('economy-finance', 'unemployment', '{"prompt":"מה המילה באנגלית עבור \"אבטלה\"?","options":["unemployment","shareholder","fiscal","surplus"],"correctIndex":0}', 5),
  ('economy-finance', 'subsidy', '{"prompt":"מה המילה באנגלית עבור \"סובסידיה\"?","options":["monopoly","subsidy","volatile","recession"],"correctIndex":1}', 6),
  ('economy-finance', 'fiscal', '{"prompt":"מה המילה באנגלית עבור \"פיסקלי, תקציבי\"?","options":["inflation","currency","fiscal","unemployment"],"correctIndex":2}', 7),
  ('economy-finance', 'monopoly', '{"prompt":"מה המילה באנגלית עבור \"מונופול\"?","options":["shareholder","subsidy","surplus","monopoly"],"correctIndex":3}', 8),
  ('economy-finance', 'surplus', '{"prompt":"מה המילה באנגלית עבור \"עודף\"?","options":["surplus","fiscal","volatile","recession"],"correctIndex":0}', 9),
  ('economy-finance', 'volatile', '{"prompt":"מה המילה באנגלית עבור \"תנודתי\"?","options":["inflation","volatile","currency","unemployment"],"correctIndex":1}', 10)
) as gen(topic_slug, headword, content, sort_order)
join public.topics t on t.slug = gen.topic_slug
join public.vocabulary_items v on v.topic_id = t.id and v.headword = gen.headword;

insert into public.exercises (type, skill_area, topic_id, cefr_level, content, sort_order)
select 'match'::exercise_type, 'vocabulary'::skill_area, t.id, t.cefr_level, gen.content::jsonb, gen.sort_order
from (values
  ('kitchen-cooking', '{"pairs":[{"left":"boil","right":"להרתיח"},{"left":"fry","right":"לטגן"},{"left":"bake","right":"לאפות"},{"left":"slice","right":"לפרוס"},{"left":"stir","right":"לערבב"}]}', 100),
  ('kitchen-cooking', '{"pairs":[{"left":"pan","right":"מחבת"},{"left":"oven","right":"תנור"},{"left":"recipe","right":"מתכון"},{"left":"ingredient","right":"מרכיב"},{"left":"taste","right":"לטעום"}]}', 101),
  ('nature-outdoors', '{"pairs":[{"left":"forest","right":"יער"},{"left":"river","right":"נהר"},{"left":"mountain","right":"הר"},{"left":"lake","right":"אגם"},{"left":"beach","right":"חוף ים"}]}', 100),
  ('nature-outdoors', '{"pairs":[{"left":"island","right":"אי"},{"left":"flower","right":"פרח"},{"left":"grass","right":"דשא"},{"left":"hill","right":"גבעה"},{"left":"desert","right":"מדבר"}]}', 101),
  ('work-office', '{"pairs":[{"left":"colleague","right":"עמית לעבודה"},{"left":"manager","right":"מנהל"},{"left":"meeting","right":"פגישה"},{"left":"salary","right":"משכורת"},{"left":"schedule","right":"לוח זמנים"}]}', 100),
  ('work-office', '{"pairs":[{"left":"contract","right":"חוזה"},{"left":"employee","right":"עובד"},{"left":"promotion","right":"קידום"},{"left":"resign","right":"להתפטר"},{"left":"task","right":"משימה"}]}', 101),
  ('money-banking', '{"pairs":[{"left":"account","right":"חשבון בנק"},{"left":"loan","right":"הלוואה"},{"left":"savings","right":"חסכונות"},{"left":"debt","right":"חוב"},{"left":"invest","right":"להשקיע"}]}', 100),
  ('money-banking', '{"pairs":[{"left":"withdraw","right":"למשוך (כסף)"},{"left":"afford","right":"להרשות לעצמו (כלכלית)"},{"left":"borrow","right":"ללוות"},{"left":"expense","right":"הוצאה"},{"left":"refund","right":"החזר כספי"}]}', 101),
  ('media-news', '{"pairs":[{"left":"headline","right":"כותרת"},{"left":"journalist","right":"עיתונאי"},{"left":"article","right":"כתבה, מאמר"},{"left":"broadcast","right":"לשדר"},{"left":"audience","right":"קהל"}]}', 100),
  ('media-news', '{"pairs":[{"left":"reporter","right":"כתב"},{"left":"rumor","right":"שמועה"},{"left":"source","right":"מקור"},{"left":"advertisement","right":"פרסומת"},{"left":"editor","right":"עורך"}]}', 101),
  ('relationships', '{"pairs":[{"left":"trust","right":"לסמוך על"},{"left":"argue","right":"להתווכח"},{"left":"apologize","right":"להתנצל"},{"left":"jealous","right":"מקנא"},{"left":"loyal","right":"נאמן"}]}', 100),
  ('relationships', '{"pairs":[{"left":"support","right":"לתמוך"},{"left":"partner","right":"בן או בת זוג"},{"left":"engaged","right":"מאורס"},{"left":"get along","right":"להסתדר עם"},{"left":"respect","right":"כבוד"}]}', 101),
  ('travel-planning', '{"pairs":[{"left":"itinerary","right":"מסלול טיול"},{"left":"passport","right":"דרכון"},{"left":"luggage","right":"מזוודות"},{"left":"reservation","right":"הזמנה מראש"},{"left":"destination","right":"יעד"}]}', 100),
  ('travel-planning', '{"pairs":[{"left":"departure","right":"יציאה, המראה"},{"left":"delay","right":"עיכוב"},{"left":"sightseeing","right":"סיור באתרים"},{"left":"accommodation","right":"מקום לינה"},{"left":"insurance","right":"ביטוח"}]}', 101),
  ('crime-law', '{"pairs":[{"left":"suspect","right":"חשוד"},{"left":"witness","right":"עד"},{"left":"trial","right":"משפט (בבית משפט)"},{"left":"jury","right":"חבר מושבעים"},{"left":"sentence","right":"גזר דין"}]}', 100),
  ('crime-law', '{"pairs":[{"left":"arrest","right":"לעצור"},{"left":"guilty","right":"אשם"},{"left":"victim","right":"קורבן"},{"left":"fraud","right":"הונאה"},{"left":"verdict","right":"פסק דין"}]}', 101),
  ('education-learning', '{"pairs":[{"left":"curriculum","right":"תוכנית לימודים"},{"left":"lecture","right":"הרצאה"},{"left":"assignment","right":"מטלה"},{"left":"scholarship","right":"מלגה"},{"left":"tuition","right":"שכר לימוד"}]}', 100),
  ('education-learning', '{"pairs":[{"left":"semester","right":"סמסטר"},{"left":"degree","right":"תואר אקדמי"},{"left":"graduate","right":"לסיים לימודים"},{"left":"literacy","right":"אוריינות"},{"left":"vocational","right":"מקצועי (הכשרה)"}]}', 101),
  ('urban-life', '{"pairs":[{"left":"congestion","right":"עומס תנועה"},{"left":"pedestrian","right":"הולך רגל"},{"left":"suburb","right":"פרבר"},{"left":"commute","right":"לנסוע לעבודה וממנה"},{"left":"residential","right":"מגורים (אזור)"}]}', 100),
  ('urban-life', '{"pairs":[{"left":"infrastructure","right":"תשתית"},{"left":"skyscraper","right":"גורד שחקים"},{"left":"neighborhood","right":"שכונה"},{"left":"crowded","right":"צפוף"},{"left":"affordable","right":"במחיר סביר"}]}', 101),
  ('politics-government', '{"pairs":[{"left":"parliament","right":"פרלמנט"},{"left":"legislation","right":"חקיקה"},{"left":"candidate","right":"מועמד"},{"left":"coalition","right":"קואליציה"},{"left":"referendum","right":"משאל עם"}]}', 100),
  ('politics-government', '{"pairs":[{"left":"accountable","right":"נושא באחריות"},{"left":"constituency","right":"אזור בחירה"},{"left":"veto","right":"להטיל וטו"},{"left":"bureaucracy","right":"ביורוקרטיה"},{"left":"sovereignty","right":"ריבונות"}]}', 101),
  ('media-communication', '{"pairs":[{"left":"propaganda","right":"תעמולה"},{"left":"censorship","right":"צנזורה"},{"left":"credibility","right":"אמינות"},{"left":"misinformation","right":"מידע שגוי"},{"left":"coverage","right":"סיקור"}]}', 100),
  ('media-communication', '{"pairs":[{"left":"editorial","right":"מאמר מערכת"},{"left":"spokesperson","right":"דובר"},{"left":"sensationalism","right":"סנסציוניות"},{"left":"transparency","right":"שקיפות"},{"left":"outlet","right":"כלי תקשורת"}]}', 101),
  ('economy-finance', '{"pairs":[{"left":"inflation","right":"אינפלציה"},{"left":"recession","right":"מיתון"},{"left":"currency","right":"מטבע"},{"left":"shareholder","right":"בעל מניות"},{"left":"unemployment","right":"אבטלה"}]}', 100),
  ('economy-finance', '{"pairs":[{"left":"subsidy","right":"סובסידיה"},{"left":"fiscal","right":"פיסקלי, תקציבי"},{"left":"monopoly","right":"מונופול"},{"left":"surplus","right":"עודף"},{"left":"volatile","right":"תנודתי"}]}', 101)
) as gen(topic_slug, content, sort_order)
join public.topics t on t.slug = gen.topic_slug;

insert into public.grammar_topics (slug, name_he, name_en, cefr_level, sort_order) values
  ('future-will', 'עתיד — will', 'Future: will', 'B1', 30),
  ('zero-conditional', 'משפט תנאי אפס', 'Zero Conditional', 'B1', 31),
  ('question-tags', 'שאלות זנב', 'Question Tags', 'B1', 32),
  ('participle-clauses', 'פסוקיות בינוני', 'Participle Clauses', 'C1', 33),
  ('nominalisation', 'נומינליזציה — שמות במקום פעלים', 'Nominalisation', 'C2', 34)
on conflict (slug) do update set
  name_he = excluded.name_he,
  name_en = excluded.name_en,
  cefr_level = excluded.cefr_level,
  sort_order = excluded.sort_order;

delete from public.grammar_lessons where grammar_topic_id in (select id from public.grammar_topics where slug in ('future-will', 'zero-conditional', 'question-tags', 'participle-clauses', 'nominalisation'));
delete from public.exercises where grammar_topic_id in (select id from public.grammar_topics where slug in ('future-will', 'zero-conditional', 'question-tags', 'participle-clauses', 'nominalisation'));

insert into public.grammar_lessons (grammar_topic_id, title_he, body_md, cefr_level, sort_order)
select gt.id, l.title_he, l.body_md, gt.cefr_level, 1
from public.grammar_topics gt
join (values
  ('future-will', 'עתיד עם will, ומתי going to', $$משתמשים ב-**will** + צורת בסיס כדי לדבר על העתיד, בעיקר במצבים האלה:

- **החלטה ברגע הדיבור:** The phone is ringing. I'll answer it.
- **תחזית או השערה:** I think it will rain tomorrow.
- **הבטחה או הצעה:** I'll help you with your homework.

**מבנה:**

- חיוב: I / you / she / we / they **will go** (בקיצור I'll, she'll)
- שלילה: **will not** = **won't**: I won't tell anyone.
- שאלה: **Will** + נושא + בסיס: Will you come with us?

**will או going to?**

| will | going to |
|---|---|
| החלטה עכשיו | תוכנית שכבר הוחלטה |
| I'll call her now. | I'm going to call her tonight. |
| תחזית לפי דעה | תחזית לפי מה שרואים |
| I think he'll win. | Look at the clouds. It's going to rain. |

**שימו לב:** אחרי will תמיד באה צורת בסיס, בלי to ובלי s: She will **go** (לא will goes, לא will to go).$$),
  ('zero-conditional', 'תנאי אפס — עובדות ותוצאות קבועות', $$משתמשים בתנאי אפס לדברים ש**תמיד** קורים כשמשהו מסוים קורה: עובדות, חוקי טבע, הרגלים.

**מבנה:** If + הווה פשוט, הווה פשוט

- If you heat ice, it **melts**.
- If I **drink** coffee at night, I **can't** sleep.
- If it **rains**, the roads **get** wet.

אפשר להחליף את **if** ב-**when** בלי לשנות את המשמעות: When you heat ice, it melts.

**סדר החלקים:** אפשר להתחיל בכל אחד מהם. כשהמשפט מתחיל ב-if, שמים פסיק באמצע:

- If you mix blue and yellow, you get green.
- You get green if you mix blue and yellow.

**ההבדל מתנאי ראשון:**

| תנאי אפס | תנאי ראשון |
|---|---|
| תמיד נכון | מצב אפשרי אחד בעתיד |
| If it rains, the grass gets wet. | If it rains tomorrow, we will stay home. |
| הווה + הווה | הווה + will |$$),
  ('question-tags', 'שאלות זנב — ..., isn''t it?', $$שאלת זנב היא שאלה קצרה בסוף משפט, שמבקשת אישור: "נכון?", "לא?".

**הכלל:** משפט חיובי → זנב שלילי. משפט שלילי → זנב חיובי.

- It's cold today, **isn't it**?
- You don't eat meat, **do you**?

**איך בונים:** לוקחים את פועל העזר מהמשפט (is, are, can, have, will...) וחוזרים עליו עם כינוי גוף.

- She **can** swim, **can't she**?
- They **have** finished, **haven't they**?
- He **will** come, **won't he**?

**אין פועל עזר?** בהווה פשוט ובעבר פשוט משתמשים ב-do / does / did:

- You **live** here, **don't you**?
- She **works** with you, **doesn't she**?
- They **went** home, **didn't they**?

**מקרים מיוחדים:**

- I am late, **aren't I**? (לא amn't I)
- Let's go, **shall we**?

**בדיבור:** כשהקול יורד בזנב, מבקשים הסכמה. כשהוא עולה, באמת שואלים.$$),
  ('participle-clauses', 'פסוקיות בינוני — כתיבה תמציתית', $$פסוקית בינוני מקצרת משפט בעזרת צורת **-ing** או צורת **V3** (past participle), במקום פסוקית מלאה עם נושא ופועל. זה נפוץ בכתיבה רשמית, אקדמית ועיתונאית.

**פעולה בו-זמנית או סיבה: -ing:**

- **Feeling** tired, she went to bed early. (= Because she felt tired...)
- **Walking** home, I met an old friend. (= While I was walking home...)

**פעולה שקדמה: Having + V3:**

- **Having finished** the report, he sent it to his manager. (= After he had finished...)

**משמעות סבילה: V3:**

- **Built** in 1920, the house needs major repairs. (= Because it was built in 1920...)
- **Asked** about the delay, the minister refused to comment.

**כלל חשוב: אותו נושא:** הנושא של הפסוקית חייב להיות הנושא של המשפט הראשי.

- ✗ Walking down the street, the rain started. (הגשם לא הלך ברחוב)
- ✓ Walking down the street, I felt the rain start.

**בתוך שם עצם:** אפשר לקצר גם פסוקית זיקה:

- The man **sitting** by the window is my uncle. (= who is sitting)
- Most of the products **sold** online are delivered within a week. (= that are sold)$$),
  ('nominalisation', 'נומינליזציה — סגנון אקדמי ורשמי', $$נומינליזציה היא הפיכת פועל או תואר ל**שם עצם**, כדי לכתוב בצורה רשמית, אובייקטיבית ודחוסה יותר. זה אחד הסימנים הבולטים של כתיבה אקדמית ברמה גבוהה.

**לפני ואחרי:**

- The government **decided** to raise taxes, and people **reacted** angrily.
- → The government's **decision** to raise taxes provoked an angry **reaction**.

- Prices **rose** quickly, which **worried** investors.
- → The rapid **rise** in prices caused **concern** among investors.

**סיומות נפוצות:**

| פועל / תואר | שם עצם |
|---|---|
| analyze | analysis |
| fail | failure |
| expand | expansion |
| able | ability |
| refuse | refusal |
| develop | development |

**למה זה עובד:**

- מעביר את המוקד מ**מי** עשה ל**מה** קרה.
- מאפשר לדחוס רעיון שלם לשם עצם אחד ולהשתמש בו כנושא: **This expansion** led to...

**זהירות:** עודף נומינליזציה הופך טקסט לכבד וקשה לקריאה. בכתיבה טובה משלבים: שמות עצם לרעיונות המרכזיים, ופעלים חיים לפעולה.$$)
) as l(slug, title_he, body_md) on gt.slug = l.slug;

insert into public.exercises (type, skill_area, grammar_topic_id, cefr_level, content, sort_order)
select 'fill_blank'::exercise_type, 'grammar'::skill_area, gt.id, gt.cefr_level, gen.content::jsonb, gen.sort_order
from (values
  ('future-will', '{"sentence":"It''s cold in here. I ___ close the window.","correctAnswer":"will","hint":"decision now"}', 1),
  ('future-will', '{"sentence":"I promise I ___ be late again.","correctAnswer":"won''t","hint":"negative of will"}', 2),
  ('future-will', '{"sentence":"Do you think she ___ pass the exam?","correctAnswer":"will","hint":"prediction"}', 3),
  ('future-will', '{"sentence":"We have already bought the tickets. We are ___ to fly to Rome.","correctAnswer":"going","hint":"a plan already decided"}', 4),
  ('future-will', '{"sentence":"___ you help me carry these bags?","correctAnswer":"Will","hint":"request"}', 5),
  ('zero-conditional', '{"sentence":"If you ___ water to 100 degrees, it boils.","correctAnswer":"heat","hint":"present simple"}', 1),
  ('zero-conditional', '{"sentence":"If people don''t sleep enough, they ___ tired.","correctAnswer":"get","hint":"present simple"}', 2),
  ('zero-conditional', '{"sentence":"Plants die if they ___ get water.","correctAnswer":"don''t","hint":"negative, present simple"}', 3),
  ('zero-conditional', '{"sentence":"___ I''m stressed, I go for a walk.","correctAnswer":"When","hint":"same meaning as if"}', 4),
  ('zero-conditional', '{"sentence":"If you press this button, the machine ___.","correctAnswer":"stops","hint":"he/she/it form"}', 5),
  ('question-tags', '{"sentence":"It''s a beautiful day, ___ it?","correctAnswer":"isn''t","hint":"positive sentence, negative tag"}', 1),
  ('question-tags', '{"sentence":"You don''t like horror films, ___ you?","correctAnswer":"do","hint":"negative sentence, positive tag"}', 2),
  ('question-tags', '{"sentence":"She works in a bank, ___ she?","correctAnswer":"doesn''t","hint":"present simple, he/she"}', 3),
  ('question-tags', '{"sentence":"They went to the concert, ___ they?","correctAnswer":"didn''t","hint":"past simple"}', 4),
  ('question-tags', '{"sentence":"You can drive, ___ you?","correctAnswer":"can''t","hint":"repeat the modal"}', 5),
  ('participle-clauses', '{"sentence":"___ finished her degree, she moved to Berlin.","correctAnswer":"Having","hint":"the earlier action"}', 1),
  ('participle-clauses', '{"sentence":"___ in 1889, the tower is now a symbol of Paris.","correctAnswer":"Built","hint":"passive meaning"}', 2),
  ('participle-clauses', '{"sentence":"Not ___ what to say, he stayed silent.","correctAnswer":"knowing","hint":"reason, -ing"}', 3),
  ('participle-clauses', '{"sentence":"The students ___ the exam early may leave.","correctAnswer":"finishing","hint":"who finish"}', 4),
  ('participle-clauses', '{"sentence":"___ by the results, the team decided to continue the study.","correctAnswer":"Encouraged","hint":"passive: they were encouraged"}', 5),
  ('nominalisation', '{"sentence":"The company''s rapid ___ (expand) surprised its competitors.","correctAnswer":"expansion","hint":"noun from expand"}', 1),
  ('nominalisation', '{"sentence":"Her ___ (refuse) to comment made the story bigger.","correctAnswer":"refusal","hint":"noun from refuse"}', 2),
  ('nominalisation', '{"sentence":"A careful ___ (analyze) of the data showed a clear trend.","correctAnswer":"analysis","hint":"noun from analyze"}', 3),
  ('nominalisation', '{"sentence":"The project''s ___ (fail) was blamed on poor planning.","correctAnswer":"failure","hint":"noun from fail"}', 4),
  ('nominalisation', '{"sentence":"The ___ (able) to adapt is essential for leaders.","correctAnswer":"ability","hint":"noun from able"}', 5)
) as gen(slug, content, sort_order)
join public.grammar_topics gt on gt.slug = gen.slug;

insert into public.exercises (type, skill_area, grammar_topic_id, cefr_level, content, sort_order)
select 'reorder'::exercise_type, 'grammar'::skill_area, gt.id, gt.cefr_level, gen.content::jsonb, gen.sort_order
from (values
  ('future-will', '{"tokens":["I","think","it","will","be","sunny","tomorrow"],"correctOrder":[0,1,2,3,4,5,6]}', 100),
  ('future-will', '{"tokens":["She","won''t","forget","your","birthday"],"correctOrder":[0,1,2,3,4]}', 101),
  ('zero-conditional', '{"tokens":["If","you","mix","red","and","white,","you","get","pink"],"correctOrder":[0,1,2,3,4,5,6,7,8]}', 100),
  ('zero-conditional', '{"tokens":["Ice","melts","if","you","leave","it","in","the","sun"],"correctOrder":[0,1,2,3,4,5,6,7,8]}', 101),
  ('question-tags', '{"tokens":["You","are","coming","tonight,","aren''t","you?"],"correctOrder":[0,1,2,3,4,5]}', 100),
  ('question-tags', '{"tokens":["He","hasn''t","called","yet,","has","he?"],"correctOrder":[0,1,2,3,4,5]}', 101),
  ('participle-clauses', '{"tokens":["Having","read","the","contract,","she","refused","to","sign","it"],"correctOrder":[0,1,2,3,4,5,6,7,8]}', 100),
  ('participle-clauses', '{"tokens":["Founded","in","1998,","the","company","now","employs","thousands"],"correctOrder":[0,1,2,3,4,5,6,7]}', 101),
  ('nominalisation', '{"tokens":["The","introduction","of","the","tax","led","to","widespread","protests"],"correctOrder":[0,1,2,3,4,5,6,7,8]}', 100),
  ('nominalisation', '{"tokens":["Their","rejection","of","the","offer","came","as","a","surprise"],"correctOrder":[0,1,2,3,4,5,6,7,8]}', 101)
) as gen(slug, content, sort_order)
join public.grammar_topics gt on gt.slug = gen.slug;

insert into public.writing_prompts (title_he, prompt_en, cefr_level, sort_order)
select w.title_he, w.prompt_en, w.lvl::cefr_level, w.sort_order
from (values
  ('החדר שלי', 'Describe your room in 3-5 sentences. What is in it? What color is it?', 'A1', 10),
  ('האוכל שאני אוהב', 'Write 3-5 sentences about food you like and food you don''t like.', 'A1', 11),
  ('הודעה לחבר', 'Write a short message to a friend inviting them to your birthday. Say when, where and what you will do.', 'A2', 12),
  ('סוף שבוע שעבר', 'Write about what you did last weekend. Use at least four verbs in the past.', 'A2', 13),
  ('חוויה מטיול', 'Write about a trip you remember well. Where did you go, what happened, and how did you feel?', 'B1', 14),
  ('מייל לבקשת מידע', 'Write an email to a language school asking about their summer courses: dates, price and level.', 'B1', 15),
  ('בעד ונגד: עבודה מהבית', 'What are the advantages and disadvantages of working from home? Give at least two of each.', 'B1', 16),
  ('מכתב תלונה', 'You bought a product online and it arrived broken. Write a formal complaint and say what you expect the company to do.', 'B2', 17),
  ('האם צריך לבטל שיעורי בית?', 'Should schools stop giving homework? Write a short essay with a clear opinion, two reasons and an example.', 'B2', 18),
  ('סקירת סרט או ספר', 'Write a review of a film or book you enjoyed. Describe it briefly and explain who would like it and why.', 'B2', 19),
  ('מאמר דעה: בינה מלאכותית בחינוך', 'Write an opinion article on whether AI tools help or harm students'' learning. Consider both sides before giving your view.', 'C1', 20),
  ('הצעה לשיפור בעיר', 'Write a proposal to your local council suggesting one change that would improve life in your city. Explain the problem, your solution and its cost.', 'C1', 21),
  ('השוואת שני מקומות', 'Compare life in a big city with life in a small town. Which would you choose at this stage of your life, and why?', 'C1', 22),
  ('מאמר: האם הטכנולוגיה מבודדת?', 'Discuss the claim that digital technology has made people more connected but lonelier. Use precise examples and address a counter-argument.', 'C2', 23),
  ('נאום קצר', 'Write a short speech for a graduation ceremony. Aim for a tone that is personal, persuasive and memorable.', 'C2', 24),
  ('ניתוח החלטה', 'Describe a difficult decision a public figure or organization made. Analyze the trade-offs and argue whether it was the right call.', 'C2', 25)
) as w(title_he, prompt_en, lvl, sort_order)
where not exists (select 1 from public.writing_prompts p where p.prompt_en = w.prompt_en);

insert into public.conversation_scenarios (slug, title_he, title_en, system_prompt, cefr_level, category, sort_order) values
  ('policy-debate', 'דיון על מדיניות ציבורית', 'Debating a Public Policy', 'You are a well-informed debate partner. Pick a current public-policy question with the user (for example public transport, housing or screen time for children), take the opposite side of their view, and challenge their arguments politely with counter-examples. Push for precise reasoning.', 'C1', 'serious_topics', 200),
  ('job-offer-counter', 'משא ומתן מתקדם על תנאים', 'Counter-Offering on a Senior Role', 'You are a director negotiating a senior job offer with the user. Be professional and somewhat firm: discuss salary, remote work, title and start date. Make them justify each request and look for trade-offs rather than simply agreeing.', 'C1', 'work_professional', 201),
  ('research-presentation-qa', 'שאלות אחרי הצגת מחקר', 'Q&A After a Research Talk', 'You are an audience member after the user''s short research presentation. First ask what their research is about, then ask sharp but fair follow-up questions about their method, their evidence and the limits of their conclusions.', 'C1', 'academic', 202),
  ('difficult-feedback', 'לתת משוב קשה', 'Giving Difficult Feedback', 'You are an employee who reports to the user. Your recent work has had problems, and the user needs to give you honest feedback. React realistically: at first a little defensive, then open to a plan if the user is clear and respectful.', 'C1', 'work_professional', 203),
  ('ethics-dilemma', 'דילמה מוסרית', 'An Ethical Dilemma', 'You are a thoughtful friend discussing an ethical dilemma with the user, such as whether to report a colleague''s mistake or whether it is ever right to break a promise. Ask probing questions, offer different moral perspectives, and avoid preaching.', 'C1', 'serious_topics', 204),
  ('crisis-press-conference', 'מסיבת עיתונאים במשבר', 'A Crisis Press Conference', 'You are a tough journalist at a press conference. The user is the spokesperson for an organization facing a crisis they describe. Ask pointed, sometimes uncomfortable questions, follow up when answers are vague, and stay professional.', 'C2', 'work_professional', 205),
  ('philosophy-cafe', 'בית קפה פילוסופי', 'A Philosophy Café', 'You are a fellow participant in a philosophy café. Explore an abstract question with the user, such as what makes a life meaningful or whether free will exists. Use nuanced language, introduce relevant ideas, and build on the user''s points rather than lecturing.', 'C2', 'serious_topics', 206),
  ('literary-discussion', 'דיון ספרותי מעמיק', 'An In-Depth Book Discussion', 'You are a well-read friend discussing a novel the user chooses. Discuss themes, character motivation, style and how the book has aged. Share your own interpretation and invite disagreement.', 'C2', 'entertainment_culture', 207),
  ('board-pitch', 'הצגת הצעה לדירקטוריון', 'Pitching to a Board', 'You are the chair of a company board. The user is pitching a major proposal (they decide what it is). Ask demanding questions about risk, cost, timing and evidence, as a sceptical but fair board member would.', 'C2', 'work_professional', 208)
on conflict (slug) do update set
  title_he = excluded.title_he,
  title_en = excluded.title_en,
  system_prompt = excluded.system_prompt,
  cefr_level = excluded.cefr_level,
  category = excluded.category,
  sort_order = excluded.sort_order;
