-- Reading and listening for B1–C2 (generated by
-- scripts/generate-reading-listening.mjs from
-- scripts/content/readingListening.mjs — edit the content there).
-- 3 original reading texts (6 MCQ + 2 open questions each) and
-- 3 full-length listening clips (3 MCQ + 1 dictation each).
-- Safe to re-run: rows with these titles are deleted first; their
-- exercises and open questions cascade.

delete from public.reading_texts where title_en in ('A New Neighbour', 'My First Job', 'A Day Without a Phone');
delete from public.listening_clips where title_en in ('At the Train Station', 'Buying a Birthday Present', 'A Message from School');

insert into public.reading_texts (title_he, title_en, body_en, cefr_level, sort_order) values
  ('שכנה חדשה', 'A New Neighbour', 'Last month, a new family moved into the apartment next to ours. On the first day, I saw a woman carrying many boxes up the stairs. The elevator in our building was broken, so I asked if she needed help. Her name was Rina, and she was very happy to get some help.

We carried boxes together for almost an hour. Rina told me that she came from a small town in the north and that this was her first time living in a big city. She was a little worried because she did not know anyone here. Her son, Eli, was eight years old, and he was starting at a new school the next week.

The next evening, I knocked on their door with a cake that my mother made. Rina invited me in for tea. Eli showed me his drawings of trains and asked me a lot of questions about the city. He wanted to know where the nearest park was and if there was a library nearby.

Now we meet almost every weekend. Sometimes I take Eli to the park with my little sister, and Rina and I drink coffee on the balcony. She says the city does not feel so big anymore.', 'A2', 100),
  ('העבודה הראשונה שלי', 'My First Job', 'When I was sixteen, I got my first job at an ice cream shop near the beach. I worked there every summer afternoon from three o''clock until nine. I wanted to earn money to buy a new bicycle.

The first week was difficult. There were twenty-four flavours, and I always forgot where each one was. Once, a customer asked for mint and I gave him pistachio, because they are both green. He laughed and said he liked pistachio too, so it was fine.

My manager, Yoni, was patient with me. He showed me how to hold the scoop and how to make the ice cream look nice in the cone. He also told me to always smile, even when the shop was very busy and there was a long line of hot, tired people.

The busiest days were Fridays. Sometimes I served more than a hundred customers in one afternoon, and my arm hurt at the end of the day. But I liked talking to people, especially to the children who could not decide which flavour to choose.

At the end of the summer, I had enough money for the bicycle. I still ride it today, and every time I pass an ice cream shop, I remember that summer.', 'A2', 101),
  ('יום בלי טלפון', 'A Day Without a Phone', 'Last Saturday, I left my phone at my friend''s house by mistake. At first I was a bit nervous. How could I check the time, the weather or my messages? I decided to try a whole day without it.

In the morning, I looked out of the window to check the weather instead of looking at an app. It was sunny, so I walked to the market. Usually I listen to music on my phone when I walk, but this time I listened to the birds and the people talking in the street. It was more interesting than I expected.

At the market, I bought vegetables and some fresh bread. I did not take any photos of the food, which is strange for me. I just enjoyed it. In the afternoon, I read half of a book that I started months ago and never finished.

In the evening, I visited my friend to get my phone back. There were fourteen new messages, but none of them were important. That night, I went to sleep earlier than usual and slept very well. Now I try to have one morning every week without my phone.', 'A2', 102);

insert into public.exercises (type, skill_area, reading_text_id, cefr_level, content, sort_order)
select 'mcq'::exercise_type, 'reading'::skill_area, rt.id, rt.cefr_level, gen.content::jsonb, gen.sort_order
from public.reading_texts rt
join (values
  ('A New Neighbour', '{"prompt":"Why did the writer offer to help Rina?","options":["The elevator was broken","Rina was the writer''s friend","The writer''s mother asked them to","Rina asked for help"],"correctIndex":0}', 1),
  ('A New Neighbour', '{"prompt":"Where did Rina live before?","options":["In another big city","In a small town in the north","In the same building","Abroad"],"correctIndex":1}', 2),
  ('A New Neighbour', '{"prompt":"What did the writer bring the next evening?","options":["Flowers","A drawing","A cake","A book"],"correctIndex":2}', 3),
  ('A New Neighbour', '{"prompt":"What did Eli want to know?","options":["When school starts","How to draw trains","Where the writer works","Where the nearest park and library were"],"correctIndex":3}', 4),
  ('A New Neighbour', '{"prompt":"How does Rina feel about the city now?","options":["It does not feel so big anymore","She is worried about her son","She wants to leave","It still feels very big"],"correctIndex":0}', 5),
  ('My First Job', '{"prompt":"Why did the writer want a job?","options":["To buy a new bicycle","To meet new friends","To learn about ice cream","To help the family"],"correctIndex":0}', 1),
  ('My First Job', '{"prompt":"What mistake did the writer make with a customer?","options":["Gave the wrong change","Gave pistachio instead of mint","Forgot the cone","Closed the shop early"],"correctIndex":1}', 2),
  ('My First Job', '{"prompt":"What did Yoni teach the writer?","options":["How to count money","How to make new flavours","How to hold the scoop and serve nicely","How to clean the shop"],"correctIndex":2}', 3),
  ('My First Job', '{"prompt":"Why did the writer''s arm hurt on Fridays?","options":["They carried heavy boxes","They rode the bicycle to work","They fell in the shop","They served many customers"],"correctIndex":3}', 4),
  ('My First Job', '{"prompt":"What did the writer enjoy most about the job?","options":["Talking to people, especially children","Working on Fridays","Working near the beach","The free ice cream"],"correctIndex":0}', 5),
  ('A Day Without a Phone', '{"prompt":"Why didn''t the writer have a phone on Saturday?","options":["They left it at a friend''s house","They lost it at the market","They gave it to their friend","It was broken"],"correctIndex":0}', 1),
  ('A Day Without a Phone', '{"prompt":"How did the writer check the weather?","options":["They asked a neighbour","They looked out of the window","They used an app","They listened to the radio"],"correctIndex":1}', 2),
  ('A Day Without a Phone', '{"prompt":"What did the writer listen to on the way to the market?","options":["Music","A podcast","Birds and people in the street","The news"],"correctIndex":2}', 3),
  ('A Day Without a Phone', '{"prompt":"What did the writer do in the afternoon?","options":["Called a friend","Took photos","Went shopping again","Read half of a book"],"correctIndex":3}', 4),
  ('A Day Without a Phone', '{"prompt":"What new habit does the writer have now?","options":["One morning a week without the phone","No phone on weekends","Going to the market every day","Reading every evening"],"correctIndex":0}', 5)
) as gen(title_en, content, sort_order)
  on rt.title_en = gen.title_en;

insert into public.reading_open_questions (reading_text_id, question_en, sort_order)
select rt.id, gen.question_en, gen.sort_order
from public.reading_texts rt
join (values
  ('A New Neighbour', 'How did the writer and Rina become friends? Describe what happened in order.', 1),
  ('A New Neighbour', 'How do you welcome new people in your neighbourhood, school or work?', 2),
  ('My First Job', 'Describe the writer''s first week at work. What was difficult, and who helped?', 1),
  ('My First Job', 'Write about your first job or a job you would like to have. Why?', 2),
  ('A Day Without a Phone', 'What did the writer notice during the day without a phone?', 1),
  ('A Day Without a Phone', 'Could you spend a day without your phone? What would be easy, and what would be hard?', 2)
) as gen(title_en, question_en, sort_order)
  on rt.title_en = gen.title_en;

insert into public.listening_clips (title_he, title_en, transcript_en, cefr_level, style, sort_order) values
  ('בתחנת הרכבת', 'At the Train Station', 'Excuse me, is this the right platform for the train to Haifa? Yes, it''s platform three, but the next train is late. It leaves at ten forty, not ten fifteen. Oh no. Is there a café here? Yes, there''s one near the main entrance, next to the ticket machines. Thank you. And how long is the trip to Haifa? About one hour and a half. Great, thanks for your help. You''re welcome. Have a good trip.', 'A2', 'standard', 100),
  ('קונים מתנת יום הולדת', 'Buying a Birthday Present', 'Hi, can I help you? Yes, I''m looking for a present for my brother. He''s turning fifteen. What does he like? He loves football and music. We have these headphones. They''re very popular with teenagers. How much are they? They''re two hundred shekels. Hmm, that''s a bit expensive. Do you have something cheaper? This football shirt is one hundred and twenty. Which team is it? It''s the national team. Perfect, he''ll love it. Can you wrap it for me? Of course.', 'A2', 'standard', 101),
  ('הודעה מבית הספר', 'A Message from School', 'Good afternoon, parents. This is a message from the school office. Tomorrow, Thursday, the school trip to the science museum will start at eight in the morning. Please make sure your children arrive at school by seven forty-five. They need to bring a packed lunch and a bottle of water. The bus will bring everyone back to school at three o''clock. If your child cannot come, please call the office before tomorrow morning. Thank you, and have a good day.', 'A2', 'standard', 102);

insert into public.exercises (type, skill_area, listening_clip_id, cefr_level, content, sort_order)
select 'mcq'::exercise_type, 'listening'::skill_area, lc.id, lc.cefr_level, gen.content::jsonb, gen.sort_order
from public.listening_clips lc
join (values
  ('At the Train Station', '{"prompt":"Which platform does the train to Haifa leave from?","options":["Platform two","Platform three","Platform four","Platform one"],"correctIndex":1}', 2),
  ('At the Train Station', '{"prompt":"What time does the train leave now?","options":["Ten thirty","Ten fifteen","Ten forty","Eleven o''clock"],"correctIndex":2}', 3),
  ('At the Train Station', '{"prompt":"Where is the café?","options":["Outside the station","On the train","On platform three","Near the main entrance, next to the ticket machines"],"correctIndex":3}', 4),
  ('Buying a Birthday Present', '{"prompt":"How old is the brother turning?","options":["Fourteen","Fifteen","Sixteen","Twelve"],"correctIndex":1}', 2),
  ('Buying a Birthday Present', '{"prompt":"Why doesn''t the customer buy the headphones?","options":["They are broken","Her brother has headphones","They are too expensive","They are not popular"],"correctIndex":2}', 3),
  ('Buying a Birthday Present', '{"prompt":"What does the customer buy?","options":["A music album","A football","Headphones","A football shirt"],"correctIndex":3}', 4),
  ('A Message from School', '{"prompt":"Where are the children going tomorrow?","options":["To the zoo","To the science museum","To the beach","To a park"],"correctIndex":1}', 2),
  ('A Message from School', '{"prompt":"What time should children arrive at school?","options":["Eight fifteen","Seven thirty","Seven forty-five","Eight o''clock"],"correctIndex":2}', 3),
  ('A Message from School', '{"prompt":"What should the children bring?","options":["A camera","Their school books","Money for lunch","A packed lunch and a bottle of water"],"correctIndex":3}', 4)
) as gen(title_en, content, sort_order)
  on lc.title_en = gen.title_en;

insert into public.exercises (type, skill_area, listening_clip_id, cefr_level, content, sort_order)
select 'dictation'::exercise_type, 'listening'::skill_area, lc.id, lc.cefr_level, gen.content::jsonb, 1
from public.listening_clips lc
join (values
  ('At the Train Station', '{"audioText":"The next train is late.","correctAnswer":"The next train is late."}'),
  ('Buying a Birthday Present', '{"audioText":"I''m looking for a present for my brother.","correctAnswer":"I''m looking for a present for my brother."}'),
  ('A Message from School', '{"audioText":"They need to bring a packed lunch.","correctAnswer":"They need to bring a packed lunch."}')
) as gen(title_en, content)
  on lc.title_en = gen.title_en;

-- ============ Idioms and phrasal verbs ============
delete from public.idioms_phrasal_verbs where phrase in ('cut corners', 'the elephant in the room', 'play it by ear', 'iron out', 'fall through', 'a double-edged sword', 'to split hairs', 'to toe the line', 'a moot point', 'to pay lip service to', 'the thin end of the wedge', 'gloss over', 'bow out');
insert into public.idioms_phrasal_verbs (phrase, type, meaning_he, example_en, cefr_level, sort_order) values
  ('cut corners', 'idiom', 'לעשות עבודה חפיפית כדי לחסוך זמן או כסף', 'The builders cut corners, and now the roof leaks.', 'C1', 200),
  ('the elephant in the room', 'idiom', 'נושא בעייתי ברור שכולם נמנעים מלדבר עליו', 'The budget cuts were the elephant in the room during the meeting.', 'C1', 201),
  ('play it by ear', 'idiom', 'לאלתר, להחליט תוך כדי לפי המצב', 'We don''t have a plan for tomorrow, so let''s play it by ear.', 'C1', 202),
  ('iron out', 'phrasal_verb', 'ליישב, לפתור בעיות קטנות אחרונות', 'We still need to iron out a few details before we sign.', 'C1', 203),
  ('fall through', 'phrasal_verb', 'להתבטל, לא לצאת לפועל', 'The deal fell through at the last minute.', 'C1', 204),
  ('a double-edged sword', 'idiom', 'משהו שיש לו גם יתרונות וגם חסרונות משמעותיים', 'Fame can be a double-edged sword.', 'C2', 205),
  ('to split hairs', 'idiom', 'להתווכח על הבדלים זניחים, לדקדק בקטנות', 'We agree on the main point, so let''s not split hairs over the wording.', 'C2', 206),
  ('to toe the line', 'idiom', 'לציית לכללים או לעמדה הרשמית', 'Junior staff were expected to toe the line and not question decisions.', 'C2', 207),
  ('a moot point', 'idiom', 'שאלה שכבר לא רלוונטית או שאין טעם להתווכח עליה', 'Whether we could have won is a moot point now.', 'C2', 208),
  ('to pay lip service to', 'idiom', 'לתמוך במשהו רק במילים, בלי מעשים', 'The company pays lip service to equality but changes nothing.', 'C2', 209),
  ('the thin end of the wedge', 'idiom', 'צעד קטן שעלול להוביל לשינוי גדול ושלילי', 'Some see the new fee as the thin end of the wedge.', 'C2', 210),
  ('gloss over', 'phrasal_verb', 'להתעלם מבעיה או להציג אותה כפחות חמורה', 'The report glosses over the main risks.', 'C2', 211),
  ('bow out', 'phrasal_verb', 'לפרוש בצורה מכובדת מתפקיד או מתחרות', 'After twenty years, she decided to bow out gracefully.', 'C2', 212);
