-- 031_grammar_set_2 (generated by scripts/generate-grammar.mjs from
-- scripts/content/grammarSet2.mjs; edit the content there, not here).
-- 18 new grammar topics (A1: 4, A2: 3, B1: 4, B2: 4, C1: 2, C2: 1), each with a lesson,
-- fill-in practice and word-order practice. All content is original.
-- Safe to re-run: topics are upserted by slug, and their lessons and
-- exercises are cleared and reinserted.

insert into public.grammar_topics (slug, name_he, name_en, cefr_level, sort_order) values
  ('there-is-there-are', 'there is / there are', 'There is / There are', 'A1', 35),
  ('imperatives', 'ציווי', 'Imperatives', 'A1', 36),
  ('object-pronouns', 'כינויי מושא', 'Object Pronouns', 'A1', 37),
  ('question-words', 'מילות שאלה', 'Question Words', 'A1', 38),
  ('adverbs-of-frequency', 'תדירות: always, usually, never', 'Adverbs of Frequency', 'A2', 39),
  ('possessive-s', 'שייכות: ''s', 'Possessive ''s', 'A2', 40),
  ('have-to', 'have to / don''t have to', 'Have to / Don''t have to', 'A2', 41),
  ('present-perfect-vs-past-simple', 'הווה מושלם מול עבר פשוט', 'Present Perfect vs Past Simple', 'B1', 42),
  ('verb-gerund-or-infinitive', 'פועל + ing או פועל + to', 'Verb + -ing or to', 'B1', 43),
  ('may-might-possibility', 'אולי: may ו-might', 'May and Might (Possibility)', 'B1', 44),
  ('so-such', 'so ו-such', 'So and Such', 'B1', 45),
  ('present-perfect-continuous', 'הווה מושלם מתמשך', 'Present Perfect Continuous', 'B2', 46),
  ('wish-if-only', 'wish ו-if only', 'Wish and If only', 'B2', 47),
  ('causative-have-get', 'have something done', 'Causative: have / get something done', 'B2', 48),
  ('future-continuous-perfect', 'עתיד מתמשך ועתיד מושלם', 'Future Continuous and Future Perfect', 'B2', 49),
  ('concession-although-despite', 'ניגוד: although ו-despite', 'Concession: although, despite, however', 'C1', 50),
  ('would-rather-had-better', 'would rather ו-had better', 'Would rather and Had better', 'C1', 51),
  ('ellipsis-substitution', 'השמטה והחלפה', 'Ellipsis and Substitution', 'C2', 52)
on conflict (slug) do update set
  name_he = excluded.name_he,
  name_en = excluded.name_en,
  cefr_level = excluded.cefr_level,
  sort_order = excluded.sort_order;

delete from public.grammar_lessons where grammar_topic_id in (select id from public.grammar_topics where slug in ('there-is-there-are', 'imperatives', 'object-pronouns', 'question-words', 'adverbs-of-frequency', 'possessive-s', 'have-to', 'present-perfect-vs-past-simple', 'verb-gerund-or-infinitive', 'may-might-possibility', 'so-such', 'present-perfect-continuous', 'wish-if-only', 'causative-have-get', 'future-continuous-perfect', 'concession-although-despite', 'would-rather-had-better', 'ellipsis-substitution'));
delete from public.exercises where grammar_topic_id in (select id from public.grammar_topics where slug in ('there-is-there-are', 'imperatives', 'object-pronouns', 'question-words', 'adverbs-of-frequency', 'possessive-s', 'have-to', 'present-perfect-vs-past-simple', 'verb-gerund-or-infinitive', 'may-might-possibility', 'so-such', 'present-perfect-continuous', 'wish-if-only', 'causative-have-get', 'future-continuous-perfect', 'concession-although-despite', 'would-rather-had-better', 'ellipsis-substitution'));

insert into public.grammar_lessons (grammar_topic_id, title_he, body_md, cefr_level, sort_order)
select gt.id, l.title_he, l.body_md, gt.cefr_level, 1
from public.grammar_topics gt
join (values
  ('there-is-there-are', 'יש / אין: there is ו-there are', $$כדי להגיד ש**יש** משהו במקום מסוים, משתמשים ב-**there is** וב-**there are**.

- **there is** + יחיד או בלתי ספיר: There is a cat in the garden. There is milk in the fridge.
- **there are** + רבים: There are three books on the table.

**בקיצור:** there is = **there's**. את there are בדרך כלל לא מקצרים בכתיבה.

**שלילה:**

- There **isn't** a bank near here.
- There **aren't any** chairs in the room.

**שאלה:** הופכים את הסדר.

- **Is there** a pharmacy on this street? Yes, there is. / No, there isn't.
- **Are there** any eggs? Yes, there are. / No, there aren't.

**שימו לב:** בעברית אומרים "יש לי" על משהו ששייך לנו. באנגלית זה **I have**, לא there is: I have a car (לא There is me a car).$$),
  ('imperatives', 'ציווי: הוראות, בקשות ואזהרות', $$צורת הציווי באנגלית היא פשוט **צורת הבסיס** של הפועל, בלי נושא. היא אותה צורה לאדם אחד ולכמה אנשים.

- **Open** the window, please.
- **Sit** down.
- **Turn** left at the lights.

**שלילה:** **Don't** + בסיס.

- **Don't** touch that. It's hot.
- **Don't** be late.

**ציווי שכולל גם אותנו:** **Let's** + בסיס.

- **Let's** go to the beach.
- **Let's not** wait for the bus. Let's walk.

**כדי שזה יישמע מנומס,** מוסיפים please בהתחלה או בסוף: Please close the door. / Close the door, please.

**שימו לב:** אין to אחרי don't ו-let's: Don't **run** (לא Don't to run).$$),
  ('object-pronouns', 'כינויי מושא: me, him, her, us, them', $$כשמישהו **מקבל** את הפעולה (אחרי הפועל או אחרי מילת יחס), משתמשים בכינוי מושא ולא בכינוי נושא.

| נושא | מושא |
|---|---|
| I | me |
| you | you |
| he | him |
| she | her |
| it | it |
| we | us |
| they | them |

- She loves **him**. (לא She loves he)
- Can you help **me**?
- I'm waiting for **them**.
- This present is for **you**.

**הכלל:** לפני הפועל (מי שעושה) = I, he, she, we, they. אחרי הפועל או אחרי for, with, to, at = me, him, her, us, them.

**שימו לב:** בעברית אומרים "אוהב אותה". באנגלית אין מילה ל"את": I love **her**.$$),
  ('question-words', 'מילות שאלה: what, where, when, who, why, how', $$שאלה עם מילת שאלה בנויה כך: **מילת שאלה + פועל עזר + נושא + פועל**.

- **What** do you do? (מה)
- **Where** do you live? (איפה)
- **When** does the film start? (מתי)
- **Who** is that woman? (מי)
- **Why** are you sad? (למה)
- **How** do you go to work? (איך)

**צירופים עם how:**

- **How old** are you? (בן או בת כמה)
- **How much** is this? (כמה זה עולה)
- **How many** brothers do you have? (כמה, עם רבים)
- **How often** do you swim? (באיזו תדירות)

**עם to be** אין פועל עזר נוסף: Where **is** the station? Who **are** they?

**שימו לב:** בעברית אפשר לשאול "איפה אתם גרים?" בלי מילה נוספת. באנגלית צריך do או does: Where **do** you live?$$),
  ('adverbs-of-frequency', 'כמה פעמים: always, usually, often, sometimes, never', $$תארי פועל של תדירות אומרים **כמה פעמים** משהו קורה. מהגבוה לנמוך:

**always** (תמיד) > **usually** (בדרך כלל) > **often** (לעתים קרובות) > **sometimes** (לפעמים) > **rarely** (לעתים רחוקות) > **never** (אף פעם)

**איפה הם עומדים במשפט:**

- **לפני** פועל רגיל: I **usually** walk to work. She **never** eats meat.
- **אחרי** to be: He **is always** late. We **are often** tired on Sundays.
- **בין** פועל העזר לפועל: I **have never** been to Paris. Do you **often** cook?

**sometimes** יכול לבוא גם בתחילת המשפט: **Sometimes** I work from home.

**שימו לב:** never כבר שלילי, ולכן אין צורך ב-don't: I **never** drink coffee (לא I don't never drink).$$),
  ('possessive-s', 'של מי זה? Dana''s car', $$כדי להגיד שמשהו **שייך** למישהו, מוסיפים **'s** לבעלים, ומה ששייך לו בא אחרי.

- **Dana's** car = המכונית של דנה
- my **brother's** room = החדר של אח שלי
- the **teacher's** desk = השולחן של המורה

**רבים שמסתיימים ב-s:** מוסיפים רק גרש.

- my **parents'** house = הבית של ההורים שלי
- the **students'** books

**רבים לא רגילים** (בלי s בסוף) מקבלים **'s** רגיל: the **children's** toys, **women's** shoes.

**לחפצים** משתמשים בדרך כלל ב-**of**: the end **of** the film, the door **of** the car.

**שימו לב:** הסדר הפוך מהעברית. בעברית "הכלב של תום", באנגלית **Tom's dog**.$$),
  ('have-to', 'חובה ובלי חובה: have to ו-don''t have to', $$**have to** + בסיס = **חייבים**, בדרך כלל בגלל חוק, כלל או נסיבות.

- I **have to** wear a uniform at work.
- She **has to** get up early tomorrow.
- We **had to** wait for an hour. (עבר)

**don't have to** = **לא חייבים** (אבל מותר):

- You **don't have to** pay. It's free.
- He **doesn't have to** work on Fridays.

**must או have to?** שניהם "חייבים". **must** נשמע יותר כמו החלטה של הדובר (I must call my mother), ו-**have to** כמו כלל מבחוץ. בעבר יש רק **had to**.

**שימו לב:** mustn't ו-don't have to **לא** אותו דבר.

- You **mustn't** smoke here. = אסור.
- You **don't have to** come. = לא חובה, אפשר לבחור.$$),
  ('present-perfect-vs-past-simple', 'I have seen או I saw? מתי כל אחד', $$שני הזמנים מדברים על העבר. ההבדל הוא **אם הזמן חשוב ואם הוא נגמר**.

**עבר פשוט (I saw):** זמן מסוים שכבר נגמר. בדרך כלל יש מילת זמן: yesterday, last week, in 2019, two days ago, when I was a child.

- I **saw** that film **last week**.
- She **moved** to Tel Aviv **in 2020**.

**הווה מושלם (I have seen):** הזמן לא חשוב או עדיין לא נגמר. מילים שבאות איתו: ever, never, already, yet, just, so far, this week.

- I **have seen** that film. (מתי? לא חשוב)
- **Have** you **ever been** to Japan?
- She **has lived** here **since** 2020. (ועדיין גרה)

**ניסיון ואז פרטים:** פותחים בהווה מושלם ועוברים לעבר פשוט:

- **Have** you ever **eaten** sushi? Yes, I **ate** it in London last year.

**שימו לב:** אף פעם לא משתמשים בהווה מושלם עם זמן שנגמר: I **went** there yesterday (לא I have gone there yesterday).$$),
  ('verb-gerund-or-infinitive', 'enjoy doing או want to do? פעלים שבאים אחרי פעלים', $$כשפועל בא אחרי פועל אחר, הצורה שלו תלויה ב**פועל הראשון**. אין כלל אחד, אז לומדים את הנפוצים.

**פועל + ing:**

enjoy, finish, mind, avoid, suggest, keep, practise, miss

- I **enjoy cooking**.
- Have you **finished eating**?
- Do you **mind waiting** a minute?

**פועל + to:**

want, need, decide, hope, plan, agree, promise, learn, would like

- I **want to travel** next year.
- She **decided to leave** early.
- We **hope to see** you soon.

**שניהם, כמעט באותה משמעות:** like, love, hate, start, begin

- I **like swimming**. / I **like to swim**.
- It **started raining**. / It **started to rain**.

**אחרי מילת יחס תמיד ing:** I'm good **at drawing**. She's interested **in learning** Spanish.$$),
  ('may-might-possibility', 'אולי כן ואולי לא: may, might, could', $$כשלא בטוחים אם משהו יקרה או נכון, משתמשים ב-**may**, **might** או **could** + בסיס.

- It **might** rain later. Take an umbrella.
- She **may** be at home. Her car is outside.
- This **could** be the answer.

בדיבור יומיומי **might** הוא הנפוץ ביותר. **may** קצת יותר רשמי ונשמע מעט יותר בטוח.

**שלילה:** **might not** / **may not** = אולי לא.

- I **might not** come tonight. I'm very tired.

**שימו לב:**

- אחרי may ו-might באה צורת בסיס, בלי to: It might **be** true (לא might to be).
- **could not** הוא לא "אולי לא". הוא אומר שמשהו **בלתי אפשרי**: He couldn't be there. I saw him in Haifa.
- **maybe** היא מילה, לא פועל, והיא באה בתחילת המשפט: **Maybe** she's busy. = She **might** be busy.$$),
  ('so-such', 'כל כך: so tired, such a long day', $$שתי המילים אומרות **"כל כך"**, וההבדל הוא מה בא אחריהן.

**so** + שם תואר או תואר פועל (בלי שם עצם):

- The film was **so boring**.
- You speak **so quickly**.

**such** + (שם תואר) + שם עצם:

- It was **such a boring film**.
- They are **such nice people**.
- We had **such fun**.

עם שם עצם ביחיד שאפשר לספור באים **such a** / **such an**: such **a** good idea, such **an** easy test.

**so ... that / such ... that** = כל כך ... ש...:

- I was **so tired that** I fell asleep on the sofa.
- It was **such a hot day that** we stayed inside.

**שימו לב:** לא אומרים so a good day. כשיש שם עצם, משתמשים ב-such: **such a** good day.$$),
  ('present-perfect-continuous', 'I''ve been waiting: פעולה שנמשכת עד עכשיו', $$**have / has been + ing** מתאר פעולה שהתחילה בעבר, נמשכה, ו**עדיין נמשכת** או הסתיימה ממש עכשיו. הדגש הוא על **משך הזמן** או על הפעולה עצמה.

- I**'ve been waiting** for you for an hour!
- She**'s been learning** French since September.
- How long **have** you **been living** here?

**תוצאה שרואים עכשיו:** You're wet. **Have** you **been running**?

**מול הווה מושלם רגיל:**

- I**'ve been reading** this book. (התהליך, אולי לא סיימתי)
- I**'ve read** this book. (סיימתי, התוצאה)
- I**'ve read** three chapters. (כמות, ולכן הווה מושלם רגיל)

**for / since:**

- **for** + משך: for two hours, for a long time
- **since** + נקודת התחלה: since Monday, since 2018, since I was a child

**שימו לב:** פעלים של מצב (know, like, believe, own) לא באים ב-ing: I've **known** her for years (לא I've been knowing).$$),
  ('wish-if-only', 'הלוואי: I wish I knew, if only I had', $$**wish** ו-**if only** מביעים משאלה שהמצב יהיה אחרת. הזמן שבא אחריהם **זז צעד אחד אחורה**.

**על ההווה:** wish + עבר פשוט

- I **wish** I **knew** the answer. (אני לא יודע או יודעת)
- I **wish** I **had** more time.
- I **wish** I **were** taller. (ברשמי were לכל הגופים; בדיבור שומעים גם was)

**על העבר (חרטה):** wish + עבר מושלם

- I **wish** I **had studied** harder. (לא למדתי מספיק)
- She **wishes** she **hadn't said** that.

**על התנהגות של מישהו אחר שמעצבנת אותנו:** wish + would

- I **wish** you **would** stop talking.
- I **wish** it **would** stop raining.

**if only** זהה ל-wish, אבל חזק ורגשי יותר: **If only** I **had** listened to you!

**שימו לב:** לא אומרים I wish I would. על עצמנו משתמשים ב-could: I wish I **could** come.$$),
  ('causative-have-get', 'מישהו אחר עושה בשבילנו: I had my hair cut', $$כשמישהו **אחר** עושה בשבילנו עבודה (בדרך כלל בתשלום), משתמשים ב-**have + חפץ + צורה שלישית**.

- I **had my hair cut** yesterday. (הספר או הספרית גזרו לי)
- We're **having the kitchen painted**.
- She **has her car washed** every week.

**get** במקום have נפוץ בדיבור:

- I need to **get my phone fixed**.
- Where did you **get your nails done**?

**השוו:**

- I **cut** my hair. = גזרתי לבד.
- I **had** my hair **cut**. = מישהו גזר לי.

**גם לדברים לא נעימים שקרו לנו:** She **had her bag stolen** on the train.

**שימו לב לסדר:** have + **מה** + צורה שלישית. לא I had cut my hair (זה עבר מושלם, ומשמעותו שגזרתי בעצמי).$$),
  ('future-continuous-perfect', 'This time tomorrow I''ll be flying. By then I''ll have finished.', $$**עתיד מתמשך: will be + ing.** פעולה שתהיה **באמצע** ברגע מסוים בעתיד.

- **This time tomorrow** I**'ll be flying** to London.
- Don't call at 8. We**'ll be having** dinner.

גם כדי לשאול על תוכניות בנימוס: **Will** you **be using** the car tonight?

**עתיד מושלם: will have + צורה שלישית.** פעולה ש**תסתיים לפני** רגע מסוים בעתיד. הסימן הנפוץ: **by** (עד).

- **By** Friday I**'ll have finished** the project.
- **By the time** you arrive, the film **will have started**.
- She**'ll have worked** here for ten years next month.

**השוו:**

- At 9 I**'ll be writing** the report. (באמצע)
- By 9 I**'ll have written** the report. (כבר גמרתי)

**שימו לב:** אחרי by the time באה צורת הווה, לא will: By the time you **arrive** (לא will arrive).$$),
  ('concession-although-despite', 'למרות ש...: although, even though, despite, in spite of', $$כולן אומרות **"למרות"**, אבל כל אחת באה עם מבנה אחר.

**although / even though / though** + משפט שלם (נושא + פועל):

- **Although** it was raining, we went for a walk.
- **Even though** she was ill, she came to work. (חזק יותר)
- **Though** I like him, I don't trust him. (קצת פחות רשמי)

**despite / in spite of** + שם עצם או ing (לא משפט שלם):

- **Despite the rain**, we went for a walk.
- **In spite of being** ill, she came to work.
- **Despite the fact that** it was raining, ... (ככה מכניסים משפט שלם)

**however** מחבר בין **שני משפטים נפרדים**, ובא אחריו פסיק:

- The hotel was expensive. **However**, the service was excellent.

**שימו לב:** לא despite of (בלי of), ולא although + שם עצם. נכון: **Despite** the noise / **Although** it was noisy.$$),
  ('would-rather-had-better', 'העדפה ואזהרה: I''d rather stay, you''d better go', $$**would rather** = **מעדיפים**. אחריו בא בסיס, בלי to.

- I**'d rather stay** at home tonight.
- **Would** you **rather** have tea or coffee?
- I**'d rather not** talk about it.
- I'd rather walk **than** take a taxi.

**כשאנחנו מעדיפים שמישהו אחר יעשה משהו,** אחרי would rather בא **עבר פשוט**, גם כשמדברים על ההווה או העתיד:

- I**'d rather you didn't tell** anyone.
- She'd rather we **came** tomorrow.

**had better** = **כדאי מאוד** (ואם לא, יהיו בעיות). חזק יותר מ-should. אחריו בא בסיס, בלי to.

- You**'d better hurry**, or you'll miss the train.
- We**'d better not** be late again.

**שימו לב:**

- had better מדבר על **עכשיו ועל העתיד**, למרות ה-had.
- בקיצור **'d** יכול להיות would וגם had: I**'d** rather = would, You**'d** better = had.$$),
  ('ellipsis-substitution', 'לא לחזור על עצמנו: so, do, one, not', $$דוברים מתקדמים לא חוזרים על מילים שכבר נאמרו. יש שתי דרכים: **להחליף** את החלק שחוזר במילה קצרה, או **להשמיט** אותו.

**החלפה:**

- **one / ones** במקום שם עצם: I don't like the red shirt. I prefer the blue **one**.
- **do / does / did** במקום פועל וכל מה שאחריו: She plays the piano better than I **do**.
- **so** במקום משפט שלם, אחרי think, hope, expect, suppose, be afraid: Will it rain? I think **so**. / I hope **not**.
- **do so** ברשמי: The minister promised to resign and **did so** the next day.

**השמטה:**

- אחרי פועל עזר: I can't swim, but my sister **can**. (swim הושמט)
- אחרי to: I didn't want to go, but I had **to**.
- **neither / so** + פועל עזר + נושא: I'm tired. **So am I.** / I don't eat meat. **Neither do I.**

**שימו לב:** I don't think so (נפוץ וטבעי) לעומת I think not (רשמי מאוד). ו-I hope not, לא I don't hope so.$$)
) as l(slug, title_he, body_md) on gt.slug = l.slug;

insert into public.exercises (type, skill_area, grammar_topic_id, cefr_level, content, sort_order)
select 'fill_blank'::exercise_type, 'grammar'::skill_area, gt.id, gt.cefr_level, gen.content::jsonb, gen.sort_order
from (values
  ('there-is-there-are', '{"sentence":"___ a big park near my house.","correctAnswer":"There is","hint":"יחיד: there is"}', 1),
  ('there-is-there-are', '{"sentence":"There ___ two cafés on this street.","correctAnswer":"are","hint":"רבים: are"}', 2),
  ('there-is-there-are', '{"sentence":"___ there a toilet on this floor?","correctAnswer":"Is","hint":"שאלה ביחיד"}', 3),
  ('there-is-there-are', '{"sentence":"There ___ any milk left. Can you buy some?","correctAnswer":"isn''t","hint":"שלילה, milk הוא בלתי ספיר"}', 4),
  ('there-is-there-are', '{"sentence":"Are there any apples? No, there ___.","correctAnswer":"aren''t","hint":"תשובה קצרה ברבים"}', 5),
  ('imperatives', '{"sentence":"___ your books on page 12.","correctAnswer":"Open","hint":"צורת בסיס"}', 1),
  ('imperatives', '{"sentence":"___ worry. Everything is fine.","correctAnswer":"Don''t","hint":"ציווי בשלילה"}', 2),
  ('imperatives', '{"sentence":"It''s late. ___ go home.","correctAnswer":"Let''s","hint":"הצעה שכוללת גם אותנו"}', 3),
  ('imperatives', '{"sentence":"Please ___ quiet in the library.","correctAnswer":"be","hint":"ציווי של to be"}', 4),
  ('imperatives', '{"sentence":"Don''t ___ the door. It''s cold outside.","correctAnswer":"open","hint":"אחרי don''t: בסיס"}', 5),
  ('object-pronouns', '{"sentence":"I don''t know that man. Do you know ___?","correctAnswer":"him","hint":"מושא של he"}', 1),
  ('object-pronouns', '{"sentence":"My sister is here. Do you want to talk to ___?","correctAnswer":"her","hint":"אחרי to"}', 2),
  ('object-pronouns', '{"sentence":"We''re lost. Can you help ___?","correctAnswer":"us","hint":"מושא של we"}', 3),
  ('object-pronouns', '{"sentence":"These shoes are great. I want ___.","correctAnswer":"them","hint":"מושא ברבים"}', 4),
  ('object-pronouns', '{"sentence":"Call ___ when you get home. I''ll be awake.","correctAnswer":"me","hint":"מושא של I"}', 5),
  ('question-words', '{"sentence":"___ is your birthday? In May.","correctAnswer":"When","hint":"שאלה על זמן"}', 1),
  ('question-words', '{"sentence":"___ do you live? In Haifa.","correctAnswer":"Where","hint":"שאלה על מקום"}', 2),
  ('question-words', '{"sentence":"How ___ brothers and sisters do you have?","correctAnswer":"many","hint":"כמה, עם רבים"}', 3),
  ('question-words', '{"sentence":"___ are you late? The bus didn''t come.","correctAnswer":"Why","hint":"שאלה על סיבה"}', 4),
  ('question-words', '{"sentence":"What time ___ the shop open?","correctAnswer":"does","hint":"פועל עזר לגוף שלישי יחיד"}', 5),
  ('adverbs-of-frequency', '{"sentence":"I ___ get up at 7. Every single day.","correctAnswer":"always","hint":"תמיד"}', 1),
  ('adverbs-of-frequency', '{"sentence":"She is ___ late. She hates waiting.","correctAnswer":"never","hint":"אף פעם"}', 2),
  ('adverbs-of-frequency', '{"sentence":"We ___ go to the cinema, maybe once a year.","correctAnswer":"rarely","hint":"לעתים רחוקות"}', 3),
  ('adverbs-of-frequency', '{"sentence":"Do you ___ eat breakfast?","correctAnswer":"usually","hint":"בדרך כלל, בתוך שאלה"}', 4),
  ('adverbs-of-frequency', '{"sentence":"He ___ always tired after work.","correctAnswer":"is","hint":"תדירות באה אחרי to be"}', 5),
  ('possessive-s', '{"sentence":"This is ___ phone. (Noa)","correctAnswer":"Noa''s","hint":"בעלים ביחיד: ''s"}', 1),
  ('possessive-s', '{"sentence":"My ___ house is very big. (parents)","correctAnswer":"parents''","hint":"רבים עם s: רק גרש"}', 2),
  ('possessive-s', '{"sentence":"The ___ toys are everywhere. (children)","correctAnswer":"children''s","hint":"רבים בלי s: ''s"}', 3),
  ('possessive-s', '{"sentence":"I don''t like the end ___ the film.","correctAnswer":"of","hint":"לחפצים: of"}', 4),
  ('possessive-s', '{"sentence":"Is that your ___ car? (sister)","correctAnswer":"sister''s","hint":"בעלים ביחיד"}', 5),
  ('have-to', '{"sentence":"In Israel, you ___ to be 17 to drive.","correctAnswer":"have","hint":"חובה לפי חוק"}', 1),
  ('have-to', '{"sentence":"She ___ to take the bus because her car broke down.","correctAnswer":"has","hint":"גוף שלישי יחיד"}', 2),
  ('have-to', '{"sentence":"You ___ have to bring food. There''s a lot here.","correctAnswer":"don''t","hint":"לא חובה"}', 3),
  ('have-to', '{"sentence":"Yesterday we ___ to stay late at the office.","correctAnswer":"had","hint":"חובה בעבר"}', 4),
  ('have-to', '{"sentence":"You ___ park here. It''s for ambulances only.","correctAnswer":"mustn''t","hint":"אסור, לא רק לא חובה"}', 5),
  ('present-perfect-vs-past-simple', '{"sentence":"I ___ my keys. I can''t find them anywhere.","correctAnswer":"have lost","hint":"תוצאה שקיימת עכשיו"}', 1),
  ('present-perfect-vs-past-simple', '{"sentence":"We ___ to Eilat last summer.","correctAnswer":"went","hint":"זמן שנגמר: last summer"}', 2),
  ('present-perfect-vs-past-simple', '{"sentence":"___ you ever tried Ethiopian food?","correctAnswer":"Have","hint":"ניסיון בחיים"}', 3),
  ('present-perfect-vs-past-simple', '{"sentence":"She ___ her homework two hours ago.","correctAnswer":"finished","hint":"ago: עבר פשוט"}', 4),
  ('present-perfect-vs-past-simple', '{"sentence":"I''ve already ___ that book. It was great.","correctAnswer":"read","hint":"צורה שלישית של read"}', 5),
  ('verb-gerund-or-infinitive', '{"sentence":"I really enjoy ___ in the sea. (swim)","correctAnswer":"swimming","hint":"enjoy + ing"}', 1),
  ('verb-gerund-or-infinitive', '{"sentence":"We decided ___ a new car. (buy)","correctAnswer":"to buy","hint":"decide + to"}', 2),
  ('verb-gerund-or-infinitive', '{"sentence":"Would you mind ___ the window? (close)","correctAnswer":"closing","hint":"mind + ing"}', 3),
  ('verb-gerund-or-infinitive', '{"sentence":"She hopes ___ a doctor one day. (become)","correctAnswer":"to become","hint":"hope + to"}', 4),
  ('verb-gerund-or-infinitive', '{"sentence":"He''s very good at ___ jokes. (tell)","correctAnswer":"telling","hint":"אחרי מילת יחס: ing"}', 5),
  ('may-might-possibility', '{"sentence":"Take a jacket. It ___ get cold tonight.","correctAnswer":"might","hint":"אפשרות בעתיד"}', 1),
  ('may-might-possibility', '{"sentence":"I''m not sure. He ___ be in a meeting.","correctAnswer":"may","hint":"אפשרות בהווה"}', 2),
  ('may-might-possibility', '{"sentence":"We might ___ go to the party. We''ll see.","correctAnswer":"not","hint":"אולי לא"}', 3),
  ('may-might-possibility', '{"sentence":"___ she missed the bus. She''s never late.","correctAnswer":"Maybe","hint":"מילה בתחילת משפט, לא פועל"}', 4),
  ('may-might-possibility', '{"sentence":"It might ___ a good idea to book a table. (be)","correctAnswer":"be","hint":"אחרי might: בסיס"}', 5),
  ('so-such', '{"sentence":"The soup is ___ hot. Wait a minute.","correctAnswer":"so","hint":"so + שם תואר"}', 1),
  ('so-such', '{"sentence":"She is ___ a good teacher.","correctAnswer":"such","hint":"such + a + שם עצם"}', 2),
  ('so-such', '{"sentence":"It was ___ an easy question.","correctAnswer":"such","hint":"such an + שם עצם"}', 3),
  ('so-such', '{"sentence":"They were ___ happy that they started to dance.","correctAnswer":"so","hint":"so ... that"}', 4),
  ('so-such', '{"sentence":"We had ___ a good time in Eilat.","correctAnswer":"such","hint":"such + a good time"}', 5),
  ('present-perfect-continuous', '{"sentence":"I''ve been ___ for the bus for 20 minutes. (wait)","correctAnswer":"waiting","hint":"been + ing"}', 1),
  ('present-perfect-continuous', '{"sentence":"How long ___ you been studying English?","correctAnswer":"have","hint":"שאלה: have + נושא + been"}', 2),
  ('present-perfect-continuous', '{"sentence":"She''s been working here ___ 2021.","correctAnswer":"since","hint":"נקודת התחלה"}', 3),
  ('present-perfect-continuous', '{"sentence":"They''ve been talking ___ hours.","correctAnswer":"for","hint":"משך זמן"}', 4),
  ('present-perfect-continuous', '{"sentence":"I''ve ___ him since we were at school. (know)","correctAnswer":"known","hint":"פועל מצב: בלי ing"}', 5),
  ('wish-if-only', '{"sentence":"I wish I ___ how to swim. (know)","correctAnswer":"knew","hint":"משאלה על ההווה: עבר פשוט"}', 1),
  ('wish-if-only', '{"sentence":"I wish I ___ gone to bed earlier last night.","correctAnswer":"had","hint":"חרטה על העבר"}', 2),
  ('wish-if-only', '{"sentence":"If only I ___ more money!","correctAnswer":"had","hint":"משאלה על ההווה"}', 3),
  ('wish-if-only', '{"sentence":"I wish you ___ stop interrupting me.","correctAnswer":"would","hint":"התנהגות של אחר"}', 4),
  ('wish-if-only', '{"sentence":"I wish I ___ come to your party, but I''m abroad.","correctAnswer":"could","hint":"על עצמנו: could"}', 5),
  ('causative-have-get', '{"sentence":"I''m going to have my eyes ___ tomorrow. (test)","correctAnswer":"tested","hint":"צורה שלישית"}', 1),
  ('causative-have-get', '{"sentence":"We had the roof ___ after the storm. (repair)","correctAnswer":"repaired","hint":"צורה שלישית"}', 2),
  ('causative-have-get', '{"sentence":"You should ___ that tooth checked by a dentist.","correctAnswer":"get","hint":"get במקום have"}', 3),
  ('causative-have-get', '{"sentence":"She ___ her hair done for the wedding last week.","correctAnswer":"had","hint":"have בעבר"}', 4),
  ('causative-have-get', '{"sentence":"He had his wallet ___ on the bus. (steal)","correctAnswer":"stolen","hint":"משהו לא נעים שקרה לנו"}', 5),
  ('future-continuous-perfect', '{"sentence":"At 10 tomorrow I''ll be ___ an exam. (take)","correctAnswer":"taking","hint":"באמצע פעולה"}', 1),
  ('future-continuous-perfect', '{"sentence":"By next June, I will ___ graduated.","correctAnswer":"have","hint":"will have + צורה שלישית"}', 2),
  ('future-continuous-perfect', '{"sentence":"Don''t come at 7. We''ll ___ eating dinner.","correctAnswer":"be","hint":"will be + ing"}', 3),
  ('future-continuous-perfect', '{"sentence":"By the time we ___, the shop will have closed. (arrive)","correctAnswer":"arrive","hint":"אחרי by the time: הווה"}', 4),
  ('future-continuous-perfect', '{"sentence":"She will have ___ the whole book by tonight. (read)","correctAnswer":"read","hint":"צורה שלישית של read"}', 5),
  ('concession-although-despite', '{"sentence":"___ the traffic, we arrived on time.","correctAnswer":"Despite","hint":"+ שם עצם"}', 1),
  ('concession-although-despite', '{"sentence":"___ she studied hard, she failed the test.","correctAnswer":"Although","hint":"+ משפט שלם"}', 2),
  ('concession-although-despite', '{"sentence":"In spite ___ feeling tired, he finished the race.","correctAnswer":"of","hint":"in spite of + ing"}', 3),
  ('concession-although-despite', '{"sentence":"The plan was risky. ___, it worked perfectly.","correctAnswer":"However","hint":"מחבר בין שני משפטים"}', 4),
  ('concession-although-despite', '{"sentence":"Despite the fact ___ it was late, nobody wanted to leave.","correctAnswer":"that","hint":"despite the fact that + משפט"}', 5),
  ('would-rather-had-better', '{"sentence":"I''d rather ___ at home than go out tonight. (stay)","correctAnswer":"stay","hint":"would rather + בסיס"}', 1),
  ('would-rather-had-better', '{"sentence":"You''d ___ take an umbrella. It''s going to pour.","correctAnswer":"better","hint":"had better"}', 2),
  ('would-rather-had-better', '{"sentence":"I''d rather you ___ smoke in the car. (not)","correctAnswer":"didn''t","hint":"מישהו אחר: עבר פשוט"}', 3),
  ('would-rather-had-better', '{"sentence":"We''d better ___ be late for the interview.","correctAnswer":"not","hint":"had better not"}', 4),
  ('would-rather-had-better', '{"sentence":"Would you rather live in the city ___ in the country?","correctAnswer":"or","hint":"בחירה בין שתי אפשרויות"}', 5),
  ('ellipsis-substitution', '{"sentence":"This cup is broken. Can I have another ___?","correctAnswer":"one","hint":"החלפת שם עצם"}', 1),
  ('ellipsis-substitution', '{"sentence":"Is the shop open on Saturday? I don''t think ___.","correctAnswer":"so","hint":"החלפת משפט"}', 2),
  ('ellipsis-substitution', '{"sentence":"He speaks Arabic better than I ___.","correctAnswer":"do","hint":"החלפת פועל"}', 3),
  ('ellipsis-substitution', '{"sentence":"Will it be expensive? I hope ___.","correctAnswer":"not","hint":"I hope not"}', 4),
  ('ellipsis-substitution', '{"sentence":"I haven''t seen that film. Neither ___ I.","correctAnswer":"have","hint":"השמטה עם פועל עזר"}', 5)
) as gen(slug, content, sort_order)
join public.grammar_topics gt on gt.slug = gen.slug;

insert into public.exercises (type, skill_area, grammar_topic_id, cefr_level, content, sort_order)
select 'reorder'::exercise_type, 'grammar'::skill_area, gt.id, gt.cefr_level, gen.content::jsonb, gen.sort_order
from (values
  ('there-is-there-are', '{"tokens":["There","are","four","people","in","my","family"],"correctOrder":[0,1,2,3,4,5,6]}', 100),
  ('there-is-there-are', '{"tokens":["Is","there","a","bus","to","the","airport"],"correctOrder":[0,1,2,3,4,5,6]}', 101),
  ('imperatives', '{"tokens":["Please","turn","off","your","phone"],"correctOrder":[0,1,2,3,4]}', 100),
  ('imperatives', '{"tokens":["Don''t","forget","your","keys"],"correctOrder":[0,1,2,3]}', 101),
  ('object-pronouns', '{"tokens":["Can","you","send","me","the","photos"],"correctOrder":[0,1,2,3,4,5]}', 100),
  ('object-pronouns', '{"tokens":["We","visit","them","every","summer"],"correctOrder":[0,1,2,3,4]}', 101),
  ('question-words', '{"tokens":["Where","do","your","parents","work"],"correctOrder":[0,1,2,3,4]}', 100),
  ('question-words', '{"tokens":["How","much","is","this","jacket"],"correctOrder":[0,1,2,3,4]}', 101),
  ('adverbs-of-frequency', '{"tokens":["I","usually","have","lunch","at","one"],"correctOrder":[0,1,2,3,4,5]}', 100),
  ('adverbs-of-frequency', '{"tokens":["They","are","never","at","home","on","Fridays"],"correctOrder":[0,1,2,3,4,5,6]}', 101),
  ('possessive-s', '{"tokens":["That","is","my","friend''s","bike"],"correctOrder":[0,1,2,3,4]}', 100),
  ('possessive-s', '{"tokens":["We","stayed","at","my","grandparents''","house"],"correctOrder":[0,1,2,3,4,5]}', 101),
  ('have-to', '{"tokens":["Do","we","have","to","bring","our","passports"],"correctOrder":[0,1,2,3,4,5,6]}', 100),
  ('have-to', '{"tokens":["He","doesn''t","have","to","work","tomorrow"],"correctOrder":[0,1,2,3,4,5]}', 101),
  ('present-perfect-vs-past-simple', '{"tokens":["Have","you","ever","been","to","Rome"],"correctOrder":[0,1,2,3,4,5]}', 100),
  ('present-perfect-vs-past-simple', '{"tokens":["I","met","him","three","years","ago"],"correctOrder":[0,1,2,3,4,5]}', 101),
  ('verb-gerund-or-infinitive', '{"tokens":["I","want","to","learn","the","guitar"],"correctOrder":[0,1,2,3,4,5]}', 100),
  ('verb-gerund-or-infinitive', '{"tokens":["She","finished","writing","the","report"],"correctOrder":[0,1,2,3,4]}', 101),
  ('may-might-possibility', '{"tokens":["I","might","visit","my","aunt","this","weekend"],"correctOrder":[0,1,2,3,4,5,6]}', 100),
  ('may-might-possibility', '{"tokens":["They","may","not","have","time","today"],"correctOrder":[0,1,2,3,4,5]}', 101),
  ('so-such', '{"tokens":["It","was","such","a","beautiful","day"],"correctOrder":[0,1,2,3,4,5]}', 100),
  ('so-such', '{"tokens":["I","was","so","hungry","that","I","ate","everything"],"correctOrder":[0,1,2,3,4,5,6,7]}', 101),
  ('present-perfect-continuous', '{"tokens":["We","have","been","living","here","for","ten","years"],"correctOrder":[0,1,2,3,4,5,6,7]}', 100),
  ('present-perfect-continuous', '{"tokens":["What","have","you","been","doing","all","day"],"correctOrder":[0,1,2,3,4,5,6]}', 101),
  ('wish-if-only', '{"tokens":["I","wish","I","had","taken","more","photos"],"correctOrder":[0,1,2,3,4,5,6]}', 100),
  ('wish-if-only', '{"tokens":["If","only","we","lived","near","the","sea"],"correctOrder":[0,1,2,3,4,5,6]}', 101),
  ('causative-have-get', '{"tokens":["I","need","to","get","my","car","serviced"],"correctOrder":[0,1,2,3,4,5,6]}', 100),
  ('causative-have-get', '{"tokens":["They","had","their","house","painted","last","year"],"correctOrder":[0,1,2,3,4,5,6]}', 101),
  ('future-continuous-perfect', '{"tokens":["This","time","next","week","we''ll","be","lying","on","the","beach"],"correctOrder":[0,1,2,3,4,5,6,7,8,9]}', 100),
  ('future-continuous-perfect', '{"tokens":["By","Monday","I''ll","have","answered","all","the","emails"],"correctOrder":[0,1,2,3,4,5,6,7]}', 101),
  ('concession-although-despite', '{"tokens":["Even","though","it","was","cold","we","swam","in","the","sea"],"correctOrder":[0,1,2,3,4,5,6,7,8,9]}', 100),
  ('concession-although-despite', '{"tokens":["Despite","his","injury","he","played","the","whole","match"],"correctOrder":[0,1,2,3,4,5,6,7]}', 101),
  ('would-rather-had-better', '{"tokens":["I''d","rather","not","discuss","it","now"],"correctOrder":[0,1,2,3,4,5]}', 100),
  ('would-rather-had-better', '{"tokens":["You''d","better","call","her","before","she","leaves"],"correctOrder":[0,1,2,3,4,5,6]}', 101),
  ('ellipsis-substitution', '{"tokens":["She","wanted","to","leave","but","she","couldn''t"],"correctOrder":[0,1,2,3,4,5,6]}', 100),
  ('ellipsis-substitution', '{"tokens":["I","prefer","the","older","photos","to","the","new","ones"],"correctOrder":[0,1,2,3,4,5,6,7,8]}', 101)
) as gen(slug, content, sort_order)
join public.grammar_topics gt on gt.slug = gen.slug;

-- Check: how many topics, lessons and exercises this seed now has.
select
  (select count(*) from public.grammar_topics where slug in ('there-is-there-are', 'imperatives', 'object-pronouns', 'question-words', 'adverbs-of-frequency', 'possessive-s', 'have-to', 'present-perfect-vs-past-simple', 'verb-gerund-or-infinitive', 'may-might-possibility', 'so-such', 'present-perfect-continuous', 'wish-if-only', 'causative-have-get', 'future-continuous-perfect', 'concession-although-despite', 'would-rather-had-better', 'ellipsis-substitution')) as topics,
  (select count(*) from public.grammar_lessons gl join public.grammar_topics gt on gt.id = gl.grammar_topic_id where gt.slug in ('there-is-there-are', 'imperatives', 'object-pronouns', 'question-words', 'adverbs-of-frequency', 'possessive-s', 'have-to', 'present-perfect-vs-past-simple', 'verb-gerund-or-infinitive', 'may-might-possibility', 'so-such', 'present-perfect-continuous', 'wish-if-only', 'causative-have-get', 'future-continuous-perfect', 'concession-although-despite', 'would-rather-had-better', 'ellipsis-substitution')) as lessons,
  (select count(*) from public.exercises e join public.grammar_topics gt on gt.id = e.grammar_topic_id where gt.slug in ('there-is-there-are', 'imperatives', 'object-pronouns', 'question-words', 'adverbs-of-frequency', 'possessive-s', 'have-to', 'present-perfect-vs-past-simple', 'verb-gerund-or-infinitive', 'may-might-possibility', 'so-such', 'present-perfect-continuous', 'wish-if-only', 'causative-have-get', 'future-continuous-perfect', 'concession-although-despite', 'would-rather-had-better', 'ellipsis-substitution')) as exercises;
