-- 035_listening_set_2.sql (generated by scripts/generate-reading-listening.mjs from
-- scripts/content/listeningSet2.mjs; edit the content there).
-- 0 original reading texts (MCQ + open questions each),
-- 10 listening clips (MCQ + 1 dictation each), and comprehension
-- questions for 5 existing clips.
-- Safe to re-run: rows with these titles are deleted first; their
-- exercises and open questions cascade.

delete from public.listening_clips where title_en in ('At the Bakery', 'Meeting in the Park', 'The Weather Today', 'After School', 'A Product Launch Briefing', 'A Lecture on Sleep and Memory', 'A Voicemail from a Contractor', 'A Radio Debate on Rent Control', 'A Talk on Translation', 'An Interview on AI and Accountability');

insert into public.listening_clips (title_he, title_en, transcript_en, cefr_level, style, sort_order) values
  ('במאפייה', 'At the Bakery', 'Good morning! Can I help you? Yes, please. I want two rolls and one chocolate cake. Anything else? No, thank you. How much is it? It''s twenty-two shekels. Here you are. Thank you! Have a nice day. You too, bye!', 'A1', 'standard', 100),
  ('היכרות בפארק', 'Meeting in the Park', 'Hi! My name is Tom. What''s your name? I''m Maya. Nice to meet you, Maya. Are you from here? No, I''m from Eilat. I live in Tel Aviv now. Is that your dog? Yes, his name is Max. He is three years old. He loves the park!', 'A1', 'standard', 101),
  ('מזג האוויר היום', 'The Weather Today', 'Good morning! Here is the weather for today. In the north, it is cold and rainy. In Tel Aviv, it is cloudy and twenty degrees. In the south, it is hot and sunny, thirty degrees. Take an umbrella if you go north!', 'A1', 'standard', 102),
  ('נפגשים אחרי בית הספר', 'After School', 'Hi Dan! Do you want to play basketball after school? Yes! What time? At four o''clock. Where? At the park near my house. OK. Can my sister come too? Sure! See you at four.', 'A1', 'standard', 103),
  ('תדריך לפני השקת מוצר', 'A Product Launch Briefing', 'Okay, everyone, thanks for joining at short notice. As you know, the launch has been moved forward by two weeks, which means we''re now going live on the fourteenth rather than the twenty-eighth. I know that puts pressure on the support team in particular, so here''s what we''ve agreed. First, we''ll release to ten percent of users on day one, and only widen it once the error rate stays below one percent for forty-eight hours. Second, marketing will hold back the press release until that point, so we''re not driving traffic to something that might wobble. Third, anyone on the support rota that week gets the following Friday off. I''d rather we under-promise and over-deliver here. If you can see a risk I haven''t mentioned, flag it today, not on the fourteenth.', 'C1', 'standard', 104),
  ('הרצאה על שינה וזיכרון', 'A Lecture on Sleep and Memory', 'Let''s start with a question most of you will have asked yourselves the night before an exam: is it better to stay up revising, or to sleep? The research is fairly consistent. During deep sleep, the brain replays what it learned during the day and gradually moves it from short-term to long-term storage. In one well-known type of study, two groups learn the same list of words; one group sleeps, the other stays awake, and both are tested twelve hours later. The group that slept typically remembers noticeably more. That doesn''t mean sleep replaces studying, of course. It means the two work together. Cutting sleep to gain an extra hour of revision is, in most cases, a poor trade. So if there''s one practical takeaway from today, it''s this: protect your sleep most carefully in exactly the weeks you feel least able to afford it.', 'C1', 'standard', 105),
  ('הודעה קולית מקבלן השיפוצים', 'A Voicemail from a Contractor', 'Hi, it''s Ronen from the renovation company, calling about your kitchen. Bit of a mixed update, I''m afraid. The good news is the cabinets arrived this morning, and they look great. The not-so-good news is that when we took the old tiles off, we found some water damage behind the sink, probably from a slow leak that''s been going on for years. We can''t just tile over it, because it''ll come back and you''ll end up paying twice. So I''d suggest we bring in a plumber on Monday to find the source, and push the tiling back to Wednesday. It''ll add roughly two days and a bit to the cost, but I''ll send you a written quote first, so nothing goes ahead without your okay. Give me a call back when you get a chance.', 'C1', 'standard', 106),
  ('דיון ברדיו על פיקוח על שכר דירה', 'A Radio Debate on Rent Control', 'Supporters of rent control tend to frame it as a matter of basic fairness, and I don''t dismiss that. But we have to distinguish between what a policy intends and what it actually does. When rents are capped well below market levels, landlords have little incentive to maintain their buildings, let alone build new ones, and people who already hold a controlled lease rarely move, even when their circumstances change. The upshot is a market that protects insiders while making it harder for newcomers, often the young and the less well-off, to find anywhere at all. None of this means the state should simply step back. The more promising levers, in my view, are on the supply side: freeing up land, speeding up permits, and tying any subsidy to the person rather than to the apartment. Fairness, in other words, is better served by abundance than by rationing.', 'C2', 'standard', 107),
  ('הרצאה על תרגום', 'A Talk on Translation', 'People often assume that a perfect translation is simply one that loses nothing. In practice, every translator is forced into a series of small betrayals. Take humor: a pun that works beautifully in Hebrew may have no equivalent in English at all, so the translator must decide whether to explain the joke, replace it with a different one, or let it quietly disappear. Each option sacrifices something, whether it''s accuracy, rhythm or the reader''s pleasure. The same is true of register. A character who speaks in a slightly old-fashioned way can sound charming in one language and merely stiff in another. What distinguishes a great translator, then, is not the absence of loss, but judgment about which losses the work can bear. The best translations are not invisible; they are honest about the choices they have made.', 'C2', 'standard', 108),
  ('ראיון על בינה מלאכותית ואחריות', 'An Interview on AI and Accountability', 'Many people worry that AI systems will make decisions no one can explain. Is that fear justified? Partly. Some of the most capable systems are genuinely opaque, even to the people who built them. But I''d push back on the idea that human decisions are always transparent. A loan officer or a hiring manager can give you a reason, but it isn''t necessarily the real one. What matters, I''d argue, is accountability rather than perfect explainability. If a system affects someone''s life, there should be a named person or institution responsible for it, a way to challenge the outcome, and regular checks for bias. So you''re not calling for a ban? Not across the board, no. Bans make sense in a few narrow areas. Elsewhere, the harder and more useful work is building institutions that can say no when a system gets it wrong.', 'C2', 'standard', 109);

insert into public.exercises (type, skill_area, listening_clip_id, cefr_level, content, sort_order)
select 'mcq'::exercise_type, 'listening'::skill_area, lc.id, lc.cefr_level, gen.content::jsonb, gen.sort_order
from public.listening_clips lc
join (values
  ('At the Bakery', '{"prompt":"כמה לחמניות מבקשים?","options":["One","Two","Three","Four"],"correctIndex":1}', 2),
  ('At the Bakery', '{"prompt":"כמה זה עולה?","options":["Twelve shekels","Twenty shekels","Twenty-two shekels","Thirty shekels"],"correctIndex":2}', 3),
  ('At the Bakery', '{"prompt":"מה עוד קונים?","options":["Some milk","A sandwich","A coffee","A chocolate cake"],"correctIndex":3}', 4),
  ('Meeting in the Park', '{"prompt":"מאיפה מאיה?","options":["Haifa","Eilat","Jerusalem","Tel Aviv"],"correctIndex":1}', 2),
  ('Meeting in the Park', '{"prompt":"מה שם הכלב?","options":["Ben","Tom","Max","Sam"],"correctIndex":2}', 3),
  ('Meeting in the Park', '{"prompt":"בן כמה הכלב?","options":["Four","Five","Two","Three"],"correctIndex":3}', 4),
  ('The Weather Today', '{"prompt":"איך מזג האוויר בצפון?","options":["Hot and sunny","Cold and rainy","Cloudy and warm","Snowy"],"correctIndex":1}', 2),
  ('The Weather Today', '{"prompt":"כמה מעלות בתל אביב?","options":["Thirty","Ten","Twenty","Twenty-five"],"correctIndex":2}', 3),
  ('The Weather Today', '{"prompt":"מה כדאי לקחת לצפון?","options":["A fan","Sunglasses","A swimsuit","An umbrella"],"correctIndex":3}', 4),
  ('After School', '{"prompt":"מה רוצים לשחק?","options":["Tennis","Basketball","Volleyball","Football"],"correctIndex":1}', 2),
  ('After School', '{"prompt":"באיזו שעה נפגשים?","options":["At two","At three","At four","At five"],"correctIndex":2}', 3),
  ('After School', '{"prompt":"מי עוד מגיע?","options":["Dan''s mother","Dan''s teacher","Dan''s brother","Dan''s sister"],"correctIndex":3}', 4),
  ('A Product Launch Briefing', '{"prompt":"Why was the meeting called?","options":["The launch has been delayed","The launch date has been brought forward","The product has been cancelled","A new team has been formed"],"correctIndex":1}', 2),
  ('A Product Launch Briefing', '{"prompt":"What must happen before the release is widened?","options":["Ten percent of users must give feedback","Marketing must publish a press release","The error rate must stay low for two days","The support team must vote on it"],"correctIndex":2}', 3),
  ('A Product Launch Briefing', '{"prompt":"What does the speaker mean by \"under-promise and over-deliver\"?","options":["Avoid making any promises at all","Deliver the product later than planned","Promise more to impress customers","Promise less than you expect to achieve, then do more"],"correctIndex":3}', 4),
  ('A Lecture on Sleep and Memory', '{"prompt":"According to the lecture, what happens during deep sleep?","options":["The brain deletes unimportant facts","The brain moves new learning into long-term memory","The brain rests completely","Short-term memory gets stronger"],"correctIndex":1}', 2),
  ('A Lecture on Sleep and Memory', '{"prompt":"In the studies described, which group remembers more?","options":["The group that stayed awake","The group that studied longer","The group that slept","Both groups equally"],"correctIndex":2}', 3),
  ('A Lecture on Sleep and Memory', '{"prompt":"What is the speaker''s main advice?","options":["Study only in the morning","Study through the night before exams","Sleep can replace studying","Protect your sleep, especially in busy weeks"],"correctIndex":3}', 4),
  ('A Voicemail from a Contractor', '{"prompt":"What problem did the workers find?","options":["The cabinets were damaged","There was water damage behind the sink","The tiles were the wrong color","The plumber didn''t come"],"correctIndex":1}', 2),
  ('A Voicemail from a Contractor', '{"prompt":"Why can''t they tile over the problem?","options":["The new tiles haven''t arrived","It would be too expensive","The damage would come back","The customer refused"],"correctIndex":2}', 3),
  ('A Voicemail from a Contractor', '{"prompt":"What will Ronen do before any extra work starts?","options":["Ask for full payment","Cancel the project","Start immediately","Send a written quote for approval"],"correctIndex":3}', 4),
  ('A Radio Debate on Rent Control', '{"prompt":"What distinction does the speaker insist on?","options":["Between landlords and tenants","Between a policy''s aims and its actual effects","Between old and new buildings","Between renting and owning"],"correctIndex":1}', 2),
  ('A Radio Debate on Rent Control', '{"prompt":"Who, according to the speaker, loses out under strict rent control?","options":["Tenants who already have controlled leases","Landlords only","Newcomers such as young people","The state"],"correctIndex":2}', 3),
  ('A Radio Debate on Rent Control', '{"prompt":"What does \"fairness is better served by abundance than by rationing\" suggest?","options":["Rents should be raised","The state should own all housing","Housing should be shared out equally","Building more is fairer than capping prices"],"correctIndex":3}', 4),
  ('A Talk on Translation', '{"prompt":"What does the speaker mean by \"small betrayals\"?","options":["Translators often make careless mistakes","Translators have to give up some features of the original","Translators change the plot","Translators ignore the author''s wishes"],"correctIndex":1}', 2),
  ('A Talk on Translation', '{"prompt":"Which options for translating a pun are mentioned?","options":["Ask the author what to do","Always add a footnote","Explain it, replace it, or let it disappear","Translate it word for word"],"correctIndex":2}', 3),
  ('A Talk on Translation', '{"prompt":"According to the speaker, what makes a great translator?","options":["Speed and accuracy","A modern, simple style","Losing nothing from the original","Good judgment about which losses to accept"],"correctIndex":3}', 4),
  ('An Interview on AI and Accountability', '{"prompt":"What does the guest say about human decisions?","options":["They are always fair","They are not always as transparent as they seem","They are easier to challenge than AI decisions","They should be replaced by AI"],"correctIndex":1}', 2),
  ('An Interview on AI and Accountability', '{"prompt":"What does the guest consider most important?","options":["Perfect explainability","Banning AI systems","Accountability for systems that affect people","Faster decisions"],"correctIndex":2}', 3),
  ('An Interview on AI and Accountability', '{"prompt":"What is the guest''s position on bans?","options":["Companies should decide on bans","AI should be banned everywhere","Bans are never justified","Bans make sense only in a few narrow areas"],"correctIndex":3}', 4)
) as gen(title_en, content, sort_order)
  on lc.title_en = gen.title_en;

insert into public.exercises (type, skill_area, listening_clip_id, cefr_level, content, sort_order)
select 'dictation'::exercise_type, 'listening'::skill_area, lc.id, lc.cefr_level, gen.content::jsonb, 1
from public.listening_clips lc
join (values
  ('At the Bakery', '{"audioText":"I want two rolls and one chocolate cake.","correctAnswer":"I want two rolls and one chocolate cake."}'),
  ('Meeting in the Park', '{"audioText":"He is three years old.","correctAnswer":"He is three years old."}'),
  ('The Weather Today', '{"audioText":"In the south, it is hot and sunny.","correctAnswer":"In the south, it is hot and sunny."}'),
  ('After School', '{"audioText":"Do you want to play basketball after school?","correctAnswer":"Do you want to play basketball after school?"}'),
  ('A Product Launch Briefing', '{"audioText":"The launch has been moved forward by two weeks.","correctAnswer":"The launch has been moved forward by two weeks."}'),
  ('A Lecture on Sleep and Memory', '{"audioText":"The group that slept typically remembers noticeably more.","correctAnswer":"The group that slept typically remembers noticeably more."}'),
  ('A Voicemail from a Contractor', '{"audioText":"The cabinets arrived this morning, and they look great.","correctAnswer":"The cabinets arrived this morning, and they look great."}'),
  ('A Radio Debate on Rent Control', '{"audioText":"We have to distinguish between what a policy intends and what it actually does.","correctAnswer":"We have to distinguish between what a policy intends and what it actually does."}'),
  ('A Talk on Translation', '{"audioText":"Every translator is forced into a series of small betrayals.","correctAnswer":"Every translator is forced into a series of small betrayals."}'),
  ('An Interview on AI and Accountability', '{"audioText":"What matters is accountability rather than perfect explainability.","correctAnswer":"What matters is accountability rather than perfect explainability."}')
) as gen(title_en, content)
  on lc.title_en = gen.title_en;

delete from public.exercises e using public.listening_clips lc
where e.listening_clip_id = lc.id and e.type = 'mcq' and lc.title_en in ('Ordering Coffee', 'A Phone Call', 'Weekend Plans', 'At School', 'At the Supermarket')
  and e.content->>'prompt' in ('מה מזמינים?', 'מה רוצים בקפה?', 'מה השם של מי שמתקשרת?', 'את מי אנה מחפשת?', 'לאן הולכים בסוף השבוע?', 'מה קונים?', 'באיזה עמוד פותחים את הספר?', 'מה עושים כשיש שאלה?', 'מה מחפשים?', 'באיזה מעבר נמצא החלב?');

insert into public.exercises (type, skill_area, listening_clip_id, cefr_level, content, sort_order)
select 'mcq'::exercise_type, 'listening'::skill_area, lc.id, lc.cefr_level, gen.content::jsonb, gen.sort_order
from public.listening_clips lc
join (values
  ('Ordering Coffee', '{"prompt":"מה מזמינים?","options":["Tea","Coffee","Juice","Water"],"correctIndex":1}', 2),
  ('Ordering Coffee', '{"prompt":"מה רוצים בקפה?","options":["Milk and sugar","Only sugar","Only milk","Nothing"],"correctIndex":2}', 3),
  ('A Phone Call', '{"prompt":"מה השם של מי שמתקשרת?","options":["Sara","Anna","Maya","Dana"],"correctIndex":1}', 2),
  ('A Phone Call', '{"prompt":"את מי אנה מחפשת?","options":["The teacher","The father","The mother","The brother"],"correctIndex":2}', 3),
  ('Weekend Plans', '{"prompt":"לאן הולכים בסוף השבוע?","options":["To the beach","To the market","To the park","To school"],"correctIndex":1}', 2),
  ('Weekend Plans', '{"prompt":"מה קונים?","options":["Fish and rice","Cake and juice","Apples and bread","Milk and eggs"],"correctIndex":2}', 3),
  ('At School', '{"prompt":"באיזה עמוד פותחים את הספר?","options":["Page five","Page ten","Page twelve","Page two"],"correctIndex":1}', 2),
  ('At School', '{"prompt":"מה עושים כשיש שאלה?","options":["Write it down","Stand up","Raise your hand","Call the teacher"],"correctIndex":2}', 3),
  ('At the Supermarket', '{"prompt":"מה מחפשים?","options":["Bread","Milk","Water","Eggs"],"correctIndex":1}', 2),
  ('At the Supermarket', '{"prompt":"באיזה מעבר נמצא החלב?","options":["Aisle one","Aisle two","Aisle three","Aisle four"],"correctIndex":2}', 3)
) as gen(title_en, content, sort_order)
  on lc.title_en = gen.title_en;

-- Check: clips from this seed, and their questions.
select
  (select count(*) from public.listening_clips where title_en in ('At the Bakery', 'Meeting in the Park', 'The Weather Today', 'After School', 'A Product Launch Briefing', 'A Lecture on Sleep and Memory', 'A Voicemail from a Contractor', 'A Radio Debate on Rent Control', 'A Talk on Translation', 'An Interview on AI and Accountability')) as new_clips,
  (select count(*) from public.exercises e join public.listening_clips lc on lc.id = e.listening_clip_id
     where e.type = 'mcq' and lc.title_en in ('At the Bakery', 'Meeting in the Park', 'The Weather Today', 'After School', 'A Product Launch Briefing', 'A Lecture on Sleep and Memory', 'A Voicemail from a Contractor', 'A Radio Debate on Rent Control', 'A Talk on Translation', 'An Interview on AI and Accountability', 'Ordering Coffee', 'A Phone Call', 'Weekend Plans', 'At School', 'At the Supermarket')) as listening_questions;
