-- 037_vocab_set_3 (generated by scripts/generate-vocab.mjs from
-- scripts/content/vocabSet3.mjs; edit the content there, not here).
-- 7 new vocabulary topics, 70 words (A1: 0, A2: 0, B1: 0, B2: 10, C1: 30, C2: 30), each with
-- IPA, an example and an English definition, plus one MCQ per word and two
-- match exercises per topic. All content is original.
-- Safe to re-run: topics are upserted by slug, and their words and
-- exercises are cleared and reinserted.

insert into public.topics (slug, name_he, name_en, cefr_level, sort_order) values
  ('digital-life', 'חיים דיגיטליים', 'Digital Life', 'B2', 51),
  ('science-technology', 'מדע וטכנולוגיה', 'Science & Technology', 'C1', 52),
  ('workplace-dynamics', 'יחסים בעבודה', 'Workplace Dynamics', 'C1', 53),
  ('culture-heritage', 'תרבות ומורשת', 'Culture & Heritage', 'C1', 54),
  ('philosophy-ethics', 'פילוסופיה ואתיקה', 'Philosophy & Ethics', 'C2', 55),
  ('law-jurisprudence', 'משפט ומשפטנות', 'Law & Jurisprudence', 'C2', 56),
  ('advanced-economics', 'כלכלה ופיננסים', 'Economics & Finance', 'C2', 57)
on conflict (slug) do update set
  name_he = excluded.name_he,
  name_en = excluded.name_en,
  cefr_level = excluded.cefr_level,
  sort_order = excluded.sort_order;

delete from public.exercises where topic_id in (select id from public.topics where slug in ('digital-life', 'science-technology', 'workplace-dynamics', 'culture-heritage', 'philosophy-ethics', 'law-jurisprudence', 'advanced-economics'));
delete from public.vocabulary_items where topic_id in (select id from public.topics where slug in ('digital-life', 'science-technology', 'workplace-dynamics', 'culture-heritage', 'philosophy-ethics', 'law-jurisprudence', 'advanced-economics'));

insert into public.vocabulary_items (topic_id, headword, ipa, part_of_speech, translation_he, example_en, definition_en, cefr_level, sort_order)
select t.id, v.headword, v.ipa, v.part_of_speech, v.translation_he, v.example_en, v.definition_en, t.cefr_level, v.sort_order
from public.topics t
join (values
  ('digital-life', 'privacy', '/ˈpraɪvəsi/', 'noun', 'פרטיות', 'Check the privacy settings before you post photos of your children.', 'the right to keep your personal information to yourself', 1),
  ('digital-life', 'notification', '/ˌnoʊtəfɪˈkeɪʃən/', 'noun', 'התראה', 'I turned off notifications so I could focus on my work.', 'a message on your phone telling you something has happened', 2),
  ('digital-life', 'subscription', '/səbˈskrɪpʃən/', 'noun', 'מנוי', 'She cancelled her streaming subscription to save money.', 'a regular payment to use a service', 3),
  ('digital-life', 'algorithm', '/ˈælɡərɪðəm/', 'noun', 'אלגוריתם', 'The app''s algorithm decides which videos you see first.', 'a set of rules a computer follows to make decisions', 4),
  ('digital-life', 'upload', '/ˈʌploʊd/', 'verb', 'להעלות (קובץ)', 'It took ten minutes to upload the video.', 'to send a file from your device to the internet', 5),
  ('digital-life', 'browser', '/ˈbraʊzər/', 'noun', 'דפדפן', 'Try opening the website in a different browser.', 'a program you use to look at websites', 6),
  ('digital-life', 'screen time', '/ˈskriːn taɪm/', 'noun', 'זמן מסך', 'My screen time doubled during the exams.', 'the time you spend looking at a phone or computer', 7),
  ('digital-life', 'hack', '/hæk/', 'verb', 'לפרוץ (למחשב או לחשבון)', 'Someone tried to hack my email account last night.', 'to get into a computer system without permission', 8),
  ('digital-life', 'offline', '/ˌɔːfˈlaɪn/', 'adjective', 'לא מחובר לרשת', 'You can read the articles offline once they''re downloaded.', 'not connected to the internet', 9),
  ('digital-life', 'cyberbullying', '/ˈsaɪbərˌbʊliɪŋ/', 'noun', 'בריונות ברשת', 'The school runs a workshop on cyberbullying every year.', 'using the internet to hurt or frighten someone', 10),
  ('science-technology', 'innovation', '/ˌɪnəˈveɪʃən/', 'noun', 'חדשנות', 'The country invests heavily in innovation and research.', 'a new idea, method or product', 1),
  ('science-technology', 'breakthrough', '/ˈbreɪkθruː/', 'noun', 'פריצת דרך', 'The new vaccine was hailed as a major breakthrough.', 'an important discovery that solves a problem', 2),
  ('science-technology', 'prototype', '/ˈproʊtətaɪp/', 'noun', 'אב טיפוס', 'The engineers tested the prototype for six months.', 'the first model of something, made to test it', 3),
  ('science-technology', 'automation', '/ˌɔːtəˈmeɪʃən/', 'noun', 'אוטומציה', 'Automation has replaced many factory jobs.', 'the use of machines to do work that people did', 4),
  ('science-technology', 'patent', '/ˈpætənt/', 'noun', 'פטנט', 'She filed a patent for her new water filter.', 'a legal right to be the only one to make or sell an invention', 5),
  ('science-technology', 'obsolete', '/ˌɑːbsəˈliːt/', 'adjective', 'מיושן, שיצא משימוש', 'Fax machines became obsolete almost overnight.', 'no longer used because something better exists', 6),
  ('science-technology', 'cutting-edge', '/ˌkʌtɪŋ ˈedʒ/', 'adjective', 'חדשני ביותר', 'The lab uses cutting-edge equipment.', 'the most modern and advanced', 7),
  ('science-technology', 'feasible', '/ˈfiːzəbəl/', 'adjective', 'בר ביצוע', 'Is it feasible to finish the project by June?', 'possible to do in practice', 8),
  ('science-technology', 'sophisticated', '/səˈfɪstɪkeɪtɪd/', 'adjective', 'מתוחכם', 'The system uses sophisticated software to detect fraud.', 'complex and advanced', 9),
  ('science-technology', 'implement', '/ˈɪmplɪment/', 'verb', 'ליישם', 'The company will implement the new system next year.', 'to start using a plan or system', 10),
  ('workplace-dynamics', 'delegate', '/ˈdeləɡeɪt/', 'verb', 'להאציל סמכויות', 'Good managers know how to delegate tasks to their team.', 'to give part of your work to someone else', 1),
  ('workplace-dynamics', 'burnout', '/ˈbɜːrnaʊt/', 'noun', 'שחיקה', 'Long hours without breaks can lead to burnout.', 'extreme tiredness caused by working too hard for too long', 2),
  ('workplace-dynamics', 'morale', '/məˈræl/', 'noun', 'מורל', 'Team morale improved after the new manager arrived.', 'how confident and positive people in a group feel', 3),
  ('workplace-dynamics', 'initiative', '/ɪˈnɪʃətɪv/', 'noun', 'יוזמה', 'She showed initiative by fixing the problem before anyone asked.', 'the ability to act without being told what to do', 4),
  ('workplace-dynamics', 'hierarchy', '/ˈhaɪərɑːrki/', 'noun', 'היררכיה', 'Start-ups often have a flat hierarchy.', 'a system where people are organized in levels of power', 5),
  ('workplace-dynamics', 'collaborate', '/kəˈlæbəreɪt/', 'verb', 'לשתף פעולה', 'The two departments collaborated on the new product.', 'to work together with someone', 6),
  ('workplace-dynamics', 'productivity', '/ˌproʊdʌkˈtɪvəti/', 'noun', 'פריון', 'Productivity dropped during the summer months.', 'how much work is done in a period of time', 7),
  ('workplace-dynamics', 'mentor', '/ˈmentɔːr/', 'noun', 'חונך', 'My first mentor taught me how to run a meeting.', 'an experienced person who advises someone less experienced', 8),
  ('workplace-dynamics', 'accountability', '/əˌkaʊntəˈbɪləti/', 'noun', 'אחריותיות, נשיאה באחריות', 'The new policy increases accountability for decisions.', 'being responsible for your actions and able to explain them', 9),
  ('workplace-dynamics', 'constructive', '/kənˈstrʌktɪv/', 'adjective', 'בונה', 'Thanks for the constructive feedback on my report.', 'useful and meant to help improve something', 10),
  ('culture-heritage', 'heritage', '/ˈherɪtɪdʒ/', 'noun', 'מורשת', 'The old city is part of the country''s cultural heritage.', 'traditions, buildings and history passed down from the past', 1),
  ('culture-heritage', 'custom', '/ˈkʌstəm/', 'noun', 'מנהג', 'It''s a local custom to bring sweets when you visit someone.', 'a traditional way of doing something', 2),
  ('culture-heritage', 'etiquette', '/ˈetɪket/', 'noun', 'כללי נימוס', 'Business etiquette varies a lot between countries.', 'the rules of polite behavior', 3),
  ('culture-heritage', 'cosmopolitan', '/ˌkɑːzməˈpɑːlɪtən/', 'adjective', 'קוסמופוליטי', 'Tel Aviv has a cosmopolitan atmosphere.', 'full of people and influences from many countries', 4),
  ('culture-heritage', 'assimilate', '/əˈsɪməleɪt/', 'verb', 'להיטמע', 'Many immigrants assimilate quickly into the new culture.', 'to become part of a new group or culture', 5),
  ('culture-heritage', 'indigenous', '/ɪnˈdɪdʒənəs/', 'adjective', 'ילידי', 'The museum displays indigenous art from the region.', 'belonging to the original people of a place', 6),
  ('culture-heritage', 'diaspora', '/daɪˈæspərə/', 'noun', 'תפוצה', 'The festival brings together members of the diaspora.', 'people who live outside the country their family came from', 7),
  ('culture-heritage', 'ritual', '/ˈrɪtʃuəl/', 'noun', 'טקס, ריטואל', 'Making coffee is my morning ritual.', 'an action always done in the same way, often for a ceremony', 8),
  ('culture-heritage', 'multicultural', '/ˌmʌltiˈkʌltʃərəl/', 'adjective', 'רב-תרבותי', 'We grew up in a multicultural neighborhood.', 'including people of many different cultures', 9),
  ('culture-heritage', 'preserve', '/prɪˈzɜːrv/', 'verb', 'לשמר', 'Volunteers work to preserve the old synagogue.', 'to keep something in its original state', 10),
  ('philosophy-ethics', 'dilemma', '/dɪˈlemə/', 'noun', 'דילמה', 'She faced a moral dilemma between loyalty and honesty.', 'a situation where you must choose between two difficult options', 1),
  ('philosophy-ethics', 'utilitarian', '/juːˌtɪlɪˈteriən/', 'adjective', 'תועלתני', 'A utilitarian view judges actions by their consequences.', 'aiming for the greatest good for the greatest number', 2),
  ('philosophy-ethics', 'autonomy', '/ɔːˈtɑːnəmi/', 'noun', 'אוטונומיה', 'Patients have the autonomy to refuse treatment.', 'the freedom to make your own decisions', 3),
  ('philosophy-ethics', 'integrity', '/ɪnˈteɡrəti/', 'noun', 'יושרה', 'He was respected for his integrity, even by his rivals.', 'the quality of being honest and having strong principles', 4),
  ('philosophy-ethics', 'virtue', '/ˈvɜːrtʃuː/', 'noun', 'מידה טובה', 'Patience is a virtue I''m still working on.', 'a good quality in a person''s character', 5),
  ('philosophy-ethics', 'determinism', '/dɪˈtɜːrmɪnɪzəm/', 'noun', 'דטרמיניזם', 'Determinism raises hard questions about free will.', 'the belief that every event is caused by earlier events', 6),
  ('philosophy-ethics', 'relativism', '/ˈrelətɪvɪzəm/', 'noun', 'רלטיביזם', 'Moral relativism holds that right and wrong depend on culture.', 'the idea that truth or morality is not the same for everyone', 7),
  ('philosophy-ethics', 'conscience', '/ˈkɑːnʃəns/', 'noun', 'מצפון', 'My conscience wouldn''t let me keep the money.', 'the inner sense of what is right and wrong', 8),
  ('philosophy-ethics', 'altruism', '/ˈæltruɪzəm/', 'noun', 'אלטרואיזם', 'Donating a kidney to a stranger is an act of pure altruism.', 'caring about others'' wellbeing more than your own', 9),
  ('philosophy-ethics', 'premise', '/ˈpremɪs/', 'noun', 'הנחת יסוד', 'The argument rests on a questionable premise.', 'an idea that an argument is based on', 10),
  ('law-jurisprudence', 'jurisdiction', '/ˌdʒʊrɪsˈdɪkʃən/', 'noun', 'סמכות שיפוט', 'The case falls outside the court''s jurisdiction.', 'the official power to make legal decisions', 1),
  ('law-jurisprudence', 'precedent', '/ˈpresɪdənt/', 'noun', 'תקדים', 'The ruling set an important precedent for future cases.', 'an earlier decision used as an example later', 2),
  ('law-jurisprudence', 'statute', '/ˈstætʃuːt/', 'noun', 'חוק כתוב', 'The statute was amended in 2019.', 'a written law passed by a parliament', 3),
  ('law-jurisprudence', 'litigation', '/ˌlɪtɪˈɡeɪʃən/', 'noun', 'התדיינות משפטית', 'The dispute ended in years of costly litigation.', 'the process of taking a case to court', 4),
  ('law-jurisprudence', 'plaintiff', '/ˈpleɪntɪf/', 'noun', 'תובע', 'The plaintiff claimed the product had caused the injury.', 'the person who brings a case against someone in court', 5),
  ('law-jurisprudence', 'defendant', '/dɪˈfendənt/', 'noun', 'נתבע, נאשם', 'The defendant denied all the charges.', 'the person accused or sued in court', 6),
  ('law-jurisprudence', 'injunction', '/ɪnˈdʒʌŋkʃən/', 'noun', 'צו מניעה', 'The court issued an injunction to stop the construction.', 'a court order that forbids an action', 7),
  ('law-jurisprudence', 'liability', '/ˌlaɪəˈbɪləti/', 'noun', 'חבות, אחריות משפטית', 'The company denied any liability for the accident.', 'legal responsibility for something', 8),
  ('law-jurisprudence', 'acquittal', '/əˈkwɪtəl/', 'noun', 'זיכוי', 'The trial ended in an acquittal.', 'a court decision that someone is not guilty', 9),
  ('law-jurisprudence', 'constitutional', '/ˌkɑːnstɪˈtuːʃənəl/', 'adjective', 'חוקתי', 'The judges ruled that the law was not constitutional.', 'allowed by or relating to a country''s constitution', 10),
  ('advanced-economics', 'austerity', '/ɔːˈsterəti/', 'noun', 'צנע', 'The government introduced austerity measures to cut the deficit.', 'strict cuts in public spending', 1),
  ('advanced-economics', 'liquidity', '/lɪˈkwɪdəti/', 'noun', 'נזילות', 'The bank faced a liquidity crisis.', 'having enough cash or assets that can quickly become cash', 2),
  ('advanced-economics', 'collateral', '/kəˈlætərəl/', 'noun', 'בטוחה', 'They used the house as collateral for the loan.', 'property promised to a lender in case a loan isn''t repaid', 3),
  ('advanced-economics', 'dividend', '/ˈdɪvɪdend/', 'noun', 'דיבידנד', 'Shareholders received a higher dividend this year.', 'a share of a company''s profit paid to its owners', 4),
  ('advanced-economics', 'solvency', '/ˈsɑːlvənsi/', 'noun', 'כושר פירעון', 'Investors questioned the firm''s solvency.', 'the ability to pay all your debts', 5),
  ('advanced-economics', 'speculation', '/ˌspekjəˈleɪʃən/', 'noun', 'ספקולציה', 'Speculation pushed housing prices to record highs.', 'buying something in the hope of selling it for more', 6),
  ('advanced-economics', 'deficit', '/ˈdefɪsɪt/', 'noun', 'גירעון', 'The budget deficit grew for the third year in a row.', 'the amount by which spending is greater than income', 7),
  ('advanced-economics', 'tariff', '/ˈtærɪf/', 'noun', 'מכס', 'New tariffs made imported cars more expensive.', 'a tax on goods coming into a country', 8),
  ('advanced-economics', 'depreciation', '/dɪˌpriːʃiˈeɪʃən/', 'noun', 'פחת, ירידת ערך', 'The car''s depreciation was faster than expected.', 'a fall in the value of something over time', 9),
  ('advanced-economics', 'equity', '/ˈekwəti/', 'noun', 'הון עצמי', 'The founders gave up some equity to raise money.', 'the value of a company that belongs to its owners', 10)
) as v(topic_slug, headword, ipa, part_of_speech, translation_he, example_en, definition_en, sort_order)
  on t.slug = v.topic_slug;

insert into public.exercises (type, skill_area, topic_id, vocabulary_item_id, cefr_level, content, sort_order)
select 'mcq'::exercise_type, 'vocabulary'::skill_area, t.id, v.id, t.cefr_level, gen.content::jsonb, gen.sort_order
from (values
  ('digital-life', 'privacy', '{"prompt":"מה המילה באנגלית עבור \"פרטיות\"?","options":["privacy","notification","algorithm","browser"],"correctIndex":0}', 1),
  ('digital-life', 'notification', '{"prompt":"מה המילה באנגלית עבור \"התראה\"?","options":["upload","notification","screen time","offline"],"correctIndex":1}', 2),
  ('digital-life', 'subscription', '{"prompt":"מה המילה באנגלית עבור \"מנוי\"?","options":["hack","cyberbullying","subscription","notification"],"correctIndex":2}', 3),
  ('digital-life', 'algorithm', '{"prompt":"מה המילה באנגלית עבור \"אלגוריתם\"?","options":["privacy","subscription","browser","algorithm"],"correctIndex":3}', 4),
  ('digital-life', 'upload', '{"prompt":"מה המילה באנגלית עבור \"להעלות (קובץ)\"?","options":["upload","algorithm","screen time","offline"],"correctIndex":0}', 5),
  ('digital-life', 'browser', '{"prompt":"מה המילה באנגלית עבור \"דפדפן\"?","options":["hack","browser","cyberbullying","notification"],"correctIndex":1}', 6),
  ('digital-life', 'screen time', '{"prompt":"מה המילה באנגלית עבור \"זמן מסך\"?","options":["privacy","subscription","screen time","upload"],"correctIndex":2}', 7),
  ('digital-life', 'hack', '{"prompt":"מה המילה באנגלית עבור \"לפרוץ (למחשב או לחשבון)\"?","options":["algorithm","browser","offline","hack"],"correctIndex":3}', 8),
  ('digital-life', 'offline', '{"prompt":"מה המילה באנגלית עבור \"לא מחובר לרשת\"?","options":["offline","screen time","cyberbullying","notification"],"correctIndex":0}', 9),
  ('digital-life', 'cyberbullying', '{"prompt":"מה המילה באנגלית עבור \"בריונות ברשת\"?","options":["privacy","cyberbullying","subscription","upload"],"correctIndex":1}', 10),
  ('science-technology', 'innovation', '{"prompt":"מה המילה באנגלית עבור \"חדשנות\"?","options":["innovation","breakthrough","automation","obsolete"],"correctIndex":0}', 1),
  ('science-technology', 'breakthrough', '{"prompt":"מה המילה באנגלית עבור \"פריצת דרך\"?","options":["patent","breakthrough","cutting-edge","sophisticated"],"correctIndex":1}', 2),
  ('science-technology', 'prototype', '{"prompt":"מה המילה באנגלית עבור \"אב טיפוס\"?","options":["feasible","implement","prototype","breakthrough"],"correctIndex":2}', 3),
  ('science-technology', 'automation', '{"prompt":"מה המילה באנגלית עבור \"אוטומציה\"?","options":["innovation","prototype","obsolete","automation"],"correctIndex":3}', 4),
  ('science-technology', 'patent', '{"prompt":"מה המילה באנגלית עבור \"פטנט\"?","options":["patent","automation","cutting-edge","sophisticated"],"correctIndex":0}', 5),
  ('science-technology', 'obsolete', '{"prompt":"מה המילה באנגלית עבור \"מיושן, שיצא משימוש\"?","options":["feasible","obsolete","implement","breakthrough"],"correctIndex":1}', 6),
  ('science-technology', 'cutting-edge', '{"prompt":"מה המילה באנגלית עבור \"חדשני ביותר\"?","options":["innovation","prototype","cutting-edge","patent"],"correctIndex":2}', 7),
  ('science-technology', 'feasible', '{"prompt":"מה המילה באנגלית עבור \"בר ביצוע\"?","options":["automation","obsolete","sophisticated","feasible"],"correctIndex":3}', 8),
  ('science-technology', 'sophisticated', '{"prompt":"מה המילה באנגלית עבור \"מתוחכם\"?","options":["sophisticated","cutting-edge","implement","breakthrough"],"correctIndex":0}', 9),
  ('science-technology', 'implement', '{"prompt":"מה המילה באנגלית עבור \"ליישם\"?","options":["innovation","implement","prototype","patent"],"correctIndex":1}', 10),
  ('workplace-dynamics', 'delegate', '{"prompt":"מה המילה באנגלית עבור \"להאציל סמכויות\"?","options":["delegate","burnout","initiative","collaborate"],"correctIndex":0}', 1),
  ('workplace-dynamics', 'burnout', '{"prompt":"מה המילה באנגלית עבור \"שחיקה\"?","options":["hierarchy","burnout","productivity","accountability"],"correctIndex":1}', 2),
  ('workplace-dynamics', 'morale', '{"prompt":"מה המילה באנגלית עבור \"מורל\"?","options":["mentor","constructive","morale","burnout"],"correctIndex":2}', 3),
  ('workplace-dynamics', 'initiative', '{"prompt":"מה המילה באנגלית עבור \"יוזמה\"?","options":["delegate","morale","collaborate","initiative"],"correctIndex":3}', 4),
  ('workplace-dynamics', 'hierarchy', '{"prompt":"מה המילה באנגלית עבור \"היררכיה\"?","options":["hierarchy","initiative","productivity","accountability"],"correctIndex":0}', 5),
  ('workplace-dynamics', 'collaborate', '{"prompt":"מה המילה באנגלית עבור \"לשתף פעולה\"?","options":["mentor","collaborate","constructive","burnout"],"correctIndex":1}', 6),
  ('workplace-dynamics', 'productivity', '{"prompt":"מה המילה באנגלית עבור \"פריון\"?","options":["delegate","morale","productivity","hierarchy"],"correctIndex":2}', 7),
  ('workplace-dynamics', 'mentor', '{"prompt":"מה המילה באנגלית עבור \"חונך\"?","options":["initiative","collaborate","accountability","mentor"],"correctIndex":3}', 8),
  ('workplace-dynamics', 'accountability', '{"prompt":"מה המילה באנגלית עבור \"אחריותיות, נשיאה באחריות\"?","options":["accountability","productivity","constructive","burnout"],"correctIndex":0}', 9),
  ('workplace-dynamics', 'constructive', '{"prompt":"מה המילה באנגלית עבור \"בונה\"?","options":["delegate","constructive","morale","hierarchy"],"correctIndex":1}', 10),
  ('culture-heritage', 'heritage', '{"prompt":"מה המילה באנגלית עבור \"מורשת\"?","options":["heritage","custom","cosmopolitan","indigenous"],"correctIndex":0}', 1),
  ('culture-heritage', 'custom', '{"prompt":"מה המילה באנגלית עבור \"מנהג\"?","options":["assimilate","custom","diaspora","multicultural"],"correctIndex":1}', 2),
  ('culture-heritage', 'etiquette', '{"prompt":"מה המילה באנגלית עבור \"כללי נימוס\"?","options":["ritual","preserve","etiquette","custom"],"correctIndex":2}', 3),
  ('culture-heritage', 'cosmopolitan', '{"prompt":"מה המילה באנגלית עבור \"קוסמופוליטי\"?","options":["heritage","etiquette","indigenous","cosmopolitan"],"correctIndex":3}', 4),
  ('culture-heritage', 'assimilate', '{"prompt":"מה המילה באנגלית עבור \"להיטמע\"?","options":["assimilate","cosmopolitan","diaspora","multicultural"],"correctIndex":0}', 5),
  ('culture-heritage', 'indigenous', '{"prompt":"מה המילה באנגלית עבור \"ילידי\"?","options":["ritual","indigenous","preserve","custom"],"correctIndex":1}', 6),
  ('culture-heritage', 'diaspora', '{"prompt":"מה המילה באנגלית עבור \"תפוצה\"?","options":["heritage","etiquette","diaspora","assimilate"],"correctIndex":2}', 7),
  ('culture-heritage', 'ritual', '{"prompt":"מה המילה באנגלית עבור \"טקס, ריטואל\"?","options":["cosmopolitan","indigenous","multicultural","ritual"],"correctIndex":3}', 8),
  ('culture-heritage', 'multicultural', '{"prompt":"מה המילה באנגלית עבור \"רב-תרבותי\"?","options":["multicultural","diaspora","preserve","custom"],"correctIndex":0}', 9),
  ('culture-heritage', 'preserve', '{"prompt":"מה המילה באנגלית עבור \"לשמר\"?","options":["heritage","preserve","etiquette","assimilate"],"correctIndex":1}', 10),
  ('philosophy-ethics', 'dilemma', '{"prompt":"מה המילה באנגלית עבור \"דילמה\"?","options":["dilemma","utilitarian","integrity","determinism"],"correctIndex":0}', 1),
  ('philosophy-ethics', 'utilitarian', '{"prompt":"מה המילה באנגלית עבור \"תועלתני\"?","options":["virtue","utilitarian","relativism","altruism"],"correctIndex":1}', 2),
  ('philosophy-ethics', 'autonomy', '{"prompt":"מה המילה באנגלית עבור \"אוטונומיה\"?","options":["conscience","premise","autonomy","utilitarian"],"correctIndex":2}', 3),
  ('philosophy-ethics', 'integrity', '{"prompt":"מה המילה באנגלית עבור \"יושרה\"?","options":["dilemma","autonomy","determinism","integrity"],"correctIndex":3}', 4),
  ('philosophy-ethics', 'virtue', '{"prompt":"מה המילה באנגלית עבור \"מידה טובה\"?","options":["virtue","integrity","relativism","altruism"],"correctIndex":0}', 5),
  ('philosophy-ethics', 'determinism', '{"prompt":"מה המילה באנגלית עבור \"דטרמיניזם\"?","options":["conscience","determinism","premise","utilitarian"],"correctIndex":1}', 6),
  ('philosophy-ethics', 'relativism', '{"prompt":"מה המילה באנגלית עבור \"רלטיביזם\"?","options":["dilemma","autonomy","relativism","virtue"],"correctIndex":2}', 7),
  ('philosophy-ethics', 'conscience', '{"prompt":"מה המילה באנגלית עבור \"מצפון\"?","options":["integrity","determinism","altruism","conscience"],"correctIndex":3}', 8),
  ('philosophy-ethics', 'altruism', '{"prompt":"מה המילה באנגלית עבור \"אלטרואיזם\"?","options":["altruism","relativism","premise","utilitarian"],"correctIndex":0}', 9),
  ('philosophy-ethics', 'premise', '{"prompt":"מה המילה באנגלית עבור \"הנחת יסוד\"?","options":["dilemma","premise","autonomy","virtue"],"correctIndex":1}', 10),
  ('law-jurisprudence', 'jurisdiction', '{"prompt":"מה המילה באנגלית עבור \"סמכות שיפוט\"?","options":["jurisdiction","precedent","litigation","defendant"],"correctIndex":0}', 1),
  ('law-jurisprudence', 'precedent', '{"prompt":"מה המילה באנגלית עבור \"תקדים\"?","options":["plaintiff","precedent","injunction","acquittal"],"correctIndex":1}', 2),
  ('law-jurisprudence', 'statute', '{"prompt":"מה המילה באנגלית עבור \"חוק כתוב\"?","options":["liability","constitutional","statute","precedent"],"correctIndex":2}', 3),
  ('law-jurisprudence', 'litigation', '{"prompt":"מה המילה באנגלית עבור \"התדיינות משפטית\"?","options":["jurisdiction","statute","defendant","litigation"],"correctIndex":3}', 4),
  ('law-jurisprudence', 'plaintiff', '{"prompt":"מה המילה באנגלית עבור \"תובע\"?","options":["plaintiff","litigation","injunction","acquittal"],"correctIndex":0}', 5),
  ('law-jurisprudence', 'defendant', '{"prompt":"מה המילה באנגלית עבור \"נתבע, נאשם\"?","options":["liability","defendant","constitutional","precedent"],"correctIndex":1}', 6),
  ('law-jurisprudence', 'injunction', '{"prompt":"מה המילה באנגלית עבור \"צו מניעה\"?","options":["jurisdiction","statute","injunction","plaintiff"],"correctIndex":2}', 7),
  ('law-jurisprudence', 'liability', '{"prompt":"מה המילה באנגלית עבור \"חבות, אחריות משפטית\"?","options":["litigation","defendant","acquittal","liability"],"correctIndex":3}', 8),
  ('law-jurisprudence', 'acquittal', '{"prompt":"מה המילה באנגלית עבור \"זיכוי\"?","options":["acquittal","injunction","constitutional","precedent"],"correctIndex":0}', 9),
  ('law-jurisprudence', 'constitutional', '{"prompt":"מה המילה באנגלית עבור \"חוקתי\"?","options":["jurisdiction","constitutional","statute","plaintiff"],"correctIndex":1}', 10),
  ('advanced-economics', 'austerity', '{"prompt":"מה המילה באנגלית עבור \"צנע\"?","options":["austerity","liquidity","dividend","speculation"],"correctIndex":0}', 1),
  ('advanced-economics', 'liquidity', '{"prompt":"מה המילה באנגלית עבור \"נזילות\"?","options":["solvency","liquidity","deficit","depreciation"],"correctIndex":1}', 2),
  ('advanced-economics', 'collateral', '{"prompt":"מה המילה באנגלית עבור \"בטוחה\"?","options":["tariff","equity","collateral","liquidity"],"correctIndex":2}', 3),
  ('advanced-economics', 'dividend', '{"prompt":"מה המילה באנגלית עבור \"דיבידנד\"?","options":["austerity","collateral","speculation","dividend"],"correctIndex":3}', 4),
  ('advanced-economics', 'solvency', '{"prompt":"מה המילה באנגלית עבור \"כושר פירעון\"?","options":["solvency","dividend","deficit","depreciation"],"correctIndex":0}', 5),
  ('advanced-economics', 'speculation', '{"prompt":"מה המילה באנגלית עבור \"ספקולציה\"?","options":["tariff","speculation","equity","liquidity"],"correctIndex":1}', 6),
  ('advanced-economics', 'deficit', '{"prompt":"מה המילה באנגלית עבור \"גירעון\"?","options":["austerity","collateral","deficit","solvency"],"correctIndex":2}', 7),
  ('advanced-economics', 'tariff', '{"prompt":"מה המילה באנגלית עבור \"מכס\"?","options":["dividend","speculation","depreciation","tariff"],"correctIndex":3}', 8),
  ('advanced-economics', 'depreciation', '{"prompt":"מה המילה באנגלית עבור \"פחת, ירידת ערך\"?","options":["depreciation","deficit","equity","liquidity"],"correctIndex":0}', 9),
  ('advanced-economics', 'equity', '{"prompt":"מה המילה באנגלית עבור \"הון עצמי\"?","options":["austerity","equity","collateral","solvency"],"correctIndex":1}', 10)
) as gen(topic_slug, headword, content, sort_order)
join public.topics t on t.slug = gen.topic_slug
join public.vocabulary_items v on v.topic_id = t.id and v.headword = gen.headword;

insert into public.exercises (type, skill_area, topic_id, cefr_level, content, sort_order)
select 'match'::exercise_type, 'vocabulary'::skill_area, t.id, t.cefr_level, gen.content::jsonb, gen.sort_order
from (values
  ('digital-life', '{"pairs":[{"left":"privacy","right":"פרטיות"},{"left":"notification","right":"התראה"},{"left":"subscription","right":"מנוי"},{"left":"algorithm","right":"אלגוריתם"},{"left":"upload","right":"להעלות (קובץ)"}]}', 100),
  ('digital-life', '{"pairs":[{"left":"browser","right":"דפדפן"},{"left":"screen time","right":"זמן מסך"},{"left":"hack","right":"לפרוץ (למחשב או לחשבון)"},{"left":"offline","right":"לא מחובר לרשת"},{"left":"cyberbullying","right":"בריונות ברשת"}]}', 101),
  ('science-technology', '{"pairs":[{"left":"innovation","right":"חדשנות"},{"left":"breakthrough","right":"פריצת דרך"},{"left":"prototype","right":"אב טיפוס"},{"left":"automation","right":"אוטומציה"},{"left":"patent","right":"פטנט"}]}', 100),
  ('science-technology', '{"pairs":[{"left":"obsolete","right":"מיושן, שיצא משימוש"},{"left":"cutting-edge","right":"חדשני ביותר"},{"left":"feasible","right":"בר ביצוע"},{"left":"sophisticated","right":"מתוחכם"},{"left":"implement","right":"ליישם"}]}', 101),
  ('workplace-dynamics', '{"pairs":[{"left":"delegate","right":"להאציל סמכויות"},{"left":"burnout","right":"שחיקה"},{"left":"morale","right":"מורל"},{"left":"initiative","right":"יוזמה"},{"left":"hierarchy","right":"היררכיה"}]}', 100),
  ('workplace-dynamics', '{"pairs":[{"left":"collaborate","right":"לשתף פעולה"},{"left":"productivity","right":"פריון"},{"left":"mentor","right":"חונך"},{"left":"accountability","right":"אחריותיות, נשיאה באחריות"},{"left":"constructive","right":"בונה"}]}', 101),
  ('culture-heritage', '{"pairs":[{"left":"heritage","right":"מורשת"},{"left":"custom","right":"מנהג"},{"left":"etiquette","right":"כללי נימוס"},{"left":"cosmopolitan","right":"קוסמופוליטי"},{"left":"assimilate","right":"להיטמע"}]}', 100),
  ('culture-heritage', '{"pairs":[{"left":"indigenous","right":"ילידי"},{"left":"diaspora","right":"תפוצה"},{"left":"ritual","right":"טקס, ריטואל"},{"left":"multicultural","right":"רב-תרבותי"},{"left":"preserve","right":"לשמר"}]}', 101),
  ('philosophy-ethics', '{"pairs":[{"left":"dilemma","right":"דילמה"},{"left":"utilitarian","right":"תועלתני"},{"left":"autonomy","right":"אוטונומיה"},{"left":"integrity","right":"יושרה"},{"left":"virtue","right":"מידה טובה"}]}', 100),
  ('philosophy-ethics', '{"pairs":[{"left":"determinism","right":"דטרמיניזם"},{"left":"relativism","right":"רלטיביזם"},{"left":"conscience","right":"מצפון"},{"left":"altruism","right":"אלטרואיזם"},{"left":"premise","right":"הנחת יסוד"}]}', 101),
  ('law-jurisprudence', '{"pairs":[{"left":"jurisdiction","right":"סמכות שיפוט"},{"left":"precedent","right":"תקדים"},{"left":"statute","right":"חוק כתוב"},{"left":"litigation","right":"התדיינות משפטית"},{"left":"plaintiff","right":"תובע"}]}', 100),
  ('law-jurisprudence', '{"pairs":[{"left":"defendant","right":"נתבע, נאשם"},{"left":"injunction","right":"צו מניעה"},{"left":"liability","right":"חבות, אחריות משפטית"},{"left":"acquittal","right":"זיכוי"},{"left":"constitutional","right":"חוקתי"}]}', 101),
  ('advanced-economics', '{"pairs":[{"left":"austerity","right":"צנע"},{"left":"liquidity","right":"נזילות"},{"left":"collateral","right":"בטוחה"},{"left":"dividend","right":"דיבידנד"},{"left":"solvency","right":"כושר פירעון"}]}', 100),
  ('advanced-economics', '{"pairs":[{"left":"speculation","right":"ספקולציה"},{"left":"deficit","right":"גירעון"},{"left":"tariff","right":"מכס"},{"left":"depreciation","right":"פחת, ירידת ערך"},{"left":"equity","right":"הון עצמי"}]}', 101)
) as gen(topic_slug, content, sort_order)
join public.topics t on t.slug = gen.topic_slug;

-- Check: topics, words and exercises this seed now has.
select
  (select count(*) from public.topics where slug in ('digital-life', 'science-technology', 'workplace-dynamics', 'culture-heritage', 'philosophy-ethics', 'law-jurisprudence', 'advanced-economics')) as topics,
  (select count(*) from public.vocabulary_items v join public.topics t on t.id = v.topic_id where t.slug in ('digital-life', 'science-technology', 'workplace-dynamics', 'culture-heritage', 'philosophy-ethics', 'law-jurisprudence', 'advanced-economics')) as words,
  (select count(*) from public.exercises e join public.topics t on t.id = e.topic_id where t.slug in ('digital-life', 'science-technology', 'workplace-dynamics', 'culture-heritage', 'philosophy-ethics', 'law-jurisprudence', 'advanced-economics')) as exercises;
