// Writes a grammar seed (topics + one lesson each + fill-in and reorder
// practice) from an authored content module. Same SQL shape as the grammar
// part of generate-level-expansion.mjs, with stricter checks.
// Run: node scripts/generate-grammar.mjs scripts/content/grammarSet2.mjs 031_grammar_set_2
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { pathToFileURL } from "node:url";
import { createClient } from "@supabase/supabase-js";

const [modulePath, seedName] = process.argv.slice(2);
if (!modulePath || !seedName) {
  console.error("usage: node scripts/generate-grammar.mjs <content module> <seed name>");
  process.exit(1);
}
const { GRAMMAR_TOPICS } = await import(pathToFileURL(modulePath).href);

const q = (s) => `'${String(s).replace(/'/g, "''")}'`;
const dollar = (s) => {
  if (s.includes("$$")) throw new Error("body contains $$");
  return `$$${s}$$`;
};
const json = (o) => q(JSON.stringify(o));
const HEB = /[֐-׿]/;
const LEVELS = ["A1", "A2", "B1", "B2", "C1", "C2"];

// ---- validation ----
const errors = [];
const slugs = new Set();
for (const g of GRAMMAR_TOPICS) {
  for (const k of ["slug", "name_he", "name_en", "level", "sort", "title_he", "body_md"]) if (!g[k]) errors.push(`${g.slug}: missing ${k}`);
  if (!LEVELS.includes(g.level)) errors.push(`${g.slug}: bad level ${g.level}`);
  if (slugs.has(g.slug)) errors.push(`duplicate slug ${g.slug}`);
  slugs.add(g.slug);
  // House style: no long dash in learner-facing Hebrew.
  for (const k of ["name_he", "title_he", "body_md"]) if (g[k]?.includes("—")) errors.push(`${g.slug}: long dash in ${k}`);
  if (g.fill.length < 4) errors.push(`${g.slug}: only ${g.fill.length} fill-in items`);
  for (const [sentence, answer, hint] of g.fill) {
    if ((sentence.match(/___/g) ?? []).length !== 1) errors.push(`${g.slug}: "${sentence}" needs exactly one ___`);
    if (!answer?.trim()) errors.push(`${g.slug}: empty answer in "${sentence}"`);
    if (hint && HEB.test(hint) && hint.includes("—")) errors.push(`${g.slug}: long dash in hint "${hint}"`);
  }
  for (const tokens of g.reorder) {
    if (tokens.length < 4) errors.push(`${g.slug}: reorder too short: ${tokens.join(" ")}`);
    if (tokens.some((t) => !t.trim() || /\s/.test(t))) errors.push(`${g.slug}: bad token in ${tokens.join("|")}`);
  }
}

// New topics only: a slug that already exists would silently replace a
// published lesson and its practice.
const envPath = new URL("../.env.local", import.meta.url);
if (existsSync(envPath)) {
  const env = Object.fromEntries(
    readFileSync(envPath, "utf8")
      .split(/\r?\n/)
      .filter((l) => l.includes("=") && !l.startsWith("#"))
      .map((l) => [l.slice(0, l.indexOf("=")), l.slice(l.indexOf("=") + 1).replace(/^"|"$/g, "")]),
  );
  const sb = createClient(env.NEXT_PUBLIC_SUPABASE_URL, env.SUPABASE_SERVICE_ROLE_KEY);
  const { data, error } = await sb.from("grammar_topics").select("slug,name_en");
  if (error) throw error;
  const taken = new Map(data.map((r) => [r.slug, r.name_en]));
  const takenNames = new Set(data.map((r) => r.name_en.toLowerCase()));
  for (const g of GRAMMAR_TOPICS) {
    if (taken.has(g.slug)) errors.push(`${g.slug}: slug already in the database`);
    if (takenNames.has(g.name_en.toLowerCase())) errors.push(`${g.slug}: topic "${g.name_en}" already in the database`);
  }
}

if (errors.length) {
  console.error(errors.join("\n"));
  process.exit(1);
}

// ---- SQL ----
const byLevel = LEVELS.map((l) => `${l}: ${GRAMMAR_TOPICS.filter((g) => g.level === l).length}`).join(", ");
const gSlugs = GRAMMAR_TOPICS.map((g) => q(g.slug)).join(", ");
const out = [];
out.push(`-- ${seedName} (generated by scripts/generate-grammar.mjs from
-- ${modulePath.replace(/\\/g, "/")}; edit the content there, not here).
-- ${GRAMMAR_TOPICS.length} new grammar topics (${byLevel}), each with a lesson,
-- fill-in practice and word-order practice. All content is original.
-- Safe to re-run: topics are upserted by slug, and their lessons and
-- exercises are cleared and reinserted.
`);
out.push(`insert into public.grammar_topics (slug, name_he, name_en, cefr_level, sort_order) values
${GRAMMAR_TOPICS.map((g) => `  (${q(g.slug)}, ${q(g.name_he)}, ${q(g.name_en)}, ${q(g.level)}, ${g.sort})`).join(",\n")}
on conflict (slug) do update set
  name_he = excluded.name_he,
  name_en = excluded.name_en,
  cefr_level = excluded.cefr_level,
  sort_order = excluded.sort_order;

delete from public.grammar_lessons where grammar_topic_id in (select id from public.grammar_topics where slug in (${gSlugs}));
delete from public.exercises where grammar_topic_id in (select id from public.grammar_topics where slug in (${gSlugs}));
`);
out.push(`insert into public.grammar_lessons (grammar_topic_id, title_he, body_md, cefr_level, sort_order)
select gt.id, l.title_he, l.body_md, gt.cefr_level, 1
from public.grammar_topics gt
join (values
${GRAMMAR_TOPICS.map((g) => `  (${q(g.slug)}, ${q(g.title_he)}, ${dollar(g.body_md)})`).join(",\n")}
) as l(slug, title_he, body_md) on gt.slug = l.slug;
`);
const fillRows = GRAMMAR_TOPICS.flatMap((g) =>
  g.fill.map(([sentence, correctAnswer, hint], i) => `  (${q(g.slug)}, ${json({ sentence, correctAnswer, hint })}, ${i + 1})`),
);
out.push(`insert into public.exercises (type, skill_area, grammar_topic_id, cefr_level, content, sort_order)
select 'fill_blank'::exercise_type, 'grammar'::skill_area, gt.id, gt.cefr_level, gen.content::jsonb, gen.sort_order
from (values
${fillRows.join(",\n")}
) as gen(slug, content, sort_order)
join public.grammar_topics gt on gt.slug = gen.slug;
`);
const reorderRows = GRAMMAR_TOPICS.flatMap((g) =>
  g.reorder.map((tokens, i) => `  (${q(g.slug)}, ${json({ tokens, correctOrder: tokens.map((_, k) => k) })}, ${100 + i})`),
);
out.push(`insert into public.exercises (type, skill_area, grammar_topic_id, cefr_level, content, sort_order)
select 'reorder'::exercise_type, 'grammar'::skill_area, gt.id, gt.cefr_level, gen.content::jsonb, gen.sort_order
from (values
${reorderRows.join(",\n")}
) as gen(slug, content, sort_order)
join public.grammar_topics gt on gt.slug = gen.slug;

-- Check: how many topics, lessons and exercises this seed now has.
select
  (select count(*) from public.grammar_topics where slug in (${gSlugs})) as topics,
  (select count(*) from public.grammar_lessons gl join public.grammar_topics gt on gt.id = gl.grammar_topic_id where gt.slug in (${gSlugs})) as lessons,
  (select count(*) from public.exercises e join public.grammar_topics gt on gt.id = e.grammar_topic_id where gt.slug in (${gSlugs})) as exercises;
`);

const path = new URL(`../supabase/seed/${seedName}.sql`, import.meta.url);
writeFileSync(path, out.join("\n"));
console.log(`wrote supabase/seed/${seedName}.sql: ${GRAMMAR_TOPICS.length} topics (${byLevel}), ${fillRows.length} fill-in + ${reorderRows.length} reorder exercises`);
