// Writes a vocabulary seed (topics + words + practice) from an authored
// content module. Same SQL shape as the vocabulary part of
// generate-level-expansion.mjs: one Hebrew-to-English MCQ per word with
// distractors from the same topic, and two match exercises per topic.
// Run: node scripts/generate-vocab.mjs scripts/content/vocabSet2.mjs 032_vocab_set_2
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { pathToFileURL } from "node:url";
import { createClient } from "@supabase/supabase-js";

const [modulePath, seedName] = process.argv.slice(2);
if (!modulePath || !seedName) {
  console.error("usage: node scripts/generate-vocab.mjs <content module> <seed name>");
  process.exit(1);
}
const { VOCAB_TOPICS } = await import(pathToFileURL(modulePath).href);

const q = (s) => `'${String(s).replace(/'/g, "''")}'`;
const json = (o) => q(JSON.stringify(o));
const LEVELS = ["A1", "A2", "B1", "B2", "C1", "C2"];

// ---- validation ----
const errors = [];
const seen = new Set();
for (const t of VOCAB_TOPICS) {
  for (const k of ["slug", "name_he", "name_en", "level", "sort"]) if (!t[k]) errors.push(`${t.slug}: missing ${k}`);
  if (!LEVELS.includes(t.level)) errors.push(`${t.slug}: bad level ${t.level}`);
  if (t.words.length < 8) errors.push(`${t.slug}: only ${t.words.length} words`);
  if (t.name_he.includes("—")) errors.push(`${t.slug}: long dash in name_he`);
  for (const w of t.words) {
    const [hw, ipa, , he, ex, def] = w;
    if (w.length !== 6 || w.some((x) => !x)) errors.push(`${t.slug}/${hw}: incomplete row`);
    if (!/^\/.+\/$/.test(ipa)) errors.push(`${hw}: IPA should be /.../`);
    if (he.includes("—")) errors.push(`${hw}: long dash in Hebrew`);
    const key = hw.toLowerCase();
    if (seen.has(key)) errors.push(`duplicate headword in this seed: ${hw}`);
    seen.add(key);
    if (!ex.toLowerCase().includes(key.split(" ")[0].slice(0, 4))) errors.push(`${hw}: example doesn't use the word`);
    if (def.toLowerCase().split(/\W+/).includes(key)) errors.push(`${hw}: definition uses the word itself`);
  }
}

// New words and topics only: a headword already in the table would show
// up twice for learners, and an existing slug would wipe a published topic.
const envPath = new URL("../.env.local", import.meta.url);
if (existsSync(envPath)) {
  const env = Object.fromEntries(
    readFileSync(envPath, "utf8")
      .split(/\r?\n/)
      .filter((l) => l.includes("=") && !l.startsWith("#"))
      .map((l) => [l.slice(0, l.indexOf("=")), l.slice(l.indexOf("=") + 1).replace(/^"|"$/g, "")]),
  );
  const sb = createClient(env.NEXT_PUBLIC_SUPABASE_URL, env.SUPABASE_SERVICE_ROLE_KEY);
  const [{ data: words, error: e1 }, { data: topics, error: e2 }] = await Promise.all([
    sb.from("vocabulary_items").select("headword").limit(10000),
    sb.from("topics").select("slug"),
  ]);
  if (e1 || e2) throw e1 ?? e2;
  const taken = new Set(words.map((w) => w.headword.toLowerCase().trim()));
  const takenSlugs = new Set(topics.map((t) => t.slug));
  for (const t of VOCAB_TOPICS) {
    if (takenSlugs.has(t.slug)) errors.push(`${t.slug}: topic slug already in the database`);
    for (const [hw] of t.words) if (taken.has(hw.toLowerCase())) errors.push(`${t.slug}/${hw}: headword already in the database`);
  }
}

if (errors.length) {
  console.error(errors.join("\n"));
  process.exit(1);
}

// ---- SQL ----
const byLevel = LEVELS.map((l) => `${l}: ${VOCAB_TOPICS.filter((t) => t.level === l).reduce((n, t) => n + t.words.length, 0)}`).join(", ");
const total = VOCAB_TOPICS.reduce((n, t) => n + t.words.length, 0);
const slugList = VOCAB_TOPICS.map((t) => q(t.slug)).join(", ");
const out = [];
out.push(`-- ${seedName} (generated by scripts/generate-vocab.mjs from
-- ${modulePath.replace(/\\/g, "/")}; edit the content there, not here).
-- ${VOCAB_TOPICS.length} new vocabulary topics, ${total} words (${byLevel}), each with
-- IPA, an example and an English definition, plus one MCQ per word and two
-- match exercises per topic. All content is original.
-- Safe to re-run: topics are upserted by slug, and their words and
-- exercises are cleared and reinserted.
`);
out.push(`insert into public.topics (slug, name_he, name_en, cefr_level, sort_order) values
${VOCAB_TOPICS.map((t) => `  (${q(t.slug)}, ${q(t.name_he)}, ${q(t.name_en)}, ${q(t.level)}, ${t.sort})`).join(",\n")}
on conflict (slug) do update set
  name_he = excluded.name_he,
  name_en = excluded.name_en,
  cefr_level = excluded.cefr_level,
  sort_order = excluded.sort_order;

delete from public.exercises where topic_id in (select id from public.topics where slug in (${slugList}));
delete from public.vocabulary_items where topic_id in (select id from public.topics where slug in (${slugList}));
`);
out.push(`insert into public.vocabulary_items (topic_id, headword, ipa, part_of_speech, translation_he, example_en, definition_en, cefr_level, sort_order)
select t.id, v.headword, v.ipa, v.part_of_speech, v.translation_he, v.example_en, v.definition_en, t.cefr_level, v.sort_order
from public.topics t
join (values
${VOCAB_TOPICS.flatMap((t) =>
  t.words.map(([hw, ipa, pos, he, ex, def], i) => `  (${q(t.slug)}, ${q(hw)}, ${q(ipa)}, ${q(pos)}, ${q(he)}, ${q(ex)}, ${q(def)}, ${i + 1})`),
).join(",\n")}
) as v(topic_slug, headword, ipa, part_of_speech, translation_he, example_en, definition_en, sort_order)
  on t.slug = v.topic_slug;
`);

const mcqRows = [];
for (const t of VOCAB_TOPICS) {
  t.words.forEach(([hw, , , he], i) => {
    const others = t.words.map((w) => w[0]).filter((w) => w !== hw);
    const distractors = [0, 1, 2].map((k) => others[(i * 3 + k * 2) % others.length]);
    if (new Set(distractors).size < 3) throw new Error(`distractors collide for ${hw}`);
    const correctIndex = i % 4;
    const options = [...distractors];
    options.splice(correctIndex, 0, hw);
    mcqRows.push(`  (${q(t.slug)}, ${q(hw)}, ${json({ prompt: `מה המילה באנגלית עבור "${he}"?`, options, correctIndex })}, ${i + 1})`);
  });
}
out.push(`insert into public.exercises (type, skill_area, topic_id, vocabulary_item_id, cefr_level, content, sort_order)
select 'mcq'::exercise_type, 'vocabulary'::skill_area, t.id, v.id, t.cefr_level, gen.content::jsonb, gen.sort_order
from (values
${mcqRows.join(",\n")}
) as gen(topic_slug, headword, content, sort_order)
join public.topics t on t.slug = gen.topic_slug
join public.vocabulary_items v on v.topic_id = t.id and v.headword = gen.headword;
`);

const matchRows = [];
for (const t of VOCAB_TOPICS) {
  [t.words.slice(0, 5), t.words.slice(5, 10)].forEach((group, k) => {
    if (group.length < 3) return;
    matchRows.push(`  (${q(t.slug)}, ${json({ pairs: group.map((w) => ({ left: w[0], right: w[3] })) })}, ${100 + k})`);
  });
}
out.push(`insert into public.exercises (type, skill_area, topic_id, cefr_level, content, sort_order)
select 'match'::exercise_type, 'vocabulary'::skill_area, t.id, t.cefr_level, gen.content::jsonb, gen.sort_order
from (values
${matchRows.join(",\n")}
) as gen(topic_slug, content, sort_order)
join public.topics t on t.slug = gen.topic_slug;

-- Check: topics, words and exercises this seed now has.
select
  (select count(*) from public.topics where slug in (${slugList})) as topics,
  (select count(*) from public.vocabulary_items v join public.topics t on t.id = v.topic_id where t.slug in (${slugList})) as words,
  (select count(*) from public.exercises e join public.topics t on t.id = e.topic_id where t.slug in (${slugList})) as exercises;
`);

const path = new URL(`../supabase/seed/${seedName}.sql`, import.meta.url);
writeFileSync(path, out.join("\n"));
console.log(`wrote supabase/seed/${seedName}.sql: ${VOCAB_TOPICS.length} topics, ${total} words (${byLevel}), ${mcqRows.length} MCQs + ${matchRows.length} matches`);
